import { io, type Socket } from 'socket.io-client';

import { type DaemonHandle } from '../shared/contracts';
import {
  type ItemDto as ChatItem,
  RunAwaiting,
  type RunPullRequest,
  RunStatus,
  type RunTaskGroup,
  type RunTaskRow,
} from './autogenerated';
import { type LiveTextEvent, parseLiveText } from './chats/live-text';

/** The three statuses a task row may carry; anything else reads as unknown. */
const TASK_STATUSES = new Set(['pending', 'in_progress', 'completed']);

/**
 * The task groups in a socket payload, keeping only the readable rows.
 *
 * Defensive for the reason {@link readPullRequestRefs} is: this is one of the
 * two shapes that arrive untyped, the generated client covering every other
 * route. An unreadable ROW is dropped rather than the group, because the chip
 * states `done/total` — losing one row shifts a count by one, while dropping the
 * group blanks a list the agent is visibly working through. Only `id` is
 * required: a patch legitimately carries no title, which is exactly why the
 * daemon's fold exists.
 */
function readTaskGroups(groups: readonly unknown[]): RunTaskGroup[] {
  const out: RunTaskGroup[] = [];
  for (const group of groups) {
    if (group === null || typeof group !== 'object') {
      continue;
    }
    const { nodeId, tasks } = group as Record<string, unknown>;
    if (!Array.isArray(tasks)) {
      continue;
    }
    const rows: RunTaskRow[] = [];
    for (const task of tasks) {
      if (task === null || typeof task !== 'object') {
        continue;
      }
      const { id, title, status, activeForm } = task as Record<string, unknown>;
      if (typeof id !== 'string' || id === '') {
        continue;
      }
      rows.push({
        id,
        title: typeof title === 'string' && title !== '' ? title : null,
        status:
          typeof status === 'string' && TASK_STATUSES.has(status)
            ? (status as RunTaskRow['status'])
            : null,
        activeForm:
          typeof activeForm === 'string' && activeForm !== ''
            ? activeForm
            : null,
      });
    }
    out.push({
      nodeId: typeof nodeId === 'string' ? nodeId : null,
      tasks: rows,
    });
  }
  return out;
}

/**
 * The pull-request refs in a socket payload, keeping only the whole ones.
 *
 * A REF is four fields and each is load-bearing downstream: the URL is what
 * `gh pr view` is addressed with, and the owner/repo/number are what a row is
 * named from. Anything short of all four is dropped rather than patched, since
 * a half-ref renders as a chip pointing nowhere — and this is the one place the
 * shapes arrive untyped, the generated client covering every other route.
 */
function readPullRequestRefs(rows: readonly unknown[]): RunPullRequest[] {
  const refs: RunPullRequest[] = [];
  for (const row of rows) {
    if (row === null || typeof row !== 'object') {
      continue;
    }
    const { owner, repo, number, url, seq } = row as Record<string, unknown>;
    if (
      typeof owner === 'string' &&
      owner !== '' &&
      typeof repo === 'string' &&
      repo !== '' &&
      typeof number === 'number' &&
      Number.isFinite(number) &&
      typeof url === 'string' &&
      url !== ''
    ) {
      // `seq` is the transcript position the capture recorded, and it only
      // orders them — the POSITION in the array already says the same thing,
      // so a payload that omits it falls back to that rather than losing the
      // ref over a field no surface reads.
      refs.push({
        owner,
        repo,
        number,
        url,
        seq:
          typeof seq === 'number' && Number.isFinite(seq) ? seq : refs.length,
      });
    }
  }
  return refs;
}

export interface DaemonClientEvents {
  onOpen?: () => void;
  onMessage?: (event: string, data: unknown) => void;
  /** `reason` is Socket.IO's own word for why the socket dropped. */
  onClose?: (reason: string) => void;
  /**
   * A connection ATTEMPT failed — the daemon is not answering, or it refused
   * the handshake token.
   *
   * Separate from `onClose` because the two are different facts and only this
   * one is actionable: a close is a live connection ending (often the daemon
   * restarting, and Socket.IO reconnects on its own), while this fires on
   * every retry of a connection that was never made. Without it a daemon that
   * is down produces no signal at all beyond a status dot changing colour —
   * which is the reported "if we have a problem with the api/connection we
   * should see it in the UI".
   */
  onError?: (message: string) => void;
}

/**
 * TWIN PARSER: mirrors the `verdict_ack` reply shape produced by the daemon's
 * `NotificationsGateway.verdict`
 * (apps/daemon/src/v1/notifications/gateways/notifications.gateway.ts) — no
 * daemon↔renderer shared package exists, so a shape change there must be
 * mirrored here, and vice versa.
 */
export interface VerdictAck {
  runId: string | null;
  requestId: string | null;
  status: 'applied' | 'expired' | 'invalid';
}

/**
 * TWIN PARSER: mirrors the daemon's `RunStatusEvent`
 * (apps/daemon/src/v1/agents/chat.types.ts), broadcast on `run_status`.
 * Outside the generated HTTP contract, so a shape change on either side MUST
 * be mirrored on the other.
 *
 * Broadcast to every client rather than to a run's room: the sidebar shows
 * runs the user is not looking at, and only the focused run's room delivers
 * items — so without this a background badge stayed stale until a refetch.
 */
export interface RunStatusEvent {
  runId: string;
  /**
   * The run's new status, or null when the event only says what the run is
   * DOING and asserts nothing about whether it is still going. See the
   * daemon-side field for why the activity announce cannot claim one.
   */
  status: RunStatus | null;
  /** What the run is doing right now, or null when it is not doing anything. */
  /**
   * What the run is doing right now, `null` when it is doing nothing — or
   * absent when this announce says nothing about it.
   *
   * Three states like `awaiting` below, and for the same reason: `null` is what
   * CLEARS the phrase, so an announce that never read the run must be able to
   * leave it alone rather than blank a running turn's row.
   */
  activity?: string | null;
  /**
   * ISO moment the run ROW was written — present on exactly the announces that
   * wrote it, absent on every activity-only one.
   *
   * It is what the sidebar orders on (`sortRunsForSidebar` reads `updatedAt`),
   * and the only thing allowed to move it: the snapshot is loaded once, so
   * without this a thread working in the background kept its load-time position
   * until the user opened it — and then jumped, because opening it was the
   * first moment anything here learned the truth.
   *
   * Absent asserts nothing, like `awaiting`. A tool-call announce does not
   * touch the row, so reading one as activity would put this list ahead of the
   * database and let the next refetch drag the thread back down.
   */
  at?: string;
  /**
   * Whether the run is parked on the user, on what — or `undefined` when this
   * event says nothing about it.
   *
   * Three states like `status` above, and for the same reason: only the two
   * transitions know about this, so an activity announce must leave the
   * client's reading alone rather than reset it. `undefined` is therefore NOT
   * interchangeable with `null` here — `null` is a run that has stopped
   * waiting.
   */
  awaiting?: RunAwaiting | null;
  /**
   * How many units of background work the run's turn is being HELD for, or
   * `undefined` when this event says nothing about it.
   *
   * A held turn is one whose agent has FINISHED and whose process is being kept
   * alive only until the delegates it launched report back. It is the state the
   * composer has to tell apart from a working agent: a message typed then must
   * go straight to the CLI, which is sitting idle waiting for those listeners,
   * rather than into the send-later queue.
   *
   * A COUNT rather than a boolean because it is also what the badge's sentence
   * is built from, and a fact both surfaces read cannot drift the way two
   * readings of one English phrase can. `0` says the hold is over.
   */
  holdingFor?: number;
  /**
   * How many DETACHED commands this run still has out, or `undefined` when this
   * event says nothing about it.
   *
   * Three states like {@link holdingFor} beside it: absent asserts nothing, `0`
   * says the last one has reported.
   *
   * It is NOT the same fact. A hold means the agent has stopped and the process
   * is being kept alive; a shell holds nothing open, so nothing may act on this
   * — the composer must not queue on it. Its one reader is the badge, which is
   * exactly why it has to ride this channel: the reading it replaced was folded
   * out of the OPEN thread's transcript, so an unfocused row could not see it
   * and the badge changed when the user looked away.
   */
  shellsOpen?: number;
  /**
   * When this run's FETCHED spend last CHANGED — the signal to ask for its
   * totals again, carrying no figure of its own.
   *
   * TWIN PARSER of the daemon's `RunStatusEvent`, where the reasoning is: it
   * exists for cursor, whose price is fetched from Cursor on a cadence no client
   * can see, so without it a figure landed on screen only when something else
   * happened to refetch — the next turn's settle, or reopening the chat.
   * `useChatTotals` re-asks on it; nothing here reads a number off it, and the
   * daemon sends none, because the totals route is the one place they are summed.
   */
  spendUpdatedAt?: number;
  /**
   * The pull requests this run has been seen to OPEN, when a capture pass has
   * just found one.
   *
   * TWIN PARSER of the daemon's `RunStatusEvent` — absent asserts nothing, and
   * the daemon announces this only when a turn ENDED having changed the answer.
   * It rides this channel because the capture used to run on the chat listing
   * alone, which is one fetch per window: a thread that opened a pull request
   * during the session it was opened in never showed a chip for it.
   */
  pullRequests?: RunPullRequest[];
  /**
   * Each agent's own task list as the DAEMON folded it, over the whole
   * transcript.
   *
   * TWIN PARSER of the daemon's `RunStatusEvent` — absent asserts nothing, and
   * the daemon announces only when a new announcement actually MOVED the fold.
   * It rides this channel because a client's own fold is bounded by the
   * transcript window it loaded: neither CLI re-states the whole list, so past
   * `HISTORY_PAGE` items the opening announcement falls out and the chip's total
   * shrinks rather than going obviously blank.
   */
  taskList?: RunTaskGroup[];
  /**
   * How full this run's context window was when its CLI last reported, and the
   * window it is measured against.
   *
   * TWIN PARSER of the daemon's `RunStatusEvent` — absent asserts nothing, a
   * value sets, and the COUNT may be null beside a window (a compaction, whose
   * conversation is gone while the model's window is not).
   *
   * It rides this channel for the reason every other row-carried fact does: a
   * client only ever learned it from the run list its window opened with, or
   * from the live deltas of the ONE run it has joined — so a thread that worked
   * for an hour while the user was elsewhere left the ring drawing an hour-old
   * figure that only a hover would correct.
   */
  contextTokens?: number | null;
  contextWindowTokens?: number | null;
  /**
   * What the run said as it reached this status — the agent's closing words, or
   * a failure's message.
   *
   * Three states like {@link awaiting} and {@link holdingFor}: absent asserts
   * nothing (an activity announce), `null` says this settle had nothing to say
   * and CLEARS the last sentence. The distinction is the fix for a notification
   * that read back the PREVIOUS turn's answer — the client holds the last
   * summary it was given, and a `/compact` turn, which produces no assistant
   * message at all, used to arrive with the field simply missing.
   */
  summary?: string | null;
  /**
   * TWIN PARSER: `RunStatusEvent.preview` in
   * `apps/daemon/src/v1/agents/chat.types.ts` — the WS envelope has no
   * generated type, so a shape change there must be mirrored here.
   *
   * What the run just SAID, for the sidebar's preview line, pushed as each
   * message is persisted rather than only when the turn ends. Separate from
   * `summary` on both sides: that one is terminal-only and feeds the system
   * notification, and this must never reach it.
   *
   * Two states only — absent asserts nothing, and there is no clearing arm: a
   * message cannot be unsaid.
   */
  preview?: string;
  /**
   * True when the turn that reached this status did nothing but the CLI's own
   * context compaction. Absent on every other announce.
   *
   * The daemon says it because only the daemon can: a background chat's items
   * are never loaded here, and that is precisely the chat a banner is for.
   */
  housekeeping?: boolean;
  /**
   * True when this status is being handed BACK rather than newly reached — the
   * delegate lease expiring over a run that had already settled. Absent on
   * every other announce.
   *
   * Read alongside `housekeeping` and for the same reason: both mark a settle
   * that is not news. They stay separate fields because they answer different
   * questions — that one is about what the turn WAS, this is about whether the
   * status changed at all. A restore also carries no `summary`, so the sentence
   * from the real settle is left standing rather than blanked.
   */
  restored?: boolean;
  /**
   * The title the daemon has just given this run — absent on every announce
   * that did not name one.
   *
   * Two states rather than the three its neighbours draw: the only producer
   * names a run that had none, so there is no clearing case. A rename by the
   * user arrives as the PATCH's own response instead.
   */
  title?: string;
  /**
   * Whether a name for this run is being worked out right now — absent when the
   * announce says nothing about it, `true` while an attempt is in flight,
   * `false` once it has finished, named or not.
   */
  titlePending?: boolean;
}

/**
 * The runId out of a `{runId}` envelope, or null.
 *
 * TWIN PARSER: the daemon writes this envelope in
 * `notifications.gateway.ts`'s `run_deleted` emit. Deliberately its own reader
 * rather than a field pulled off {@link parseRunStatus}: that one requires a
 * status shape this event does not carry, and reusing it would refuse every
 * deletion.
 */
export function parseDeletedRunId(data: unknown): string | null {
  if (typeof data !== 'object' || data === null) {
    return null;
  }
  const { runId } = data as { runId?: unknown };
  return typeof runId === 'string' && runId.length > 0 ? runId : null;
}

/**
 * Read a `run_status` payload, or null when it is not one. Defensive because
 * the shape has no generated type behind it: a version skew must degrade to
 * "no live badge update", never to a crashed sidebar.
 */
export function parseRunStatus(data: unknown): RunStatusEvent | null {
  if (typeof data !== 'object' || data === null) {
    return null;
  }
  const {
    runId,
    status,
    activity,
    at,
    awaiting,
    holdingFor,
    shellsOpen,
    spendUpdatedAt,
    pullRequests,
    taskList,
    contextTokens,
    contextWindowTokens,
    summary,
    preview,
    housekeeping,
    restored,
    title,
    titlePending,
  } = data as Record<string, unknown>;
  if (typeof runId !== 'string' || runId.length === 0) {
    return null;
  }
  // Absent stays absent (this event asserts nothing about waiting); an explicit
  // null clears; an unrecognised kind is read as "parked, kind unknown" ⇒
  // dropped to absent rather than to null, because a skewed daemon that grew a
  // third kind is still telling us the run is blocked, and clearing would put a
  // spinner back on a run nobody can unblock without noticing.
  const parked =
    awaiting === undefined
      ? undefined
      : awaiting === null
        ? null
        : AWAITING_VALUES.has(awaiting as RunAwaiting)
          ? (awaiting as RunAwaiting)
          : undefined;
  // A MISSING or null status is an activity-only announce and is read as such.
  // An unrecognised one is still rejected outright: that is version skew, and
  // treating it as "no status" would silently downgrade a real status change
  // into an activity update rather than degrading to no update at all.
  const known = status === null || status === undefined;
  if (!known && !RUN_STATUS_VALUES.has(status as RunStatus)) {
    return null;
  }
  return {
    runId,
    status: known ? null : (status as RunStatus),
    // Absent stays absent, exactly like `awaiting` and `summary`: an announce
    // that carried no activity key asserts nothing, and reading it as `null`
    // would clear the phrase of a run that is still working. An explicit null
    // (or an empty string) still clears.
    ...(activity === undefined
      ? {}
      : {
          activity:
            typeof activity === 'string' && activity !== '' ? activity : null,
        }),
    // Kept only when it is a DATE. The sidebar compares these lexically, so a
    // string that is merely non-empty would not degrade to "no reorder" — it
    // would sort, wrongly, and stay wherever it landed until the next refetch.
    ...(typeof at === 'string' && Number.isFinite(Date.parse(at))
      ? { at }
      : {}),
    ...(parked === undefined ? {} : { awaiting: parked }),
    // Absent stays absent, exactly like `awaiting`: an ordinary activity
    // announce says nothing about the hold and must not clear it.
    ...(typeof holdingFor === 'number' && Number.isFinite(holdingFor)
      ? { holdingFor: Math.max(0, Math.trunc(holdingFor)) }
      : {}),
    // Read on the same terms as the hold above, and absent for the same reason:
    // an announce that carried no count says nothing about the commands this
    // run has out, and clearing on silence would take the badge down while a
    // `pnpm dev` was still running.
    ...(typeof shellsOpen === 'number' && Number.isFinite(shellsOpen)
      ? { shellsOpen: Math.max(0, Math.trunc(shellsOpen)) }
      : {}),
    // A MARKER rather than a reading: only its presence and its being newer
    // than the last one matter, so nothing here clamps or interprets the value
    // beyond requiring a finite number — a nonsense one would at worst cost one
    // extra totals fetch, where a `NaN` would compare unequal to itself forever
    // and re-fetch on every render.
    ...(typeof spendUpdatedAt === 'number' && Number.isFinite(spendUpdatedAt)
      ? { spendUpdatedAt }
      : {}),
    // Every entry checked, not merely the array: this arrives as a socket
    // payload rather than through the generated client, and a half-shaped ref
    // reaches `gh pr view` as a URL. An array that is present but holds nothing
    // usable is dropped whole rather than admitted empty, which would blank a
    // thread's chips on a turn that simply had nothing to say.
    ...(Array.isArray(pullRequests) && readPullRequestRefs(pullRequests).length
      ? { pullRequests: readPullRequestRefs(pullRequests) }
      : {}),
    // Admitted whenever it is an ARRAY, including an empty one — unlike the
    // pull requests above, where empty is dropped. The two differ because the
    // daemon announces this only when the fold MOVED, and a list moving to
    // nothing (a snapshot that cleared it) is a real reading the chip has to
    // act on; a pull-request announce carrying nothing usable is only ever a
    // malformed payload, since a run that opened none is never announced.
    ...(Array.isArray(taskList) ? { taskList: readTaskGroups(taskList) } : {}),
    // The PAIR travels together or not at all: a count is only a reading with
    // the window it was measured against, and admitting half would let a fresh
    // count be scaled against a window from before a model change. `null` is a
    // real value for the count alone — a compaction clears it and keeps the
    // window — so the guard admits a number OR null, and nothing else.
    ...((typeof contextTokens === 'number' && Number.isFinite(contextTokens)) ||
    contextTokens === null
      ? {
          contextTokens:
            contextTokens === null
              ? null
              : Math.max(0, Math.trunc(contextTokens)),
          contextWindowTokens:
            typeof contextWindowTokens === 'number' &&
            Number.isFinite(contextWindowTokens)
              ? Math.max(0, Math.trunc(contextWindowTokens))
              : null,
        }
      : {}),
    // Three states, and the empty string is deliberately one of the CLEARING
    // ones: a settle whose agent said nothing arrives as null, and a daemon
    // that sent `''` means the same thing. Only a MISSING field leaves the
    // client's last sentence standing, which is what an activity announce does.
    ...(summary === undefined
      ? {}
      : {
          summary:
            typeof summary === 'string' && summary !== '' ? summary : null,
        }),
    // Only a non-empty string, and no clearing arm: an empty preview would be
    // the daemon saying the thread's last message is blank, which no row ever
    // is — a skewed value leaves the line where it was.
    ...(typeof preview === 'string' && preview !== '' ? { preview } : {}),
    ...(housekeeping === true ? { housekeeping: true } : {}),
    ...(restored === true ? { restored: true } : {}),
    // An empty string is dropped rather than applied: a blank title would
    // relabel the row with nothing, which reads as the chat having lost its name.
    ...(typeof title === 'string' && title !== '' ? { title } : {}),
    // Only a real boolean, so a skewed daemon sending something else leaves the
    // client's reading alone rather than latching a shimmer nothing lowers.
    ...(typeof titlePending === 'boolean' ? { titlePending } : {}),
  };
}

/** The generated enum as a lookup, so an unknown status is rejected. */
const RUN_STATUS_VALUES: ReadonlySet<RunStatus> = new Set(
  Object.values(RunStatus),
);

/** Same, for the awaiting kinds. */
const AWAITING_VALUES: ReadonlySet<RunAwaiting> = new Set(
  Object.values(RunAwaiting),
);

/**
 * One line of the daemon's debug log, as it arrives on the `debug` event.
 *
 * TWIN PARSER: mirrors `DebugEntrySchema`
 * (apps/daemon/src/v1/diagnostics/diagnostics.types.ts). The HTTP read of the
 * same shape IS generated (`DebugLogPageDto`), but this event carries no route
 * so no generated type reaches it — a shape change on either side must be
 * mirrored on the other.
 */
export interface DebugLogEntry {
  seq: number;
  at: string;
  channel: string;
  level: string;
  message: string;
  context: Record<string, string> | null;
}

/**
 * Read a `debug` payload, or null when it is not one.
 *
 * Defensive for the reason every twin parser here is: a version skew must
 * degrade to "the panel misses a line", never to a crashed app — and this one
 * is the DEBUG panel, so failing loudly inside it would take out the surface
 * someone is using precisely because something else is already wrong.
 */
export function parseDebugEntry(data: unknown): DebugLogEntry | null {
  if (typeof data !== 'object' || data === null) {
    return null;
  }
  const { seq, at, channel, level, message, context } = data as Record<
    string,
    unknown
  >;
  if (
    typeof seq !== 'number' ||
    typeof at !== 'string' ||
    typeof channel !== 'string' ||
    typeof level !== 'string' ||
    typeof message !== 'string'
  ) {
    return null;
  }
  return {
    seq,
    at,
    channel,
    level,
    message,
    context:
      context && typeof context === 'object'
        ? (context as Record<string, string>)
        : null,
  };
}

/**
 * A turn the daemon has just written to its usage ledger.
 *
 * TWIN PARSER: mirrors the daemon's `UsageRecordedEvent`
 * (apps/daemon/src/v1/stats/stats.types.ts), broadcast on `usage_recorded`.
 * It rides `/ws`, which has no OpenAPI document, so no generated type reaches
 * it — a shape change on either side must be mirrored on the other.
 *
 * Broadcast to every client, not to a run's room: the page that reads it is
 * Stats, which is about every run at once and joins no room at all.
 */
export interface UsageRecordedEvent {
  runId: string;
  nodeId: string | null;
  occurredAt: string;
}

/**
 * Read a `usage_recorded` payload, or null when it is not one.
 *
 * Defensive like its neighbours: the worst a skew may cost is a Stats page that
 * refreshes on the next turn instead of this one.
 */
export function parseUsageRecorded(data: unknown): UsageRecordedEvent | null {
  if (typeof data !== 'object' || data === null) {
    return null;
  }
  const { runId, nodeId, occurredAt } = data as Record<string, unknown>;
  if (typeof runId !== 'string' || typeof occurredAt !== 'string') {
    return null;
  }
  return {
    runId,
    nodeId: typeof nodeId === 'string' ? nodeId : null,
    occurredAt,
  };
}

const JOIN_TIMEOUT_MS = 5_000;

interface JoinWaiter {
  resolve: () => void;
  reject: (error: Error) => void;
  timer: ReturnType<typeof setTimeout>;
}

/**
 * Thin Socket.IO client to the loopback daemon. Authenticates with the
 * per-launch token via the handshake `auth` payload (browsers can't set WS
 * headers) and lets Socket.IO own reconnection. Forces the `websocket`
 * transport — no HTTP long-polling fallback is needed on loopback. M2 grows it
 * from the M1 hello/echo proof into the live run-event channel: `join`/`leave`
 * a run's room and receive its persisted `item` events.
 *
 * Socket.IO rooms are per-socket and server-side, so a transient
 * disconnect/reconnect lands a fresh socket id in NO rooms. The client tracks
 * the active run and re-emits `join` on every (re)connect, and fires
 * `onReconnect` so the renderer can fetch the items it missed while offline
 * (the room buffers nothing for an absent member).
 */
export class DaemonClient {
  private socket: Socket | null = null;
  private readonly itemListeners = new Set<(item: ChatItem) => void>();
  private readonly liveTextListeners = new Set<
    (event: LiveTextEvent) => void
  >();
  private readonly reconnectListeners = new Set<(error?: Error) => void>();
  private readonly disconnectListeners = new Set<() => void>();
  private readonly verdictAckListeners = new Set<(ack: VerdictAck) => void>();
  private readonly runStatusListeners = new Set<
    (event: RunStatusEvent) => void
  >();
  private readonly usageListeners = new Set<
    (event: UsageRecordedEvent) => void
  >();
  private readonly runDeletedListeners = new Set<(runId: string) => void>();
  private readonly joinWaiters = new Map<string, Set<JoinWaiter>>();
  private readonly debugListeners = new Set<(entry: DebugLogEntry) => void>();
  private activeRunId: string | null = null;
  private hasConnected = false;
  /** Whether the debug room should be re-joined after a reconnect. */
  private debugStreaming = false;

  constructor(
    private readonly handle: DaemonHandle,
    private readonly events: DaemonClientEvents,
  ) {}

  connect(): void {
    const socket = io(`http://${this.handle.host}:${this.handle.port}`, {
      path: '/ws',
      transports: ['websocket'],
      auth: { token: this.handle.token },
    });
    this.socket = socket;

    socket.on('connect', () => {
      const isReconnect = this.hasConnected;
      this.hasConnected = true;
      // Re-join the active run's room so live items resume after a reconnect.
      let joined: Promise<void> | null = null;
      if (this.activeRunId) {
        if (isReconnect) {
          joined = this.waitForJoin(this.activeRunId);
        }
        socket.emit('join', { runId: this.activeRunId });
      }
      // Same rule as the run room, and easy to miss: a reconnect lands a NEW
      // socket that is in no rooms, so an open debug panel would go silent
      // after a daemon restart and look like "nothing is happening".
      if (this.debugStreaming) {
        socket.emit('debug_subscribe', { on: true });
      }
      this.events.onOpen?.();
      if (isReconnect) {
        void (joined ?? Promise.resolve())
          .then(() => {
            for (const listener of this.reconnectListeners) {
              listener();
            }
          })
          .catch((err: unknown) => {
            const error = err instanceof Error ? err : new Error(String(err));
            for (const listener of this.reconnectListeners) {
              listener(error);
            }
          });
      }
    });
    socket.on('disconnect', (reason: string) => {
      this.rejectAllJoins('socket disconnected before joining run');
      for (const listener of this.disconnectListeners) {
        listener();
      }
      this.events.onClose?.(reason);
    });
    // Every failed ATTEMPT, including each automatic retry. Socket.IO keeps
    // retrying forever and reports nothing else, so this is the only place the
    // renderer can learn that the daemon is unreachable or rejecting the
    // token — the difference between "still connecting" and "will never
    // connect", which the UI otherwise had no way to tell the user about.
    socket.on('connect_error', (err: Error) => {
      // The ADDRESS is included because Socket.IO's own wording for a refused
      // loopback connection is the bare "websocket error" — true, and useless
      // for the one question the user can act on: which port are we dialling,
      // and is anything listening on it. The client is the only place that
      // knows, since host and port are negotiated per launch.
      const endpoint = `${this.handle.host}:${this.handle.port}`;
      const reason = err.message || 'could not reach the daemon';
      this.events.onError?.(`${reason} (${endpoint})`);
    });
    socket.onAny((event: string, data: unknown) => {
      this.events.onMessage?.(event, data);
      if (event === 'joined') {
        this.resolveJoined(data);
      }
      if (event === 'item') {
        const item = data as ChatItem;
        for (const listener of this.itemListeners) {
          listener(item);
        }
      }
      if (event === 'agent_delta') {
        // The EPHEMERAL live-text plane (see chats/live-text.ts, the twin of
        // the daemon's RunDeltaEvent). Nothing here is persisted, so a dropped
        // event costs nothing: the next one carries the whole tail again.
        const live = parseLiveText(data);
        if (live) {
          for (const listener of this.liveTextListeners) {
            listener(live);
          }
        }
      }
      if (event === 'run_status') {
        const status = parseRunStatus(data);
        if (status) {
          for (const listener of this.runStatusListeners) {
            listener(status);
          }
        }
      }
      if (event === 'run_deleted') {
        // Carries a runId and nothing else: the run is GONE, so there is no
        // shape to parse beyond the id of what to forget.
        const runId = parseDeletedRunId(data);
        if (runId) {
          for (const listener of this.runDeletedListeners) {
            listener(runId);
          }
        }
      }
      if (event === 'usage_recorded') {
        const usage = parseUsageRecorded(data);
        if (usage) {
          for (const listener of this.usageListeners) {
            listener(usage);
          }
        }
      }
      if (event === 'debug') {
        const entry = parseDebugEntry(data);
        if (entry) {
          for (const listener of this.debugListeners) {
            listener(entry);
          }
        }
      }
      if (event === 'verdict_ack') {
        const ack = data as VerdictAck;
        for (const listener of this.verdictAckListeners) {
          listener(ack);
        }
      }
    });
  }

  /**
   * Start or stop receiving the daemon's debug log on this socket.
   *
   * Explicitly opt-in, and that is the whole design: with the `agent-stdio`
   * channel on, this stream is thousands of lines per turn, so a client that
   * is not showing them must not be sent them. Re-issued on every reconnect
   * for the same reason `join` is — rooms are per-socket and server-side, so a
   * fresh socket lands in none of them.
   */
  setDebugStream(on: boolean): void {
    this.debugStreaming = on;
    this.socket?.emit('debug_subscribe', { on });
  }

  /** Subscribe to debug entries; returns an unsubscribe function. */
  onDebugEntry(listener: (entry: DebugLogEntry) => void): () => void {
    this.debugListeners.add(listener);
    return () => {
      this.debugListeners.delete(listener);
    };
  }

  /** Subscribe to live assistant text (the non-durable growing bubble). */
  onLiveText(listener: (event: LiveTextEvent) => void): () => void {
    this.liveTextListeners.add(listener);
    return () => {
      this.liveTextListeners.delete(listener);
    };
  }

  /**
   * Subscribe to verdict acknowledgments. Only `expired` means the request
   * already settled; `invalid` remains retryable.
   */
  onVerdictAck(listener: (ack: VerdictAck) => void): () => void {
    this.verdictAckListeners.add(listener);
    return () => {
      this.verdictAckListeners.delete(listener);
    };
  }

  /**
   * Subscribe to run-status changes for EVERY run, not just the focused one —
   * this is what keeps a background chat's badge honest.
   */
  onRunStatus(listener: (event: RunStatusEvent) => void): () => void {
    this.runStatusListeners.add(listener);
    return () => {
      this.runStatusListeners.delete(listener);
    };
  }

  /**
   * Subscribe to run DELETIONS, for every run rather than the focused one.
   *
   * The sibling of {@link onRunStatus} and needed for the same reason one step
   * further: a status event can only ever describe a run that still exists, so
   * without this a client that did not perform the delete had nothing able to
   * tell it the row should go — and kept one for a run whose rows were gone.
   */
  onRunDeleted(listener: (runId: string) => void): () => void {
    this.runDeletedListeners.add(listener);
    return () => {
      this.runDeletedListeners.delete(listener);
    };
  }

  /**
   * Subscribe to ledger writes — one event per finished turn whose usage was
   * recorded, for whatever is showing what the app has spent.
   */
  onUsageRecorded(listener: (event: UsageRecordedEvent) => void): () => void {
    this.usageListeners.add(listener);
    return () => {
      this.usageListeners.delete(listener);
    };
  }

  /** Subscribe to streamed run items; returns an unsubscribe function. */
  onItem(listener: (item: ChatItem) => void): () => void {
    this.itemListeners.add(listener);
    return () => {
      this.itemListeners.delete(listener);
    };
  }

  /**
   * Subscribe to reconnects (not the first connect); returns an unsubscribe
   * function. The renderer uses this to fetch items missed while offline.
   */
  onReconnect(listener: (error?: Error) => void): () => void {
    this.reconnectListeners.add(listener);
    return () => {
      this.reconnectListeners.delete(listener);
    };
  }

  onDisconnect(listener: () => void): () => void {
    this.disconnectListeners.add(listener);
    return () => {
      this.disconnectListeners.delete(listener);
    };
  }

  /** Join a run's room to start receiving its `item` events. */
  joinRun(runId: string): Promise<void> {
    this.activeRunId = runId;
    const joined = this.waitForJoin(runId);
    if (this.socket?.connected) {
      this.socket.emit('join', { runId });
    }
    return joined;
  }

  /** Leave a run's room. */
  leaveRun(runId: string): void {
    if (this.activeRunId === runId) {
      this.activeRunId = null;
    }
    this.rejectJoins(runId, 'run room was left before joining');
    this.socket?.emit('leave', { runId });
  }

  /**
   * Answer an `ask`-node's approval card. The durable acknowledgment is the
   * `approval_verdict` item the daemon persists-then-emits back to the room;
   * the immediate `verdict_ack` reply only reports routing (`expired` means
   * already settled; `invalid` remains retryable).
   * `answer` carries the user's picked option / typed text for a question
   * card (AskUserQuestion) — omitted for plain tool approvals.
   *
   * TWIN PARSER: the daemon parses this `verdict` envelope in
   * `extractVerdict`
   * (apps/daemon/src/v1/notifications/gateways/notifications.gateway.ts) —
   * `{runId, requestId, allow, answer?}`, `answer` honored only as a
   * non-empty string ≤ MAX_ANSWER_LENGTH. A shape change here must be
   * mirrored there, and vice versa.
   */
  sendVerdict(
    runId: string,
    requestId: string,
    allow: boolean,
    answer?: string,
  ): void {
    this.socket?.emit('verdict', {
      runId,
      requestId,
      allow,
      ...(answer !== undefined ? { answer } : {}),
    });
  }

  close(): void {
    this.rejectAllJoins('socket closed before joining run');
    this.socket?.close();
    this.socket = null;
  }

  private waitForJoin(runId: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const waiter: JoinWaiter = {
        resolve,
        reject,
        timer: setTimeout(() => {
          this.removeJoinWaiter(runId, waiter);
          reject(new Error(`timed out joining run ${runId}`));
        }, JOIN_TIMEOUT_MS),
      };
      const waiters = this.joinWaiters.get(runId) ?? new Set<JoinWaiter>();
      waiters.add(waiter);
      this.joinWaiters.set(runId, waiters);
    });
  }

  private resolveJoined(data: unknown): void {
    const runId =
      typeof data === 'object' &&
      data !== null &&
      typeof (data as { runId?: unknown }).runId === 'string'
        ? (data as { runId: string }).runId
        : null;
    if (!runId) {
      return;
    }
    const waiters = this.joinWaiters.get(runId);
    if (!waiters) {
      return;
    }
    this.joinWaiters.delete(runId);
    for (const waiter of waiters) {
      clearTimeout(waiter.timer);
      waiter.resolve();
    }
  }

  private rejectJoins(runId: string, message: string): void {
    const waiters = this.joinWaiters.get(runId);
    if (!waiters) {
      return;
    }
    this.joinWaiters.delete(runId);
    for (const waiter of waiters) {
      clearTimeout(waiter.timer);
      waiter.reject(new Error(message));
    }
  }

  private rejectAllJoins(message: string): void {
    for (const runId of [...this.joinWaiters.keys()]) {
      this.rejectJoins(runId, message);
    }
  }

  private removeJoinWaiter(runId: string, waiter: JoinWaiter): void {
    const waiters = this.joinWaiters.get(runId);
    if (!waiters) {
      return;
    }
    waiters.delete(waiter);
    if (waiters.size === 0) {
      this.joinWaiters.delete(runId);
    }
  }
}
