import type { HandoffTargetDto } from './autogenerated';

/**
 * The whole handoff contract, once: ask the daemon for an invocation, and either
 * open it in the user's terminal or say why there isn't one.
 *
 * ONE caller now — `chats/Chats.tsx`'s `openThreadTerminal`, handing a
 * thread's own conversation to the user's terminal. The other callers this
 * module once shared — an MCP server's sign-in and a CLI's own account
 * sign-in, from both the chat surface and Settings — moved to the in-app
 * `use-cli-login.ts` flow, which never opens a terminal at all (see
 * `apps/ui/CLAUDE.md`).
 *
 * A refusal is the ANSWER, not a failure — cursor-agent genuinely cannot reopen
 * one of its conversations — so the daemon's own sentence is what the user
 * reads, and `fallback` covers only the case where it sent none.
 */
export async function openResolvedTarget(
  resolve: () => Promise<HandoffTargetDto>,
  fallback: string,
  setError: (message: string | null) => void,
): Promise<void> {
  try {
    setError(null);
    const target = await resolve();
    if (target.kind !== 'command' || !target.command || !target.cwd) {
      setError(target.unavailableReason ?? fallback);
      return;
    }
    await window.geniro.openInTerminal({
      command: target.command,
      args: target.args,
      cwd: target.cwd,
      // Carried, never composed here: a resume that dropped it would open the
      // DEFAULT profile, where this session id does not exist, and the CLI
      // would show an unrelated conversation instead of an error.
      env: target.env,
    });
  } catch (err) {
    setError(err instanceof Error ? err.message : String(err));
  }
}
