import {
  ClipboardCheck,
  FolderOpen,
  Pause,
  Play,
  SquareCode,
  Trash2,
  X,
} from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';

import type { DebugChannel, DiagnosticsReportDto } from '../autogenerated';
import { ErrorBanner } from '../components/error-banner';
import { PanelResizeHandle, usePanelWidth } from '../components/panel-resize';
import { Button } from '../components/ui/button';
import { Chip } from '../components/ui/chip';
import { Input } from '../components/ui/input';
import { cn } from '../components/ui/utils';
import type { DaemonApis } from '../daemon-api';
import type { DaemonClient, DebugLogEntry } from '../daemon-client';
import { followTail } from '../scroll-to-bottom';
import { useDebugLog } from './use-debug-log';

/**
 * Every channel the daemon records, with what each one is FOR — the label
 * alone ("agent-stdio") does not tell a reader whether turning it on is a good
 * idea, and one of these is a decision worth making deliberately.
 */
const CHANNELS: { value: DebugChannel; label: string; hint: string }[] = [
  {
    value: 'daemon',
    label: 'Daemon',
    hint: 'The daemon’s own log — turns, adapters, errors, startup',
  },
  {
    value: 'transcript',
    label: 'Transcript',
    hint: 'Every item and status the daemon streams, with its seq',
  },
  {
    value: 'agent-stdio',
    label: 'Agent I/O',
    hint: 'RAW conversation with the CLI — large, and it contains your code',
  },
  { value: 'ui', label: 'UI', hint: 'Errors and events from this window' },
];

/** How each level reads. Tokens only — no literal colours. */
const LEVEL_CLASS: Record<string, string> = {
  error: 'text-destructive',
  warn: 'text-warning',
  info: 'text-foreground',
  debug: 'text-muted-foreground',
  trace: 'text-muted-foreground',
};

/**
 * The debug drawer: a devtools-style panel across the bottom of the app.
 *
 * Placed here rather than as a fourth nav view because it is a thing you
 * consult WHILE using the app — the question is always "what happened when I
 * pressed that", and a full-screen view that replaces the thing you pressed
 * cannot answer it. Its trigger lives in the nav rail's footer beside the
 * connection dot, which is where the eye already goes when something is wrong.
 *
 * It is the live view; the FILE is the record. The panel says where that file
 * is, and can reveal it — because the log that matters most is the one from
 * the session that already crashed.
 */
export function DebugPanel({
  apis,
  client,
  onClose,
}: {
  apis: DaemonApis;
  client: DaemonClient;
  onClose: () => void;
}): React.JSX.Element {
  const {
    entries,
    channels,
    filePath,
    dropped,
    paused,
    error,
    setChannels,
    setPaused,
    clear,
  } = useDebugLog(apis, client, true);
  const [filter, setFilter] = useState('');
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState<string | null>(null);
  const [dismissedError, setDismissedError] = useState<string | null>(null);
  const {
    width: height,
    minWidth,
    maxWidth,
    startResize,
    resizeTo,
  } = usePanelWidth({
    storageKey: 'debug.panelHeight',
    defaultWidth: 260,
    minWidth: 120,
    maxWidth: 720,
    handleEdge: 'top',
  });

  const shown = useMemo(() => {
    const needle = filter.trim().toLowerCase();
    if (!needle) {
      return entries;
    }
    return entries.filter(
      (entry) =>
        entry.message.toLowerCase().includes(needle) ||
        entry.channel.includes(needle) ||
        Object.values(entry.context ?? {}).some((value) =>
          value.toLowerCase().includes(needle),
        ),
    );
  }, [entries, filter]);

  // Follow the tail, but only while not paused — pausing is what someone does
  // to READ something, and yanking the viewport back to the bottom under them
  // is the exact opposite of what they asked for.
  const tailRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    // The sentinel's PARENT is the scroll box, and it is what gets moved —
    // never `scrollIntoView`, which scrolls every scrollable ancestor up to and
    // including the document. See `scroll-to-bottom.ts` for the whole story.
    const scroller = tailRef.current?.parentElement;
    if (!paused && scroller) {
      followTail(scroller);
    }
  }, [shown.length, paused]);

  const copyReport = (): void => {
    void apis.diagnostics
      .buildDiagnosticsReport()
      .then((report) => navigator.clipboard.writeText(formatReport(report)))
      .then(() => {
        setCopied(true);
        setCopyError(null);
        setTimeout(() => setCopied(false), 2_000);
      })
      .catch((err: unknown) => setCopyError(String(err)));
  };

  const banner = copyError ?? (error === dismissedError ? null : error);

  return (
    <aside
      className="relative flex shrink-0 flex-col border-t border-border bg-sidebar"
      style={{ height }}
      aria-label="Debug log">
      <PanelResizeHandle
        edge="top"
        label="Resize debug panel"
        onMouseDown={startResize}
        value={height}
        min={minWidth}
        max={maxWidth}
        onResize={resizeTo}
      />
      <div className="flex flex-wrap items-center gap-1.5 px-3 pt-2 pb-1.5">
        <span className="text-xs font-medium tracking-wide text-muted-foreground uppercase">
          Debug
        </span>
        {CHANNELS.map(({ value, label, hint }) => {
          const on = channels.includes(value);
          return (
            <Chip
              key={value}
              asChild
              interactive
              tone={on ? 'active' : 'muted'}
              title={hint}>
              <button
                type="button"
                aria-pressed={on}
                className={cn('h-6 px-1.5', on && 'bg-accent')}
                onClick={() =>
                  setChannels(
                    on
                      ? channels.filter((channel) => channel !== value)
                      : [...channels, value],
                  )
                }>
                {label}
              </button>
            </Chip>
          );
        })}
        <Input
          value={filter}
          onChange={(event) => setFilter(event.target.value)}
          placeholder="Filter…"
          aria-label="Filter debug entries"
          className="h-6 w-40 px-2 text-xs"
        />
        <span className="ml-auto flex shrink-0 items-center gap-0.5">
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-6"
            aria-label={
              paused ? 'Resume the debug stream' : 'Pause the debug stream'
            }
            title={paused ? 'Resume' : 'Pause'}
            onClick={() => setPaused(!paused)}>
            {paused ? (
              <Play className="size-3.5 shrink-0" />
            ) : (
              <Pause className="size-3.5 shrink-0" />
            )}
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-6"
            aria-label="Clear the debug view"
            // Says plainly that this is a VIEW operation: the file is the
            // record, and a button that read "Clear" alone would look like it
            // destroys evidence.
            title="Clear this view — the log file is untouched"
            onClick={clear}>
            <Trash2 className="size-3.5 shrink-0" />
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-6 gap-1 px-2 text-[11px]"
            title="Copy versions, paths, CLI status and the recent log for a bug report"
            onClick={copyReport}>
            <ClipboardCheck className="size-3 shrink-0" />
            {copied ? 'Copied' : 'Copy diagnostics'}
          </Button>
          {filePath ? (
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="size-6"
              aria-label="Reveal the log file"
              title={filePath}
              onClick={() => void window.geniro.revealPath(filePath)}>
              <FolderOpen className="size-3.5 shrink-0" />
            </Button>
          ) : null}
          {/* Sits HERE, not in a menu: the two are consulted for the same
              symptom and the answer is often in the other one. What this panel
              cannot show — the DOM, a stylesheet, the actual request that
              404'd — is one click away, and the reverse is signposted in the
              title so nobody hunts for daemon logs in a Console that will
              never have them. */}
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-6"
            aria-label="Open Chrome DevTools"
            title="Chrome DevTools (⌥⌘I) — DOM, Console, and this window’s requests. The daemon and the agent CLIs are separate processes; they only appear here."
            onClick={() => void window.geniro.toggleDevTools()}>
            <SquareCode className="size-3.5 shrink-0" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-6"
            aria-label="Close the debug panel"
            title="Close"
            onClick={onClose}>
            <X className="size-3.5 shrink-0" />
          </Button>
        </span>
      </div>
      {banner ? (
        <ErrorBanner
          // MARGIN, not padding: the strip owns its own inset now, and a
          // `px-*` here would merge that away and put the text on the fill's
          // edge.
          className="mx-3 mb-1"
          message={banner}
          onDismiss={() => {
            setCopyError(null);
            setDismissedError(error);
          }}
        />
      ) : null}
      {dropped > 0 ? (
        // Said out loud. A debug log that quietly loses the lines you were
        // looking for is worse than one that admits it did.
        <p className="px-3 pb-1 text-[11px] text-warning">
          {dropped} earlier {dropped === 1 ? 'entry' : 'entries'} scrolled out
          of the daemon’s buffer — they are still in the log file.
        </p>
      ) : null}
      <div className="min-h-0 flex-1 overflow-x-hidden overflow-y-auto px-3 pb-2">
        {shown.length === 0 ? (
          <p className="py-2 text-xs text-muted-foreground">
            {entries.length === 0
              ? 'Nothing recorded yet.'
              : 'No entries match this filter.'}
          </p>
        ) : (
          <ul className="m-0 flex list-none flex-col p-0">
            {shown.map((entry) => (
              <DebugRow key={entry.seq} entry={entry} />
            ))}
          </ul>
        )}
        <div ref={tailRef} />
      </div>
    </aside>
  );
}

/**
 * One line. `break-all` on the message for the same reason the transcript
 * needs it: these carry absolute paths and serialized JSON with no spaces, and
 * an unbroken one would push the panel sideways.
 */
function DebugRow({ entry }: { entry: DebugLogEntry }): React.JSX.Element {
  const context = Object.entries(entry.context ?? {});
  return (
    <li className="flex gap-2 rounded px-1 py-0.5 font-mono text-[11px] leading-relaxed hover:bg-accent/40">
      <span className="shrink-0 text-muted-foreground">
        {entry.at.slice(11, 23)}
      </span>
      <span className="w-16 shrink-0 truncate text-muted-foreground">
        {entry.channel}
      </span>
      <span
        className={cn(
          'min-w-0 flex-1 break-all whitespace-pre-wrap',
          LEVEL_CLASS[entry.level] ?? 'text-foreground',
        )}>
        {entry.message}
        {context.length > 0 ? (
          <span className="text-muted-foreground">
            {' '}
            {context.map(([key, value]) => `${key}=${value}`).join(' ')}
          </span>
        ) : null}
      </span>
    </li>
  );
}

/**
 * The report as pasteable text rather than raw JSON.
 *
 * It goes into a GitHub issue or a chat message, and a 200-entry JSON blob is
 * something a reader scrolls past. The head is the machine, the tail is the
 * evidence, and both are readable without a formatter.
 */
export function formatReport(report: DiagnosticsReportDto): string {
  const pairs = (value: object): string[] =>
    Object.entries(value).map(([key, item]) => `${key}: ${String(item)}`);
  const lines = [
    `# geniro diagnostics — ${report.generatedAt}`,
    '',
    '## daemon',
    ...pairs(report.daemon),
    '',
    '## agents',
    ...report.agents.map(
      (agent) =>
        `${agent.kind}: ${agent.version ?? 'not detected'} (${agent.binary})` +
        (agent.unavailableReason ? ` — ${agent.unavailableReason}` : ''),
    ),
    '',
    '## runs',
    ...pairs(report.runs),
    '',
    `## last ${report.recentEntries.length} log entries`,
    ...report.recentEntries.map(
      (entry) =>
        `${entry.at} ${entry.channel} ${entry.level} ${entry.message}` +
        (entry.context
          ? ` ${Object.entries(entry.context)
              .map(([key, value]) => `${key}=${String(value)}`)
              .join(' ')}`
          : ''),
    ),
  ];
  return lines.join('\n');
}
