/**
 * Contracts shared INSIDE the Electron UI app (main ⇄ preload ⇄ renderer):
 * the IPC surface, persisted settings, CLI detection, Keychain identifiers and
 * the daemon connection handle. Nothing here describes the daemon's HTTP API.
 *
 * The daemon's wire shapes are NOT mirrored here. They are generated from its
 * own OpenAPI document into `apps/ui/src/renderer/autogenerated` by
 * `pnpm generate:api`, and the renderer imports them from there — so a route or
 * schema change on the daemon surfaces as a type error after regeneration
 * instead of silently drifting from a hand-written copy.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Daemon connection (read from the pidfile by main, passed to the renderer)
// ─────────────────────────────────────────────────────────────────────────────

/** Connection coordinates the renderer needs to open an authed WS/HTTP call. */
export interface DaemonHandle {
  /** Loopback host the daemon reported binding to (from the pidfile). */
  host: string;
  /** Loopback port the daemon reported binding to. */
  port: number;
  /** Per-launch bearer token; required on every daemon request. */
  token: string;
  /** Daemon version (semver). */
  version: string;
}

/** Live status the renderer polls/subscribes to for the connection banner. */
export interface DaemonStatus {
  connected: boolean;
  handle: DaemonHandle | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Settings (non-secret app config — persisted as JSON in userData)
// ─────────────────────────────────────────────────────────────────────────────

/** Persisted, non-secret application settings. Secrets never live here. */
export interface Settings {
  /** First-run onboarding finished (gates the renderer's initial route). */
  onboardingComplete: boolean;
  /** Absolute path to the user's working project folder (agent cwd). */
  projectFolder: string | null;
  /** Recently used project folders, most recent first (composer suggestions). */
  recentFolders: string[];
  /** The chat composer's last target — a CLI kind or `wf:<slug>`. */
  lastChatTarget: string | null;
  /**
   * The new-run composer's last approval mode, so it opens on the choice the
   * user actually works in rather than resetting to `ask` every time. An
   * opaque string here on purpose: the mode vocabulary is the DAEMON's (its
   * `ChatApprovalMode`), and this file holds no daemon shapes — the renderer
   * validates the stored value against the generated enum before applying it.
   */
  lastApprovalMode: string | null;
  /**
   * The new-run composer's last model per CLI. Keyed by CLI because the two
   * have disjoint model vocabularies — one shared slot would hand cursor a
   * claude alias the moment the user switched agents. A missing entry means
   * that CLI's own default (no `--model` flag).
   */
  lastModels: Partial<Record<CliKind, string>>;
  /**
   * The new-run composer's last reasoning-effort level per CLI. Keyed per CLI
   * for the same reason as `lastModels`, and opaque here for the same reason
   * as `lastApprovalMode`: the vocabulary belongs to the CLI (the daemon asks
   * its adapter), so this file cannot name the levels. A missing entry means
   * that CLI's own default — which is also every CLI that has no such control.
   */
  lastEfforts: Partial<Record<CliKind, string>>;
  /** Explicit overrides for CLI binary locations (else resolved on PATH). */
  cliPaths: Partial<Record<CliKind, string>>;
  /** Whether to check for app updates on launch (wired in M4). */
  checkForUpdates: boolean;
  /**
   * Spawn the daemon with a Node inspector on loopback, so real Chrome
   * DevTools can attach to it from `chrome://inspect`.
   *
   * The daemon is a separate Node process, so the renderer's DevTools can see
   * nothing of it. This is what closes that gap, and it is the genuine article
   * rather than a reimplementation: Sources with breakpoints over the daemon's
   * own TypeScript, the CPU profiler, heap snapshots.
   *
   * A setting rather than always-on. An open inspector port is arbitrary code
   * execution inside the daemon for anything that can reach loopback — fine on
   * a single-user machine, which is this app's whole premise, but not
   * something to hand every packaged install without the user asking. Off by
   * default; the choice persists, so it is one click once. Applying it needs a
   * daemon respawn (an inspector is a process-launch flag), which the settings
   * write triggers.
   */
  daemonInspect: boolean;
}

/** Default settings written on first launch when no settings file exists. */
export const DEFAULT_SETTINGS: Settings = {
  onboardingComplete: false,
  projectFolder: null,
  recentFolders: [],
  lastChatTarget: null,
  lastApprovalMode: null,
  lastModels: {},
  lastEfforts: {},
  cliPaths: {},
  checkForUpdates: true,
  daemonInspect: false,
};

/**
 * Loopback port the daemon's inspector listens on when `daemonInspect` is on.
 *
 * 9229 deliberately — it is node's own default, and the one address
 * `chrome://inspect` discovers with no configuration. A tidier private port
 * would mean every user's first step is "add 127.0.0.1:<x> under Configure",
 * which is the step people give up at.
 *
 * The Electron MAIN process is never launched with `--inspect` here, so
 * nothing else in this app claims it. If something outside does, node reports
 * the address as in use and the daemon still starts — the inspector is the
 * only thing lost.
 */
export const DAEMON_INSPECT_PORT = 9229;

// ─────────────────────────────────────────────────────────────────────────────
// App updates (GitHub Releases version check — the ad-hoc build reports a newer
// release but does not self-install; the user updates via brew / the script)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Outcome of an app-update check. `dev` = unpackaged launch, checks disabled;
 * `available` carries the update command in `message` (Geniro notifies but does
 * not self-update — see main/updater.ts).
 */
export interface UpdateCheckResult {
  status: 'dev' | 'up-to-date' | 'available' | 'error';
  version: string | null;
  message: string | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI detection
// ─────────────────────────────────────────────────────────────────────────────

/** CLI agents geniro can drive in v1 (all headless). */
export type CliKind = 'claude' | 'cursor-agent';

/** Every CLI kind, in onboarding display order. */
export const CLI_KINDS: readonly CliKind[] = ['claude', 'cursor-agent'];

/** Result of probing the host for a single CLI agent. */
export interface CliDetection {
  kind: CliKind;
  /** True when the binary was located and reported a version. */
  found: boolean;
  /** Absolute path to the resolved binary, when found. */
  path: string | null;
  /** Version string the binary reported, when found. */
  version: string | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Git (the composer's branch chip — read from the folder a run will use)
// ─────────────────────────────────────────────────────────────────────────────

/** Git state of a working directory; every field is safe on a non-repo. */
export interface GitInfo {
  /** False for a plain folder — the branch chip renders only when true. */
  isRepo: boolean;
  /** Current branch, or null on a detached HEAD (no branch to name). */
  branch: string | null;
  /** Local branches, for the picker. */
  branches: string[];
  /** Working tree has uncommitted changes — blocks a branch switch. */
  dirty: boolean;
}

/** Outcome of a guarded branch switch. `branch` is the branch now checked out. */
export interface BranchSwitchResult {
  ok: boolean;
  branch: string | null;
  /** Why the switch was refused or failed; null on success. */
  error: string | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Secrets (macOS Keychain — never written to disk or SQLite)
// ─────────────────────────────────────────────────────────────────────────────

/** Keychain service name under which all geniro secrets are stored. */
export const KEYCHAIN_SERVICE = 'io.geniro.app';

/** Logical secret identifiers (Keychain "account" within the service). */
export type SecretName = 'cursor.apiKey';

// ─────────────────────────────────────────────────────────────────────────────
// IPC contract (window.geniro — exposed by the preload via contextBridge)
// ─────────────────────────────────────────────────────────────────────────────

/** Input captured by the onboarding flow and committed in one IPC call. */
export interface OnboardingInput {
  /** Per-agent binary path overrides (absolute paths); omitted keys auto-detect. */
  cliPaths?: Partial<Record<CliKind, string>>;
  /** Optional Cursor API key; stored in the Keychain, never echoed back. */
  cursorApiKey?: string;
}

/**
 * The typed API surface the preload exposes on `window.geniro`. The renderer
 * never touches Node or Electron directly — every privileged action is one of
 * these channels.
 */
export interface GeniroApi {
  /** Current onboarding + daemon status. */
  getStatus(): Promise<{ onboardingComplete: boolean; daemon: DaemonStatus }>;
  /** Daemon connection handle (host + port + token) for opening an authed WS. */
  getDaemonHandle(): Promise<DaemonHandle | null>;
  /** Subscribe to daemon restarts that rotate the loopback handle/token. */
  onDaemonRestarted(listener: (handle: DaemonHandle) => void): () => void;
  /** Open the native folder picker; returns the chosen absolute path or null. */
  pickProjectFolder(): Promise<string | null>;
  /** Open the native file picker for an agent binary; returns the path or null. */
  pickAgentBinary(): Promise<string | null>;
  /** Read the persisted settings. */
  getSettings(): Promise<Settings>;
  /** Merge a partial patch into settings; returns the updated settings. */
  updateSettings(patch: Partial<Settings>): Promise<Settings>;
  /** Probe the host for each supported CLI agent. */
  detectClis(): Promise<CliDetection[]>;
  /** Store a secret in the Keychain. */
  saveSecret(name: SecretName, value: string): Promise<void>;
  /** Whether a secret exists in the Keychain (value is never returned). */
  hasSecret(name: SecretName): Promise<boolean>;
  /** Remove a secret from the Keychain. */
  deleteSecret(name: SecretName): Promise<void>;
  /** Persist onboarding input and mark onboarding complete. */
  completeOnboarding(input: OnboardingInput): Promise<Settings>;
  /** Open a native picker for a workflow YAML to import; path or null. */
  pickWorkflowImport(): Promise<string | null>;
  /** Open a native save dialog for a workflow export; target path or null. */
  pickWorkflowExport(defaultName: string): Promise<string | null>;
  /** Check the GitHub Releases feed for an app update (no-op in dev). */
  checkForUpdates(): Promise<UpdateCheckResult>;
  /** Read a folder's git state (repo? branch? branches? dirty?). */
  getGitInfo(dir: string): Promise<GitInfo>;
  /**
   * Open the user's own terminal on a command — the handoff out of geniro.
   * Takes the command as DATA (never a shell string) so nothing here has to
   * quote it, and so the renderer cannot smuggle a second command in.
   */
  openInTerminal(input: {
    command: string;
    args: string[];
    cwd: string;
  }): Promise<void>;
  /** Switch the folder to a branch — refused when the tree is dirty. */
  switchBranch(dir: string, branch: string): Promise<BranchSwitchResult>;
  /**
   * Show one of the daemon's own files in Finder — the debug log.
   *
   * Deliberately narrow: it REVEALS (selects in a file manager) rather than
   * opens, so nothing here can be talked into executing what it is handed, and
   * main refuses any path outside the daemon's log directory. The renderer is
   * sandboxed and a path it supplies is not trusted just because the daemon
   * gave it to us.
   */
  revealPath(
    path: string,
  ): Promise<{ revealed: boolean; reason: string | null }>;
  /**
   * Toggle Chrome DevTools on this window — the same Elements / Console /
   * Network panels a browser gives you, because the renderer IS a browser.
   *
   * It answers a different question from the debug panel and neither replaces
   * the other. DevTools sees ONE process, this one: the DOM, renderer
   * exceptions, and every HTTP call and `/ws` frame the renderer sends. It
   * cannot see the daemon or a spawned CLI at all — those are separate
   * processes with no page and no renderer network stack, which is why the
   * daemon log, the transcript stream and `agent-stdio` exist in the debug
   * panel instead, and why reaching the daemon's own internals needs
   * `daemonInspect` rather than this.
   *
   * Electron's default menu already binds this to ⌥⌘I; the button exists so it
   * is findable from the place a user already looks when something is wrong.
   */
  toggleDevTools(): Promise<void>;
}

/** IPC channel names — single source of truth for main ⇄ preload wiring. */
export const IPC = {
  getStatus: 'geniro:getStatus',
  getDaemonHandle: 'geniro:getDaemonHandle',
  onDaemonRestarted: 'geniro:onDaemonRestarted',
  pickProjectFolder: 'geniro:pickProjectFolder',
  pickAgentBinary: 'geniro:pickAgentBinary',
  getSettings: 'geniro:getSettings',
  updateSettings: 'geniro:updateSettings',
  detectClis: 'geniro:detectClis',
  saveSecret: 'geniro:saveSecret',
  hasSecret: 'geniro:hasSecret',
  deleteSecret: 'geniro:deleteSecret',
  completeOnboarding: 'geniro:completeOnboarding',
  pickWorkflowImport: 'geniro:pickWorkflowImport',
  pickWorkflowExport: 'geniro:pickWorkflowExport',
  checkForUpdates: 'geniro:checkForUpdates',
  getGitInfo: 'geniro:getGitInfo',
  openInTerminal: 'geniro:openInTerminal',
  switchBranch: 'geniro:switchBranch',
  revealPath: 'geniro:revealPath',
  toggleDevTools: 'geniro:toggleDevTools',
} as const satisfies Record<keyof GeniroApi, string>;
