import type { UsageGroup } from '../autogenerated';
import { formatUsd } from '../chats/agent-activity';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '../components/ui/card';
import { isCosted, toRankedRows } from './chart-data';
import { categoryToken } from './charts/chart-theme';
import { formatTurns } from './stats-format';

/**
 * A breakdown as a ranked list of bars — who spent what, dearest first.
 *
 * Bars rather than the ring this replaced. A ring compares angles, which the eye
 * does badly past three slices and cannot do at all for the long tail; and its
 * legend had to sit beside it, so a model name like
 * `claude-opus-5[thinking=true,context=300k,…]` was truncated to a few
 * characters. A bar row gives the label the full width of the card and ranks by
 * length, which is the comparison actually being made.
 *
 * Every group is drawn — there is no "N more" fold, because the fold was what
 * forced the ring's slice budget in the first place, and a list simply gets
 * longer.
 */
export function BreakdownCard({
  title,
  groups,
  labelOf,
  emptyLabel,
}: {
  title: string;
  groups: readonly UsageGroup[];
  /** How a null key reads for THIS dimension — "unknown model", "no folder". */
  labelOf: (key: string | null) => string;
  emptyLabel: string;
}): React.JSX.Element {
  const costed = isCosted(groups);
  const rows = toRankedRows(
    groups,
    labelOf,
    (row) =>
      // Spend where the whole card is sized by it; the turn count otherwise, so a
      // group whose CLI reported no cost still states what it DID.
      costed && row.costUsd !== null
        ? formatUsd(row.costUsd)
        : formatTurns(row.turns),
    costed,
  );

  return (
    <Card className="min-w-0 flex-1">
      <CardHeader>
        <CardTitle className="text-sm font-medium">{title}</CardTitle>
      </CardHeader>
      <CardContent className="pb-5">
        {rows.length === 0 ? (
          <p className="text-sm text-muted-foreground">{emptyLabel}</p>
        ) : (
          <ul className="flex flex-col gap-3">
            {rows.map((row, index) => (
              <li key={row.id} className="flex flex-col gap-1.5">
                <div className="flex min-w-0 items-baseline gap-2 text-sm">
                  <span className="min-w-0 flex-1 truncate" title={row.title}>
                    {row.label}
                  </span>
                  <span className="shrink-0 tabular-nums text-muted-foreground">
                    {row.display}
                  </span>
                </div>
                <div className="h-1.5 w-full overflow-hidden rounded-full bg-muted">
                  <div
                    className="h-full rounded-full"
                    style={{
                      // A floor, so a real but tiny share is still a visible
                      // mark rather than rounding away to nothing — the same
                      // reason the old ring kept a minimum wedge.
                      width: `${Math.max(row.fraction * 100, 2)}%`,
                      backgroundColor: categoryToken(index),
                    }}
                  />
                </div>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}
