import { Plus, Zap } from 'lucide-react';

import type { TaskDto } from '../autogenerated';
import { Chip } from '../components/ui/chip';
import { cn } from '../components/ui/utils';
import { TaskCard } from './task-card';
import { taskStatusMeta } from './task-status';

export function BoardColumn({
  status,
  tasks,
  selectedTaskId,
  draggingTaskId,
  isDropTarget,
  onOpenTask,
  onDragStartTask,
  onDragEndTask,
  onDragOver,
  onDragLeave,
  onDrop,
  onTaskKeyDown,
  onAddTask,
  autopilot,
}: {
  status: string;
  tasks: TaskDto[];
  selectedTaskId: string | null;
  draggingTaskId: string | null;
  isDropTarget: boolean;
  onOpenTask: (taskId: string) => void;
  onDragStartTask: (taskId: string) => void;
  onDragEndTask: () => void;
  onDragOver: (event: React.DragEvent<HTMLElement>) => void;
  onDragLeave: () => void;
  onDrop: (event: React.DragEvent<HTMLElement>) => void;
  onTaskKeyDown?: (
    event: React.KeyboardEvent<HTMLButtonElement>,
    taskId: string,
  ) => void;
  onAddTask: (status: string) => void;
  /**
   * Present only on the column the project's autopilot picks work up from.
   *
   * The banner and the Stop belong to THAT column and to no other, because
   * that is the only place on the board where "work leaves here on its own" is
   * a fact about what the user is looking at.
   */
  autopilot?: {
    breakerOpen: boolean;
    /** From the daemon's queue, not the columns — null while unread. */
    running: number | null;
    waiting: number | null;
    onStop: () => void;
  };
}): React.JSX.Element {
  const meta = taskStatusMeta(status);
  return (
    <section
      role="group"
      aria-label={`${meta.label}, ${tasks.length} task${tasks.length === 1 ? '' : 's'}`}
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
      className={cn(
        // The column is a SURFACE the cards sit on, which is what was missing:
        // without it the cards floated on the page and the board read as one
        // list with gaps rather than as columns.
        //
        // `muted/40` and not `muted` outright, because the flat token inverts
        // between themes — it is darker than the page in light and LIGHTER than
        // `card` in dark, which would sink every card into its own column. The
        // blend keeps one order in both: page, then column, then card on top.
        // Grows to share the width when the columns FIT, and falls back to
        // scrolling when they do not. A fixed `w-72` put the fifth column off
        // the right edge behind a horizontal scroll on a window wide enough
        // to hold all of them with room to spare.
        'flex min-w-64 flex-1 basis-72 flex-col gap-2 rounded-xl bg-muted/40 p-2',
        // The EDGE carries the definition, not the fill. `muted` cannot simply
        // be deepened: in dark it converges on `card` around 50%, and past that
        // the cards stop reading as raised out of their own column. A ring is
        // legible at any tint and behaves the same in both themes.
        'ring-1 transition-[background-color,box-shadow]',
        isDropTarget ? 'bg-accent/60 ring-primary' : 'ring-border',
      )}>
      {/* Quiet chrome, not a card: the columns are the page's structure, so a
        filled badge per header read as six competing buttons. The status glyph
        carries the only colour here. */}
      <header className="flex items-center gap-2 px-1">
        <meta.icon
          className={cn('size-3.5 shrink-0', meta.className)}
          aria-hidden
        />
        <span className="text-sm font-medium">{meta.label}</span>
        <span className="text-xs tabular-nums text-muted-foreground">
          {tasks.length}
        </span>
        <button
          type="button"
          // Visible rather than revealed on hover: a pointer-only affordance is
          // undiscoverable by keyboard and invisible in a screenshot, and this
          // app already prefers a quiet always-there control to a hidden one.
          aria-label={`Add a task to ${meta.label}`}
          title={`Add a task to ${meta.label}`}
          onClick={() => {
            onAddTask(status);
          }}
          className="ml-auto rounded p-1 text-muted-foreground hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50">
          <Plus className="size-3.5" aria-hidden />
        </button>
      </header>
      {autopilot ? <AutopilotBanner {...autopilot} /> : null}
      <div className="flex min-h-24 flex-1 flex-col gap-2 overflow-y-auto">
        {tasks.map((task) => (
          <TaskCardRow
            key={task.id}
            task={task}
            selected={task.id === selectedTaskId}
            dragging={task.id === draggingTaskId}
            onOpen={onOpenTask}
            onDragStart={onDragStartTask}
            onDragEnd={onDragEndTask}
            onKeyDown={onTaskKeyDown}
          />
        ))}
        {/* Nothing at rest. An empty column already LOOKS empty, and on a
            fresh board "No tasks" was written four times across a screen whose
            own emptiness said it once. The drop hint stays: that one is a
            state the column is in, not a restatement of what it holds. */}
        {tasks.length === 0 && isDropTarget ? (
          <p className="px-1 py-3 text-xs text-muted-foreground">Drop here</p>
        ) : null}
      </div>
    </section>
  );
}

/**
 * That the autopilot reads this column, and the way to stop it.
 *
 * Deliberately thin. The SETTING lives on the board header, where the switch,
 * the intake column and the cap are; what belongs here is only the fact that
 * this particular column is the one work leaves from, and the one press worth
 * having within reach of it.
 *
 * Stop is always visible and never behind a confirm: it is what a user reaches
 * for when something is going wrong, and a dialog in the way is the wrong
 * thing to meet at that moment. It is also cheap to undo — the header switch
 * arms the project again — which is what makes no-confirm right here and wrong
 * for the project delete elsewhere.
 *
 * It disarms INTAKE and deliberately does not touch a task already running:
 * stopping a working agent is a different act with a different cost and has
 * its own control on the run. The title says so, because a Stop that silently
 * left an agent working would be read as broken.
 */
function AutopilotBanner({
  breakerOpen,
  running,
  waiting,
  onStop,
}: {
  breakerOpen: boolean;
  running: number | null;
  waiting: number | null;
  onStop: () => void;
}): React.JSX.Element {
  return (
    <div
      data-slot="autopilot-banner"
      className={cn(
        // NO `text-xs` on the wrapper. A type-setting wrapper does not reach
        // a native `<button>` inside it — `global.css` gives every bare button
        // an explicit size as a direct rule, which beats an inherited one — so
        // the Stop chip would render larger than the sentence beside it. Each
        // child states its own size instead, which `Chip` already does.
        'flex items-center gap-1.5 rounded-lg px-2 py-1',
        // Ambient state, from tokens already in use — never a new colour.
        // A banner competing with the cards would read as an alert on every
        // board that merely has autopilot switched on.
        breakerOpen
          ? 'bg-warning/10 text-warning'
          : 'bg-accent/50 text-muted-foreground',
      )}>
      <Zap className="size-3.5 shrink-0" aria-hidden />
      <span className="min-w-0 flex-1 text-xs">
        {/* The column is NOT named again: this sits directly under a header
            that already says it. */}
        {breakerOpen
          ? 'Autopilot is stopped.'
          : (queueLine(running, waiting) ?? 'Autopilot starts tasks here.')}
      </span>
      {breakerOpen ? null : (
        <Chip asChild interactive>
          <button
            type="button"
            aria-label="Stop the autopilot"
            title="Stops picking up new work. A task already running is left alone."
            onClick={onStop}
            // `h-6 px-1.5` over the chip's own `h-8`: this sits inside a band
            // one line tall, and a chip at its default height makes the band
            // taller than the cards under it.
            className="h-6 shrink-0 px-1.5">
            Stop
          </button>
        </Chip>
      )}
    </div>
  );
}

/**
 * What the autopilot is doing, in the fewest words that are still true.
 *
 * The counts come from the daemon's own queue rather than from the columns on
 * screen: a card's column is written optimistically the moment it is dragged,
 * and "running" means a run that is still live — which a column cannot say,
 * since a card dragged out of `in_progress` by hand still holds its agent.
 *
 * Null while nothing has been read, and the caller falls back to the plain
 * sentence rather than drawing a zero it cannot stand behind.
 */
function queueLine(
  running: number | null,
  waiting: number | null,
): string | null {
  if (running === null || waiting === null) {
    return null;
  }
  if (running === 0 && waiting === 0) {
    return 'Autopilot starts tasks here.';
  }
  const parts: string[] = [];
  if (running > 0) {
    parts.push(`${running} running`);
  }
  if (waiting > 0) {
    parts.push(`${waiting} waiting`);
  }
  return parts.join(' · ');
}

function TaskCardRow({
  task,
  selected,
  dragging,
  onOpen,
  onDragStart,
  onDragEnd,
  onKeyDown,
}: {
  task: TaskDto;
  selected: boolean;
  dragging: boolean;
  onOpen: (taskId: string) => void;
  onDragStart: (taskId: string) => void;
  onDragEnd: () => void;
  onKeyDown?: (
    event: React.KeyboardEvent<HTMLButtonElement>,
    taskId: string,
  ) => void;
}): React.JSX.Element {
  return (
    <TaskCard
      task={task}
      selected={selected}
      dragging={dragging}
      onOpen={() => {
        onOpen(task.id);
      }}
      onDragStart={() => {
        onDragStart(task.id);
      }}
      onDragEnd={onDragEnd}
      onKeyDown={
        onKeyDown === undefined
          ? undefined
          : (event) => {
              onKeyDown(event, task.id);
            }
      }
    />
  );
}
