import { Paperclip, X } from 'lucide-react';
import { useState } from 'react';

import type { TaskFile } from '../autogenerated';
import { Button } from '../components/ui/button';
import { cn } from '../components/ui/utils';

/** `1.2 MB`, or nothing at all for a size that could not be read. */
function formatBytes(bytes: number | null): string | null {
  if (bytes === null || bytes < 0) {
    return null;
  }
  if (bytes < 1024) {
    return `${bytes} B`;
  }
  const units = ['KB', 'MB', 'GB', 'TB'];
  let value = bytes / 1024;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  // One decimal below 10 and none above it: `9.4 MB` is worth the digit,
  // `847.3 MB` is three characters of noise on a row that has to fit a name.
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${units[unit]}`;
}

/**
 * The files bound to a card — an archive, a spec, a spreadsheet.
 *
 * REPORTED as missing: "я всё ещё не могу прицеплять файлы, например
 * zip-архивы, то есть как attachments." Pasting had covered images and, for
 * anything else, wrote the file's PATH into the description — which works and
 * is invisible: a path buried in prose cannot be listed, counted or removed.
 *
 * Every row REFERENCES a file that stays where the user put it; geniro copies
 * nothing (the trade is argued daemon-side at `TaskFileSchema`). Two things
 * follow, and both are said on screen rather than left to be discovered: the
 * path is on each row's tooltip, so a link that breaks because the file moved
 * is diagnosable, and the remove control says it removes the REFERENCE.
 *
 * DROPPING is offered beside the picker because it is how somebody with a zip
 * in a Finder window will actually try first — and it costs one handler, the
 * path of a dropped file being exactly what `webUtils.getPathForFile` answers.
 */
export function TaskAttachments({
  files,
  onAttach,
  onDetach,
}: {
  files: readonly TaskFile[];
  /** Absent where there is no daemon to attach through — the harness. */
  onAttach?: (paths: readonly string[]) => void;
  onDetach?: (attachmentId: string) => void;
}): React.JSX.Element {
  const [over, setOver] = useState(false);

  const dropped = (event: React.DragEvent<HTMLDivElement>): string[] =>
    [...event.dataTransfer.files]
      .map((file) => window.geniro.filePath(file))
      .filter((path): path is string => path !== null && path !== '');

  return (
    <div
      data-slot="task-attachments"
      onDragOver={(event) => {
        // Without this the browser navigates to the dropped file, which
        // replaces the whole app with a PDF and loses the window's state.
        event.preventDefault();
        setOver(true);
      }}
      onDragLeave={() => {
        setOver(false);
      }}
      onDrop={(event) => {
        event.preventDefault();
        setOver(false);
        const paths = dropped(event);
        if (paths.length > 0) {
          onAttach?.(paths);
        }
      }}
      className={cn(
        'flex flex-col gap-1 rounded-md transition-colors',
        over && 'bg-accent/40 ring-1 ring-primary',
      )}>
      {files.map((file) => (
        <div
          key={file.id}
          // `min-h-8` is the panel's own property-row height, and it is what
          // makes the `Files` name line up with this first row rather than
          // with the middle of the stack — see `PropertyRow`'s `align`.
          className="flex min-h-8 min-w-0 items-center gap-2 rounded-md px-2 hover:bg-accent/40">
          {/* The PATH on the tooltip, not the name: the name is on screen, and
              the path is the thing that explains a file that has since moved. */}
          <span className="min-w-0 flex-1 truncate text-xs" title={file.path}>
            {file.name}
          </span>
          {formatBytes(file.bytes) === null ? null : (
            <span className="shrink-0 text-[11px] tabular-nums text-muted-foreground">
              {formatBytes(file.bytes)}
            </span>
          )}
          {onDetach === undefined ? null : (
            <button
              type="button"
              // The wording is the whole guarantee: this is not a delete, and a
              // control that read `Delete bundle.zip` would be a promise this
              // app must never keep.
              aria-label={`Remove ${file.name} from this task`}
              title="Removes it from this task. The file itself is left alone."
              onClick={() => {
                onDetach(file.id);
              }}
              className="shrink-0 rounded p-0.5 text-muted-foreground hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50">
              <X className="size-3" aria-hidden />
            </button>
          )}
        </div>
      ))}
      {onAttach === undefined ? null : (
        <Button
          variant="ghost"
          size="sm"
          className="h-8 w-fit px-2 text-[11px] text-muted-foreground"
          onClick={() => {
            void window.geniro.pickTaskFiles().then((paths) => {
              if (paths.length > 0) {
                onAttach(paths);
              }
            });
          }}>
          <Paperclip className="size-3.5" aria-hidden />
          {files.length === 0 ? 'Attach files' : 'Attach more'}
        </Button>
      )}
    </div>
  );
}
