// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type { DaemonHandle } from '../../shared/contracts';
import { createPreloadStub } from '../__fixtures__/preload-stub';
import type { TaskDto } from '../autogenerated';
import { aTask } from './__tests__/fixtures';
import { TaskCard } from './task-card';

const mocks = vi.hoisted(() => ({
  listProjects: vi.fn(() =>
    Promise.resolve([{ id: 'p1', name: 'One', folder: '/w' }]),
  ),
  listTasks: vi.fn(),
  reconcileTasks: vi.fn(),
  moveTaskStatus: vi.fn(() => Promise.resolve({})),
}));

vi.mock('../daemon-api', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../daemon-api')>()),
  createDaemonApis: () => ({
    projects: {
      listProjects: mocks.listProjects,
      readProjectQueue: vi.fn().mockResolvedValue({
        running: 0,
        waiting: 0,
        eligible: [],
        blocked: [],
      }),
    },
    tasks: {
      listTasks: mocks.listTasks,
      reconcileTasks: mocks.reconcileTasks,
      moveTaskStatus: mocks.moveTaskStatus,
    },
    // The board reads the library for its target pickers; the real
    // `createDaemonApis` returns every API class, so an omission here is the
    // double drifting rather than a case the screen should guard for.
    workflows: { listWorkflows: vi.fn().mockResolvedValue([]) },
    agents: {},
  }),
}));

const { Tasks } = await import('./Tasks');

(
  globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

let root: Root | null = null;
let container: HTMLDivElement | null = null;

beforeEach(() => {
  // The board prunes a settled card's worktree through the bridge on mount.
  window.geniro = createPreloadStub();
});

afterEach(() => {
  act(() => {
    root?.unmount();
  });
  container?.remove();
  root = null;
  container = null;
});

/**
 * A complete card wearing a status this build has never heard of.
 *
 * Built from the shared fixture with ONE field cast, rather than hand-written:
 * a hand-written row omits every field the subject does not care about, and
 * the cast then silences the type gate on all of them — which is how this spec
 * came to hold a card with no `pullRequests`, and to fail over a feature it
 * says nothing about. The unknown STATUS is the fiction under test; nothing
 * else about the row should be fictional.
 */
function fromANewerDaemon(): TaskDto {
  return aTask({
    title: 'From a newer daemon',
    status: 'blocked' as unknown as TaskDto['status'],
  });
}

describe('a status this build does not know', () => {
  it('renders the card instead of taking the board down', () => {
    // The daemon owns the status vocabulary and a newer build of it can send
    // one this renderer has never heard of — `parseTaskChanged` deliberately
    // passes such a value through rather than dropping the event. That choice
    // is only defensible if the board survives it.
    const task = fromANewerDaemon();

    container = document.createElement('div');
    document.body.appendChild(container);
    root = createRoot(container);

    expect(() => {
      act(() => {
        root!.render(
          <TaskCard
            task={task}
            selected={false}
            dragging={false}
            onOpen={vi.fn()}
            onDragStart={vi.fn()}
            onDragEnd={vi.fn()}
          />,
        );
      });
    }).not.toThrow();
    expect(container.textContent).toContain('From a newer daemon');
  });
});

describe('a keyboard move from a status this build does not know', () => {
  it('refuses the move rather than sliding the card to the first column', async () => {
    // `BOARD_COLUMNS.indexOf(status)` is -1 for an unrecognised status, so
    // `-1 + 1` indexes column 0 — an Alt+Right that looks like a nudge one
    // column right silently reclassifies the card as Backlog, and the daemon
    // is told the card came from a column it was never in.
    const unknown = fromANewerDaemon();
    mocks.reconcileTasks.mockResolvedValue([unknown]);

    const handle: DaemonHandle = {
      host: '127.0.0.1',
      port: 1,
      token: 't',
      version: '1',
      startedAt: '2026-01-01T00:00:00.000Z',
    };
    container = document.createElement('div');
    document.body.appendChild(container);
    root = createRoot(container);
    await act(async () => {
      root!.render(<Tasks handle={handle} client={null} active />);
    });

    const node = container.querySelector(
      '[data-task-id="t1"]',
    ) as HTMLButtonElement | null;
    // Guards against a vacuous pass: if the card never rendered there is no
    // node to press, and `moveTaskStatus` goes uncalled for a reason that has
    // nothing to do with the move being refused.
    expect(node).not.toBeNull();
    node?.dispatchEvent(
      new KeyboardEvent('keydown', {
        key: 'ArrowRight',
        altKey: true,
        bubbles: true,
      }),
    );
    await act(async () => {});

    expect(mocks.moveTaskStatus).not.toHaveBeenCalled();
  });
});
