import type { ChatApprovalMode } from '../autogenerated';
import { Select } from '../components/ui/select';

/** Display labels for the chat approval modes (order = menu order). */
const MODE_LABELS: readonly { value: ChatApprovalMode; label: string }[] = [
  { value: 'ask', label: 'ask' },
  { value: 'acceptEdits', label: 'accept edits' },
  { value: 'plan', label: 'plan' },
  { value: 'auto', label: 'auto-approve' },
];

/**
 * The composer's tool-approval chip, offering exactly the modes the run's CLI
 * says it honours.
 *
 * Which modes those are is the DAEMON's answer (`GET /v1/capabilities`
 * `approvals[]`, composed from each adapter's own `AdapterConfig.approval`),
 * never a judgement made here. This used to branch on the agent name —
 * `agentKind === 'cursor-agent'` rendered nothing, on the once-true grounds
 * that the CLI had no per-turn approval channel. ACP gave it one, so the chip
 * was hiding a control the user really had: every cursor chat sat in the
 * daemon's default `ask`, raised a permission card for every tool, and offered
 * no way to switch. A name-based branch cannot notice a CLI gaining a
 * capability; a capability list can.
 *
 * Renders nothing when the CLI honours no modes at all, and nothing while the
 * capability is still unknown — a picker that guesses its own options would be
 * stating a safety posture nobody verified.
 *
 * `plan` carries one extra narrowing on top: it is hidden unless the installed
 * claude probed pass (no dead UI), while a run already stored on `plan` keeps
 * the option visible so the select never lies.
 *
 * Editable MID-TURN, like every other composer chip. It used to lock, on the
 * once-true grounds that the daemon 409'd an approval change while a turn ran —
 * but the CLI accepts a `set_permission_mode` on a turn already in flight and
 * re-reads it in milliseconds, so that refusal was a limitation of the daemon
 * rather than of the agent. The daemon now hands the change to the running turn
 * and still refuses the one case it genuinely cannot honour (a turn spawned
 * with no permission gate at all), which surfaces as an ordinary error rather
 * than as a control greyed out in advance.
 */
export function ApprovalModeSelect({
  supportedModes,
  value,
  planSupported,
  onChange,
  className,
}: {
  /**
   * Modes this run's CLI honours, or null while capabilities have not loaded.
   * Empty means the CLI has no approval channel — the chip is then absent
   * because there is genuinely nothing to choose, not because of its name.
   */
  supportedModes: readonly ChatApprovalMode[] | null;
  /** Current mode; null = legacy run created before the selector existed. */
  value: ChatApprovalMode | null;
  planSupported: boolean;
  onChange: (mode: ChatApprovalMode) => void;
  className?: string;
}): React.JSX.Element | null {
  if (supportedModes === null || supportedModes.length === 0) {
    return null;
  }
  const options = MODE_LABELS.filter(
    (mode) =>
      supportedModes.includes(mode.value) &&
      (mode.value !== 'plan' || planSupported || value === 'plan'),
  );
  return (
    <Select
      variant="ghost"
      value={value}
      placeholder="cli default"
      aria-label="Tool-approval mode"
      title="Tool-approval mode"
      className={className}
      groups={[{ items: [...options] }]}
      onValueChange={(mode) => onChange(mode as ChatApprovalMode)}
    />
  );
}
