// @vitest-environment jsdom
import { act, useMemo } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type { ItemDto as ChatItem } from '../autogenerated';
import { CallBlock } from './call-block';
import {
  type CallFollowUp,
  type CallMessageChannel,
  CallMessageChannelContext,
} from './call-message-box';
import { type CallBlockEntry, groupTranscript } from './transcript-groups';
import type { TranscriptNodeMeta } from './transcript-item';
import {
  type CallMessageSend,
  useCallMessageQueues,
} from './use-call-message-queues';

(
  globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

const NODES: ReadonlyMap<string, TranscriptNodeMeta> = new Map([
  ['orch', { name: 'Orchestrator', kind: 'agent' }],
  ['poet', { name: 'Poet', kind: 'agent', agent: 'claude' }],
]);

const JOINS: CallFollowUp = { unavailableReason: null, interrupts: false };
const TARGET = expect.objectContaining({
  runId: 'run-1',
  nodeId: 'poet',
  callId: 'call-1',
});

let seq = 0;
function item(
  kind: ChatItem['kind'],
  payload: unknown,
  nodeId: string,
): ChatItem {
  seq += 1;
  return {
    id: `i-${seq}`,
    runId: 'run-1',
    nodeId,
    seq,
    kind,
    role: null,
    payload,
    createdAt: 'now',
  };
}

/** A call whose callee is working, or — without its status row — still queued. */
function blockOf(started = true): CallBlockEntry {
  const entries = groupTranscript([
    item(
      'call_started',
      { callId: 'call-1', calleeNodeId: 'poet', message: 'Write a haiku.' },
      'orch',
    ),
    ...(started
      ? [
          item(
            'status',
            { status: 'running', nodeId: 'poet', callId: 'call-1' },
            'poet',
          ),
        ]
      : []),
    item('message', { text: 'drafting', callId: 'call-1' }, 'poet'),
  ]);
  const block = entries[0];
  if (block?.type !== 'call-block') {
    throw new Error('expected a call block');
  }
  return block;
}

/** The real queue hook behind the channel, as `Chats` provides it. */
function Harness({
  block,
  send,
  followUp = JOINS,
}: {
  block: CallBlockEntry;
  send: CallMessageSend;
  followUp?: CallFollowUp | null;
}): React.JSX.Element {
  const queues = useCallMessageQueues(send);
  const channel = useMemo(
    (): CallMessageChannel => ({
      runId: 'run-1',
      queues,
      followUpOf: () => followUp,
    }),
    [queues, followUp],
  );
  return (
    <CallMessageChannelContext.Provider value={channel}>
      <CallBlock block={block} nodes={NODES} />
    </CallMessageChannelContext.Provider>
  );
}

let container: HTMLDivElement;
let root: Root;

beforeEach(() => {
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
});

afterEach(() => {
  act(() => root.unmount());
  container.remove();
  vi.useRealTimers();
});

function render(element: React.JSX.Element): void {
  act(() => root.render(element));
}

function toggleCard(): void {
  act(() =>
    container
      .querySelector<HTMLButtonElement>('button[aria-expanded]')!
      .click(),
  );
}

function openButton(): HTMLButtonElement | null {
  return container.querySelector<HTMLButtonElement>(
    '[data-slot="call-message-open"]',
  );
}

function openBox(): void {
  toggleCard();
  act(() => openButton()!.click());
}

function type(value: string): HTMLTextAreaElement {
  const box = container.querySelector('textarea')!;
  act(() => {
    Object.getOwnPropertyDescriptor(
      HTMLTextAreaElement.prototype,
      'value',
    )!.set!.call(box, value);
    box.dispatchEvent(new Event('input', { bubbles: true }));
  });
  return box;
}

async function pressEnter(box: HTMLTextAreaElement): Promise<void> {
  await act(async () => {
    box.dispatchEvent(
      new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }),
    );
    await Promise.resolve();
  });
}

async function flush(): Promise<void> {
  for (let tick = 0; tick < 8; tick += 1) {
    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
  }
}

function refusal(code: string, message: string): Error {
  return new Error(
    `daemon POST /v1/workflows/runs/run-1/nodes/poet/calls/call-1/messages failed (409): ${JSON.stringify({ code, message })}`,
  );
}

describe('messaging a call’s callee directly', () => {
  it('offers the button in the card’s FOOTER, and nothing without a channel', () => {
    render(<Harness block={blockOf()} send={vi.fn()} />);
    toggleCard();
    expect(openButton()?.closest('[data-slot="block-footer"]')).not.toBeNull();

    render(<CallBlock block={blockOf()} nodes={NODES} />);
    expect(openButton()).toBeNull();
  });

  it('sends the text to THIS call on Enter, then closes the box', async () => {
    const send = vi.fn(() => Promise.resolve());
    render(<Harness block={blockOf()} send={send} />);
    openBox();
    expect(container.textContent).toContain(
      'its answer still goes to Orchestrator',
    );
    await pressEnter(type('  use the rain metaphor  '));
    await flush();

    expect(send).toHaveBeenCalledWith(TARGET, 'use the rain metaphor', []);
    expect(container.querySelector('textarea')).toBeNull();
    expect(container.querySelector('[data-slot="queued-message"]')).toBeNull();
  });

  it('carries a pasted image with the message', async () => {
    const png = new Uint8Array([0x89, 0x50, 0x4e, 0x47]);
    const send = vi.fn(() => Promise.resolve());
    render(<Harness block={blockOf()} send={send} />);
    openBox();
    const box = container.querySelector('textarea')!;
    const paste = new Event('paste', { bubbles: true });
    Object.defineProperty(paste, 'clipboardData', {
      value: { files: [new File([png], 'shot.png', { type: 'image/png' })] },
    });
    await act(async () => {
      box.dispatchEvent(paste);
    });
    await flush();
    expect(
      container.querySelector('[data-slot="staged-attachment"]'),
    ).not.toBeNull();

    await pressEnter(type('see this'));
    await flush();

    expect(send).toHaveBeenCalledWith(TARGET, 'see this', [
      { mediaType: 'image/png', data: Buffer.from(png).toString('base64') },
    ]);
  });

  it('queues a second message behind one still being delivered, and sends it after', async () => {
    let release!: () => void;
    const send = vi
      .fn<CallMessageSend>()
      .mockImplementationOnce(
        () =>
          new Promise<void>((resolve) => {
            release = resolve;
          }),
      )
      .mockResolvedValue(undefined);
    render(<Harness block={blockOf()} send={send} />);
    openBox();
    await pressEnter(type('first'));
    act(() => openButton()!.click());
    await pressEnter(type('second'));
    await flush();

    expect(send).toHaveBeenCalledTimes(1);
    // The one being delivered is out of the list — nothing can edit or remove
    // a message the daemon already has.
    expect(
      [...container.querySelectorAll('[data-slot="queued-message"]')].map(
        (row) => row.textContent,
      ),
    ).toEqual([expect.stringContaining('second')]);
    expect(
      container.querySelector('[data-slot="call-message-sending"]'),
    ).not.toBeNull();

    await act(async () => {
      release();
    });
    await flush();

    expect(send).toHaveBeenCalledTimes(2);
    expect(send).toHaveBeenLastCalledWith(TARGET, 'second', []);
  });

  it('retries a refusal the callee may clear, and delivers', async () => {
    vi.useFakeTimers();
    const send = vi
      .fn<CallMessageSend>()
      .mockRejectedValueOnce(
        refusal(
          'CALL_MESSAGE_REFUSED',
          "Poet can't take a message while it works",
        ),
      )
      .mockResolvedValue(undefined);
    render(<Harness block={blockOf()} send={send} />);
    openBox();
    await pressEnter(type('hello'));
    await act(async () => {
      await vi.advanceTimersByTimeAsync(400);
    });

    expect(send).toHaveBeenCalledTimes(2);
    expect(container.querySelector('[role="alert"]')).toBeNull();
  });

  it('honours Send now on a paused queue pressed while a message is still going out', async () => {
    let release!: () => void;
    const send = vi
      .fn<CallMessageSend>()
      .mockImplementationOnce(
        () =>
          new Promise<void>((resolve) => {
            release = resolve;
          }),
      )
      .mockResolvedValue(undefined);
    render(<Harness block={blockOf()} send={send} />);
    openBox();
    await pressEnter(type('first'));
    act(() => openButton()!.click());
    await pressEnter(type('second'));
    await flush();

    act(() =>
      container
        .querySelector<HTMLButtonElement>('button[aria-pressed]')!
        .click(),
    );
    act(() =>
      container
        .querySelector<HTMLButtonElement>(
          'button[aria-label="Send queued message 1 now"]',
        )!
        .click(),
    );
    await act(async () => {
      release();
    });
    await flush();

    expect(send).toHaveBeenCalledTimes(2);
    expect(send).toHaveBeenLastCalledWith(TARGET, 'second', []);
  });

  it('on a paused queue releases only the message pressed, even when it is removed mid-retry', async () => {
    vi.useFakeTimers();
    let release!: () => void;
    const send = vi
      .fn<CallMessageSend>()
      .mockImplementationOnce(
        () =>
          new Promise<void>((resolve) => {
            release = resolve;
          }),
      )
      .mockRejectedValueOnce(refusal('CALL_MESSAGE_REFUSED', 'not now'))
      .mockResolvedValue(undefined);
    render(<Harness block={blockOf()} send={send} />);
    openBox();
    await pressEnter(type('zero'));
    act(() => openButton()!.click());
    await pressEnter(type('first'));
    act(() => openButton()!.click());
    await pressEnter(type('second'));
    await act(async () => {
      await vi.advanceTimersByTimeAsync(0);
    });
    act(() =>
      container
        .querySelector<HTMLButtonElement>('button[aria-pressed]')!
        .click(),
    );
    await act(async () => {
      release();
      await vi.advanceTimersByTimeAsync(0);
    });
    // Paused with [first, second] waiting: release `first` by hand.
    act(() =>
      container
        .querySelector<HTMLButtonElement>(
          'button[aria-label="Send queued message 1 now"]',
        )!
        .click(),
    );
    await act(async () => {
      await vi.advanceTimersByTimeAsync(0);
    });
    // Refused and waiting to retry — the user removes it.
    act(() =>
      container
        .querySelector<HTMLButtonElement>(
          'button[aria-label="Remove queued message 1"]',
        )!
        .click(),
    );
    await act(async () => {
      await vi.advanceTimersByTimeAsync(5_000);
    });

    expect(send.mock.calls.map((call) => call[1])).toEqual(['zero', 'first']);
    expect(
      container.querySelector('[data-slot="queued-message"]')?.textContent,
    ).toContain('second');
  });

  it('stops retrying once the refusals run out, and says why', async () => {
    vi.useFakeTimers();
    const send = vi
      .fn<CallMessageSend>()
      .mockRejectedValue(
        refusal(
          'CALL_MESSAGE_REFUSED',
          "Poet can't take a message while it works",
        ),
      );
    render(<Harness block={blockOf()} send={send} />);
    openBox();
    await pressEnter(type('hello'));
    await act(async () => {
      await vi.advanceTimersByTimeAsync(10_000);
    });

    expect(send).toHaveBeenCalledTimes(5);
    expect(container.querySelector('[role="alert"]')?.textContent).toBe(
      "Poet can't take a message while it works",
    );
    expect(
      container.querySelector('[data-slot="queued-message"]')?.textContent,
    ).toContain('hello');
  });

  it('keeps a message the daemon refuses for good, says why, and does not re-send it on its own', async () => {
    const send = vi
      .fn<CallMessageSend>()
      .mockRejectedValue(
        refusal('CALL_NOT_RUNNING', 'this call is no longer running'),
      );
    render(<Harness block={blockOf()} send={send} />);
    openBox();
    await pressEnter(type('hello'));
    await flush();

    expect(container.querySelector('[role="alert"]')?.textContent).toBe(
      'this call is no longer running',
    );
    expect(
      container.querySelector('[data-slot="queued-message"]')?.textContent,
    ).toContain('hello');

    // Folding the card and opening it again neither loses nor re-sends it.
    toggleCard();
    toggleCard();
    await flush();
    expect(send).toHaveBeenCalledTimes(1);
    expect(
      container.querySelector('[data-slot="queued-message"]')?.textContent,
    ).toContain('hello');
  });

  it('says BEFORE the press that the callee’s CLI interrupts its current step', () => {
    render(
      <Harness
        block={blockOf()}
        send={vi.fn()}
        followUp={{ unavailableReason: null, interrupts: true }}
      />,
    );
    openBox();
    expect(container.textContent).toContain('Interrupts Poet’s current step');
    expect(container.textContent).not.toContain('Joins');
  });

  it('is disabled, saying why, when the CLI takes nothing mid-turn — or before that is known', () => {
    const noChannel = {
      unavailableReason: 'no mid-turn channel',
      interrupts: false,
    };
    render(<Harness block={blockOf()} send={vi.fn()} followUp={noChannel} />);
    toggleCard();
    expect(openButton()!.disabled).toBe(true);
    expect(openButton()!.title).toBe('no mid-turn channel');

    render(<Harness block={blockOf()} send={vi.fn()} followUp={null} />);
    expect(openButton()!.disabled).toBe(true);
    expect(openButton()!.title).toContain('Checking whether Poet');
  });

  it('drops the draft on Escape', () => {
    render(<Harness block={blockOf()} send={vi.fn()} />);
    openBox();
    const box = type('never mind');
    act(() => {
      box.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }),
      );
    });
    expect(container.querySelector('textarea')).toBeNull();
    act(() => openButton()!.click());
    expect(container.querySelector('textarea')?.value).toBe('');
  });

  it('is not offered while the call is still queued for a turn', () => {
    const queued = blockOf(false);
    expect(queued.status).toBe('pending');
    render(<Harness block={queued} send={vi.fn()} />);
    toggleCard();
    expect(openButton()).toBeNull();
  });

  it('keeps an open draft when the call ends under it, and will not send it', () => {
    const send = vi.fn();
    const running = blockOf();
    render(<Harness block={running} send={send} />);
    openBox();
    type('still there?');

    render(<Harness block={{ ...running, status: 'completed' }} send={send} />);

    expect(container.querySelector('textarea')?.value).toBe('still there?');
    expect(container.textContent).toContain('Poet’s call has ended');
    expect(
      container.querySelector<HTMLButtonElement>(
        '[data-slot="call-message-send"]',
      )!.disabled,
    ).toBe(true);
    expect(send).not.toHaveBeenCalled();
  });
});
