import { Pencil, Trash2, Workflow as WorkflowIcon } from 'lucide-react';
import { memo, useEffect, useRef, useState } from 'react';

import type { PullRequestInfo } from '../../shared/contracts';
import type { RunAwaiting } from '../autogenerated';
import { NavListItem } from '../components/nav-list-item';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { cn } from '../components/ui/utils';
import { CurrentPullRequestLine } from './pull-request-row';
import { formatRelativeTime } from './relative-time';
import {
  awaitingPhrase,
  HELD_ACTIVITY,
  isWorkingRunStatus,
  RUN_STATUS_META,
  RunStatusIcon,
  type RunStatusKind,
  STANDING_ACTIVITY,
} from './run-status';

/**
 * One chat-list row: the run's label (custom title, else its workflow's name,
 * else the agent), hover-revealed rename/delete controls, the latest message
 * as a one-line preview, and a status line — icon + tone per state, always
 * LEADING the status word, spinning while running — with the last-activity time
 * on the right (hidden while running: the spinner IS the live signal). A
 * running row additionally names what the agent is doing, so the badge
 * distinguishes work from a turn parked waiting on the user.
 *
 * Filing it into a group is a DRAG, not a control on this row: a chat is moved
 * by dragging it into the group, which is one gesture where a menu was a click,
 * a read and a second click. Nothing here knows about groups any more.
 *
 * Renaming happens IN the row: the label becomes a text field in place, so the
 * name is edited where it is read instead of in a popup that hides the list it
 * came from. Enter commits, Escape reverts, blur commits. The edit state is
 * local to the row — the parent only supplies the commit, which throws to
 * report a failure, keeping the row in edit mode with the reason shown.
 *
 * Memoized (the sidebar renders one per run on every composer keystroke) —
 * callbacks take the row's `runId` so the parent can pass stable functions.
 */
export const ChatListItem = memo(function ChatListItem({
  runId,
  label,
  isWorkflow,
  status,
  lastMessage,
  lastActivityAt,
  activity = null,
  awaiting = null,
  pullRequest = null,
  active,
  unseen = false,
  naming = false,
  onActivate,
  onRename,
  onDelete,
  dragging = false,
  onDragStartRun,
  onDragEndRun,
}: {
  runId: string;
  label: string;
  /** Show the workflow glyph before the label (a team run, not a 1:1 chat). */
  isWorkflow: boolean;
  /**
   * The DISPLAY status, not the daemon's row value — wider than `RunStatus`
   * because `needs-input` is derived in the renderer (`displayRunStatus`) and
   * no daemon row ever carries it.
   */
  status: RunStatusKind;
  lastMessage: string | null;
  /** ISO time of the run's last activity (its `updatedAt`). */
  lastActivityAt: string;
  /**
   * What this run is doing right now ("running Bash"), or null. Shown BESIDE
   * the status word while running: "running" alone cannot tell one piece of
   * work from another.
   */
  activity?: string | null;
  /**
   * What the run is parked on waiting for the user, straight from the daemon's
   * approval registry — null when it is not parked.
   *
   * Separate from `activity` because it comes from a different place and
   * outlives it: `activity` rides events only, so it is empty in a window that
   * connected after the turn parked, whereas this is on the run row itself.
   * That gap is why the phrase used to disappear on a reload while the badge
   * stayed correct.
   */
  awaiting?: RunAwaiting | null;
  /**
   * The pull request this thread's folder is on, or null when there is none.
   *
   * Resolved by the owner rather than here: it is a match between the folder's
   * checked-out branch and a list read once per folder, and a row that fetched
   * its own would spawn one `gh` process per thread in the list.
   */
  pullRequest?: PullRequestInfo | null;
  active: boolean;
  /**
   * This thread finished, failed or asked something and the user has not
   * opened it since — see {@link import('./use-unseen-runs')}. Drawn as the
   * unread mark it is: a dot on the row and its name in the heavier weight,
   * the pairing a mail client uses, so the row reads as new at a glance and
   * nothing else about it moves.
   */
  unseen?: boolean;
  /**
   * The daemon is working out a NAME for this run right now, so the label on
   * screen is the placeholder it is about to replace.
   *
   * Drawn as a pulse on the label alone. Naming a claude chat costs a whole
   * extra CLI turn, and until this the row simply sat on the raw opening line
   * with nothing saying a better name was on its way — reported as exactly
   * that once the wait was measured.
   */
  naming?: boolean;
  onActivate: (runId: string) => void;
  /** Commit a new title. Rejects to report the failure back into the row. */
  onRename: (runId: string, title: string) => Promise<void>;
  onDelete: (runId: string) => void;
  /** This is the row being dragged — dimmed while it travels. */
  dragging?: boolean;
  /**
   * Picked up, and put down. Where it LANDS is the section's business
   * (`Chats.tsx`): a drop zone has to cover a whole group, including the space
   * between its rows, and `dragover` bubbles there from here anyway.
   */
  onDragStartRun?: (runId: string) => void;
  onDragEndRun?: () => void;
}): React.JSX.Element {
  const meta = RUN_STATUS_META[status];
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(label);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (editing) {
      inputRef.current?.focus();
      inputRef.current?.select();
    }
  }, [editing]);

  const startEditing = (): void => {
    setDraft(label);
    setError(null);
    setEditing(true);
  };
  const commit = async (): Promise<void> => {
    const title = draft.trim();
    // Nothing to save — an empty name would leave the row unidentifiable, and
    // an unchanged one is not worth a request.
    if (title.length === 0 || title === label) {
      setEditing(false);
      return;
    }
    setBusy(true);
    setError(null);
    try {
      await onRename(runId, title);
      setEditing(false);
    } catch (err) {
      // Stay open carrying the reason: closing would discard the typed name
      // and leave the failure invisible.
      setError(String(err));
    } finally {
      setBusy(false);
    }
  };

  return (
    <NavListItem
      active={active}
      // `select-none`: without it a press-and-drag on the row starts a TEXT
      // selection instead of the drag, which is what "gets selected, but
      // doesn't drag" looks like from the other side of the screen.
      className={cn(
        'group select-none',
        // An unseen row is marked on the ROW, not only in front of its name.
        // Reported twice: a 6px dot was missed, a 10px one still was — "точку
        // не видно… давай что-то более заметное, дополнительная линия или
        // выделение". A mark the width of a glyph competes with every other
        // glyph on a 260px rail; a bar down the row's own edge and a wash
        // behind it are read by shape and area instead, which is what a mail
        // client uses for the same job.
        //
        // The bar is a pseudo-element on the row's own box (`NavListItem` is
        // `relative`), so it costs no layout and cannot push the title the way
        // a leading element does — and it sits INSIDE the row, clear of the
        // group's colour rail, which is the section's mark rather than this
        // row's.
        unseen &&
          'before:absolute before:top-1.5 before:bottom-1.5 before:left-0 before:w-[3px] before:rounded-full before:bg-primary',
        // The wash yields to the ACTIVE row: an open chat has its own
        // highlight, and two backgrounds on one row would read as a third
        // state. Moot in practice — opening a thread is what marks it seen —
        // but the frame in between is exactly when the eye is on it.
        unseen && !active && 'bg-primary/10',
        dragging && 'opacity-40',
      )}
      activateLabel={label}
      suspendActivation={editing}
      // Not while renaming: a text field inside a draggable element cannot be
      // selected with the mouse, because the drag starts instead.
      draggable={onDragStartRun !== undefined && !editing}
      onDragStart={(event) => {
        // Firefox refuses to start a drag with no payload; the value is never
        // read back, since the parent already knows what it picked up.
        event.dataTransfer.setData('text/plain', runId);
        event.dataTransfer.effectAllowed = 'move';
        onDragStartRun?.(runId);
      }}
      onDragEnd={() => onDragEndRun?.()}
      onActivate={() => onActivate(runId)}>
      <span className="flex items-center gap-1.5">
        {/* Leads the row, ahead of the workflow glyph: it is about the row as a
            whole rather than about what kind of run it is, and the left edge is
            where an eye scanning a list for "what is new" already goes. */}
        {unseen ? (
          // 6px of caramel on a cream rail was the thing being scanned for and
          // the easiest thing on the row to miss — at that size it reads as
          // punctuation in front of the name rather than as a mark on the row.
          // 10px is the fix, and the plain disc is deliberate: a haloed variant
          // was tried at three ring weights and each read as a target or a
          // donut, which is a different symbol, while none of them was more
          // legible than simply making the dot big enough to see.
          <span
            data-slot="unseen-dot"
            title="Not opened since it last reported"
            aria-label="not seen yet"
            role="img"
            className="size-2.5 shrink-0 rounded-full bg-primary"
          />
        ) : null}
        {isWorkflow ? (
          <WorkflowIcon
            aria-hidden="true"
            className="size-3.5 shrink-0 text-muted-foreground"
          />
        ) : null}
        {editing ? (
          <Input
            ref={inputRef}
            value={draft}
            disabled={busy}
            aria-label={`Rename ${label}`}
            aria-invalid={error !== null || undefined}
            className="h-6 min-w-0 flex-1 px-1.5 py-0 text-sm"
            onChange={(event) => setDraft(event.target.value)}
            onKeyDown={(event) => {
              // The commit is one request — an Enter confirming an IME
              // composition must not fire it on a half-composed name.
              if (event.nativeEvent.isComposing) {
                return;
              }
              if (event.key === 'Enter') {
                void commit();
              } else if (event.key === 'Escape') {
                // Closing unmounts the field, and removing a focused element
                // fires no blur — so the abandoned draft cannot leak through
                // the commit-on-blur path below. The error goes with it: it
                // describes an attempt the user just abandoned, and the row
                // renders it from state, so leaving it would strand a red
                // failure line under a name that is no longer being edited.
                setError(null);
                setEditing(false);
              }
            }}
            onBlur={() => {
              if (!busy) {
                void commit();
              }
            }}
          />
        ) : (
          <>
            <span
              data-slot="chat-row-label"
              // The pulse marks the LABEL and nothing else on the row: it is
              // the one thing about to change, and animating the row would
              // read as the chat itself doing something.
              className={cn(
                'min-w-0 flex-1 truncate text-sm font-medium',
                unseen && 'font-semibold text-foreground',
                naming && 'title-naming',
              )}
              title={naming ? 'Naming this chat…' : undefined}>
              {label}
            </span>
            {/* Chats only: a workflow run's name comes from the workflow it
                ran, so renaming it here would read as editing the library
                entry from another view. */}
            {isWorkflow ? null : (
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="size-5 shrink-0 text-muted-foreground opacity-0 group-hover:opacity-100 focus-visible:opacity-100"
                aria-label={`Rename ${label}`}
                title="Rename"
                onClick={(event) => {
                  event.stopPropagation();
                  startEditing();
                }}>
                <Pencil className="size-3 shrink-0" />
              </Button>
            )}
            {/* BOTH kinds. A workflow ROW is one run's history, not the
                workflow — deleting it leaves the library entry untouched. It
                was gated with rename before, which is why the sidebar's
                workflow rows could not be removed at all. */}
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="size-5 shrink-0 text-muted-foreground opacity-0 group-hover:opacity-100 hover:text-destructive focus-visible:opacity-100"
              aria-label={`Delete ${label}`}
              title="Delete"
              onClick={(event) => {
                event.stopPropagation();
                onDelete(runId);
              }}>
              <Trash2 className="size-3 shrink-0" />
            </Button>
          </>
        )}
      </span>
      {error ? (
        <span className="truncate text-xs text-destructive">{error}</span>
      ) : null}
      {lastMessage ? (
        <span className="truncate text-xs text-muted-foreground">
          {lastMessage}
        </span>
      ) : null}
      {pullRequest ? (
        <CurrentPullRequestLine pullRequest={pullRequest} />
      ) : null}
      <span className="flex items-center gap-1 text-xs">
        {/* EVERY glyph leads its label, the spinner included. It was parked at
            the far right for a while, on the theory that a moving thing in
            front of its word would push the line about — it does not (both
            glyphs are the same `size-3 shrink-0` box), and what it did instead
            was give a running row a different shape from every other row in the
            list, so the eye had to look in two places to read one column. */}
        <RunStatusIcon status={status} />
        {/* Never wrapped: the status word is the shortest thing on the line and
            the one that must stay readable, so the activity phrase beside it
            (which already truncates) is what gives up room. Before this,
            `needs more info` broke across two lines and made the row taller
            than its neighbours. */}
        <span className={cn('shrink-0 whitespace-nowrap', meta.className)}>
          {meta.label}
        </span>
        {/* A parked row gets a phrase too, and it is worded from the KIND
            rather than taken from the activity plane: the label says the run is
            blocked on the user, this says on WHAT — the difference between
            going to read a question and going to press a button. */}
        {status === 'needs-input' && awaiting ? (
          <span className="min-w-0 truncate text-muted-foreground">
            · {awaitingPhrase(awaiting)}
          </span>
        ) : isWorkingRunStatus(status) ? (
          /* Never conditional on there BEING a phrase: a null activity means
             "working, nothing named", not "say nothing", and treating the two
             the same is what made this row flicker once per tool call. See
             {@link STANDING_ACTIVITY} — and {@link HELD_ACTIVITY}, which is the
             same fallback for a turn that is held rather than thinking. */
          <span className="min-w-0 truncate text-muted-foreground">
            ·{' '}
            {activity ??
              (status === 'held' ? HELD_ACTIVITY : STANDING_ACTIVITY)}
          </span>
        ) : null}
        {/* The time is for runs that have STOPPED — "when did this last do
            anything" is only a question about a run that is no longer doing
            it. A parked run is as live as a running one (its turn is open, its
            process is up), so it is excluded for the same reason `running` is
            — and on a 260px sidebar it was the third thing competing for the
            line, which is what made the status label wrap onto two rows. A HELD
            run is live on both of those counts too, so it is excluded with
            them: `waiting · 24m` was the reported row, and the `24m` is exactly
            the half of it that reads as a thread nobody has touched since. */}
        {!isWorkingRunStatus(status) && status !== 'needs-input' ? (
          <span className="ml-auto pl-2 text-muted-foreground">
            {formatRelativeTime(lastActivityAt)}
          </span>
        ) : null}
      </span>
    </NavListItem>
  );
});
