// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import type { Mock } from 'vitest';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type { ItemDto as ChatItem } from '../autogenerated';
import {
  chatContextAwaitingReading,
  chatContextFigures,
  type ChatContextSources,
  useRememberedContextReading,
} from './chat-context';
import type { ContextReading } from './context-reading';

function sources(
  overrides: Partial<ChatContextSources> = {},
): ChatContextSources {
  return {
    live: undefined,
    run: null,
    transcript: undefined,
    itemsLoaded: true,
    recall: () => null,
    ...overrides,
  };
}

function systemRow(payload: Record<string, unknown>): ChatItem {
  return {
    id: 's1',
    runId: 'run-1',
    nodeId: null,
    seq: 1,
    kind: 'system',
    role: null,
    payload,
    createdAt: '2026-09-14T10:00:00.000Z',
  } as ChatItem;
}

describe('chatContextFigures', () => {
  it('reads the live delta first, then the run row, then the transcript', () => {
    const live = { contextTokens: 10, contextWindowTokens: 200 };
    const run = { contextTokens: 20, contextWindowTokens: 300 };
    const transcript = { contextTokens: 30, contextWindowTokens: 400 };

    expect(chatContextFigures(sources({ live, run, transcript }))).toEqual({
      tokens: 10,
      window: 200,
    });
    expect(chatContextFigures(sources({ run, transcript }))).toEqual({
      tokens: 20,
      window: 300,
    });
    expect(chatContextFigures(sources({ transcript }))).toEqual({
      tokens: 30,
      window: 400,
    });
  });

  it('reads the window whether or not there is a count, so a compaction keeps the denominator', () => {
    // After a `/compact` every count is gone and the window — which belongs to
    // the model — is not. The empty ring needs that gauge.
    const run = { contextTokens: null, contextWindowTokens: 200000 };

    expect(chatContextFigures(sources({ run }))).toEqual({
      tokens: null,
      window: 200000,
    });
  });

  it('does not recall over a loaded transcript that yields no reading', () => {
    // A compaction discards the figures above it. A remembered one would hand
    // the old ring straight back as the last source.
    const recall = vi.fn((): ContextReading => ({
      tokens: 99000,
      window: 1000000,
    }));

    expect(chatContextFigures(sources({ itemsLoaded: true, recall }))).toEqual({
      tokens: null,
      window: null,
    });
    expect(recall).not.toHaveBeenCalled();
  });

  it('recalls the remembered reading only while nothing is loaded yet', () => {
    // The refetch mid-switch: the transcript is empty, and the ring keeps the
    // figure it last showed for this run instead of blanking.
    const recall = vi.fn((): ContextReading => ({
      tokens: 70000,
      window: 200000,
    }));

    expect(chatContextFigures(sources({ itemsLoaded: false, recall }))).toEqual(
      { tokens: 70000, window: 200000 },
    );
    expect(recall).toHaveBeenCalledTimes(1);
  });

  it('never reaches for the recalled reading while a live count exists', () => {
    const recall = vi.fn((): ContextReading => ({
      tokens: 70000,
      window: 200000,
    }));

    expect(
      chatContextFigures(
        sources({
          live: { contextTokens: 5000, contextWindowTokens: 200000 },
          itemsLoaded: false,
          recall,
        }),
      ),
    ).toEqual({ tokens: 5000, window: 200000 });
    expect(recall).not.toHaveBeenCalled();
  });
});

describe('chatContextAwaitingReading', () => {
  it('names the compaction only when the ring has no count to draw', () => {
    const compacted = [
      systemRow({ compaction: { preTokens: 100000, postTokens: 9000 } }),
    ];

    expect(chatContextAwaitingReading(null, compacted)).toBe(
      'Conversation compacted — its new size is measured on the next message',
    );
    expect(chatContextAwaitingReading(9000, compacted)).toBeNull();
    expect(chatContextAwaitingReading(null, [])).toBeNull();
  });
});

describe('useRememberedContextReading', () => {
  let container: HTMLDivElement;
  let root: Root;
  let remember: Mock<(runId: string, reading: ContextReading | null) => void>;
  let forget: Mock<(runId: string) => void>;

  function Harness(
    props: Parameters<typeof useRememberedContextReading>[0],
  ): null {
    useRememberedContextReading(props);
    return null;
  }

  async function paint(
    figures: { tokens: number | null; window: number | null },
    itemsLoaded: boolean,
  ): Promise<void> {
    await act(async () => {
      root.render(
        <Harness
          runId="run-1"
          figures={figures}
          itemsLoaded={itemsLoaded}
          remember={remember}
          forget={forget}
        />,
      );
    });
  }

  beforeEach(() => {
    container = document.createElement('div');
    document.body.appendChild(container);
    root = createRoot(container);
    remember = vi.fn<(runId: string, reading: ContextReading | null) => void>();
    forget = vi.fn<(runId: string) => void>();
  });

  afterEach(() => {
    act(() => root.unmount());
    container.remove();
  });

  it('files a measured reading for the run it was taken from', async () => {
    await paint({ tokens: 50000, window: 200000 }, true);

    expect(remember).toHaveBeenCalledWith('run-1', {
      tokens: 50000,
      window: 200000,
    });
    expect(forget).not.toHaveBeenCalled();
  });

  it('forgets the remembered reading over a loaded transcript that has none', async () => {
    // A compaction left nothing to measure: the old figure must not come back.
    await paint({ tokens: null, window: 200000 }, true);

    expect(forget).toHaveBeenCalledWith('run-1');
    expect(remember).not.toHaveBeenCalled();
  });

  it('keeps the remembered reading while the transcript is still fetching', async () => {
    await paint({ tokens: null, window: 200000 }, false);

    expect(forget).not.toHaveBeenCalled();
    expect(remember).not.toHaveBeenCalled();
  });
});
