import type { CliKind } from '../../shared/contracts';
import { ChatApprovalMode } from '../autogenerated';

/**
 * Reading FOREIGN strings into the composer's own vocabulary.
 *
 * Two kinds of string reach the composer from outside it: the daemon's
 * approval modes, and a target that may name a library workflow rather than a
 * CLI. Both arrive from settings.json — a file the user can edit and an older
 * build can write — so "it came from our own settings" is not the same as "it
 * is a value this build understands", and that check lives here.
 *
 * It imports NO component module — only `shared/contracts` and the generated
 * client — which keeps it out of the renderer's component cycles.
 */

/** Is this stored/foreign string one of the daemon's approval modes? */
export const isChatApprovalMode = (value: unknown): value is ChatApprovalMode =>
  typeof value === 'string' &&
  (Object.values(ChatApprovalMode) as string[]).includes(value);

/** A composer target naming a library workflow rather than a CLI. */
const WORKFLOW_TARGET = /^wf:(.+)$/;

/** The workflow slug a target names, or null when it names a CLI. */
export function workflowSlugOf(target: string): string | null {
  return WORKFLOW_TARGET.exec(target)?.[1] ?? null;
}

/**
 * Which CLI's model/effort a target keys under.
 *
 * A workflow's nodes each name their own in the YAML, so there is no CLI to ask
 * about — it reports `claude` because the composer's own `agentKind` does, and
 * the two must agree or a remembered model would be stored under a key the
 * composer never reads back.
 */
export function targetAgentKind(target: string): CliKind {
  return workflowSlugOf(target) !== null ? 'claude' : (target as CliKind);
}
