import { Maximize2 } from 'lucide-react';

import type { AgentContextWindow } from '../autogenerated';
import { Select } from '../components/ui/select';
import { formatTokens } from './agent-activity';

/**
 * Sentinel for "ask for no particular size" — a distinct value rather than
 * `''`, for the same reason {@link CLI_DEFAULT_EFFORT} is: the menu needs a row
 * it can check, and an empty option value reads as "nothing selected".
 */
export const MODEL_DEFAULT_CONTEXT_WINDOW = '__default__';

/**
 * The MENU row's label for {@link MODEL_DEFAULT_CONTEXT_WINDOW} — "let the
 * model decide", which is a choice and has to read as one beside the sizes.
 *
 * The CHIP does not show this. See {@link ContextWindowSelect}'s `windowTokens`.
 */
const DEFAULT_ROW_LABEL = 'model default';

/**
 * What the CHIP says when nothing is picked and nothing has been measured.
 *
 * REPORTED as "вместо Default Window, потому что это слишком длинно, может
 * быть, сразу значение дефолтное туда поставим". Two words became one, and the
 * one that went is the one the leading icon already draws.
 */
const DEFAULT_CHIP_LABEL = 'default';

/**
 * The context-window chip: which of the model's window sizes a turn runs at.
 *
 * REPORTED as "cursor also has a model size, that is 1 million, 300k … I
 * should be able to select it everywhere". It is the same shape as the effort
 * chip because it is the same kind of thing — a per-MODEL parameter whose
 * vocabulary belongs to the CLI — and it is deliberately ONE component for
 * every surface (the composer, a graph node), so the rows, the default sentinel
 * and the add-back row below cannot drift between copies.
 *
 * THE NUMBERS ARE THE CLI's OWN. Nothing here maps `1m` to a token count: the
 * count that matters is the one the agent then reports about its own window,
 * which the context meter already draws from the CLI's accounting — a table
 * here would be a second answer to that question with nothing keeping the two
 * in step. (Measured end to end: `1m` makes cursor report a 1,000,000-token
 * window, `300k` a 300,000-token one, on the same model and the same prompt.)
 *
 * WITH NO SIZES THERE IS NOTHING AT ALL — no chip, no explanation, whichever
 * of the four cases it is. It has now been all three shapes: an inert word
 * (`one window`), then a live picker offering `model default` alone with the
 * daemon's sentence as its note, and now nothing. The middle shape answered a
 * report about the FIRST ("we need to keep it as default then if there is no
 * other options … it shouldn't be just inactive button like that"), and it is
 * what got reported next: on `auto-smart`, which runs at one window, the row
 * still carried a pressable `default` — "если авто, то мы по идее не должны
 * выбирать Contact Size, а у нас я все еще вижу активно кнопку Default".
 * A control whose menu holds one row is a control with nothing to choose, and
 * both earlier shapes were arguments about how to DRAW that rather than about
 * whether to. The daemon still says why (`unavailableReason`/`unavailableKind`
 * on the listing); nothing here renders it, and the window a turn actually runs
 * at is on screen anyway — the context meter's own ring is drawn from the
 * agent's accounting.
 */
export function ContextWindowSelect({
  windows,
  value,
  nextTurnOnly = false,
  windowTokens = null,
  onChange,
  className,
  variant = 'ghost',
  id,
}: {
  windows: AgentContextWindow[];
  /** The chosen size, or null for the model's own default. */
  value: string | null;
  /** A turn is running — this pick lands on the NEXT one. */
  nextTurnOnly?: boolean;
  /**
   * The window the CLI itself reported for the model this run is on, in tokens
   * — what the context meter's own denominator is drawn from.
   *
   * Shown on the CHIP in place of the word `default`, which is the reported
   * "вместо Default Window … может быть, сразу значение дефолтное туда
   * поставим": the chip's job is to say what this turn runs at, and a measured
   * `1M` says it in two characters where `default window` took fourteen.
   *
   * It is read from the SAME reading the ring draws (the agent's own
   * accounting) rather than from a table mapping `1m` to a number — this file's
   * standing rule, and the reason the two can never disagree about one model.
   *
   * Null wherever nothing has measured it: a thread with no turn yet, the
   * builder's node inspector, a saved configuration. Those keep the word.
   */
  windowTokens?: number | null;
  onChange: (contextWindow: string | null) => void;
  className?: string;
  /**
   * `ghost` is the composer's flat chip, `default` the bordered form field the
   * graph builder's node inspector uses.
   */
  variant?: 'ghost' | 'default';
  /** Ties the form-field variant to its `Field` label. */
  id?: string;
}): React.JSX.Element | null {
  if (windows.length === 0) {
    return null;
  }
  const known = windows.some((window) => window.id === value);
  // A size the CURRENT model does not offer — a chat carried over to another
  // model, or a workflow node whose model changed under it. Always model-
  // specific here (there is no CLI-wide union of window sizes), so the row is
  // added back DISABLED rather than dropped: the value is still stored, and
  // hiding it would leave nothing on screen naming what the chip's silent
  // "default window" fallback is covering for.
  const refused = value !== null && !known;
  const rows = [
    ...windows.map((window) => ({ value: window.id, label: window.label })),
    ...(refused
      ? [{ value, label: value, disabled: true, hint: 'unavailable' }]
      : []),
  ];
  return (
    <Select
      variant={variant}
      id={id}
      aria-label="Context window"
      title={
        nextTurnOnly
          ? 'Context window — applies to your next message'
          : 'Context window'
      }
      className={className}
      leadingIcon={<Maximize2 />}
      // The chip states the window; the MENU states the choice. They are
      // different sentences and this is where they part: with nothing picked
      // the chip reads `1M` — what the turn runs at — while the menu's own row
      // still reads `model default`, which is what you would be choosing. A
      // single label cannot be both, and `triggerLabel` exists for exactly this
      // kind of split.
      triggerLabel={
        (refused ? null : value) === null
          ? windowTokens !== null && windowTokens > 0
            ? formatTokens(windowTokens)
            : DEFAULT_CHIP_LABEL
          : undefined
      }
      // What the chip SHOWS when the model does not take the stored size: the
      // default, which is what the turn will actually run at. Showing the
      // stored word would claim a window the agent cannot reach.
      value={(refused ? null : value) ?? MODEL_DEFAULT_CONTEXT_WINDOW}
      groups={[
        { items: rows },
        {
          items: [
            { value: MODEL_DEFAULT_CONTEXT_WINDOW, label: DEFAULT_ROW_LABEL },
          ],
        },
      ]}
      onValueChange={(next) =>
        onChange(next === MODEL_DEFAULT_CONTEXT_WINDOW ? null : next)
      }
    />
  );
}
