import { AttachmentMediaType } from '../autogenerated';

/**
 * The longest edge a pasted image may have when it reaches the model.
 *
 * MEASURED, not chosen. A conversation carrying more than a handful of images
 * is served under a tighter per-image ceiling, and the provider states it in
 * the refusal itself — read out of the CLI's own session record for the run
 * that produced the report:
 *
 *   messages.8.content.1.image.source.base64.data: At least one of the image
 *   dimensions exceed max allowed size for many-image requests: 2000 pixels
 *
 * The CLI caps every image IT reads at exactly this, on both axes (`maxWidth`
 * / `maxHeight` in the shipped 2.1.237 bundle's own image budget), which is
 * why an agent's own screenshots never trip it. geniro's attachments do not go
 * through that code — they are handed over as base64 content blocks — so a
 * retina screenshot arrived at its native size and stayed in the conversation
 * poisoning every turn after it. On the reported run: 27 pasted images, seven
 * of them over this line (2160, 2094, 2094, 2044, 2032, 2012, 2008 px wide),
 * and eight `API Error: an image in the conversation could not be processed
 * and was removed` rows.
 *
 * The failure is also actively misleading once it happens: the CLI's advice is
 * to re-read the file, and the offender is an OLD image in the history, so the
 * agent re-read and re-shrank the wrong picture twice before giving up.
 */
export const MAX_ATTACHMENT_PIXELS = 2000;

/**
 * The JPEG ladder for the rare image that is still too heavy once it fits the
 * pixel ceiling. Same shape as the CLI's own descent, one rung shorter — below
 * this a screenshot's text stops being readable, and an unreadable image is not
 * a smaller one, it is a wasted one.
 */
const JPEG_QUALITIES = [0.8, 0.6, 0.4] as const;

/** One decoded image, plus the handle its own encoder will want back. */
export interface DecodedImage {
  width: number;
  height: number;
  /**
   * The decoder's own object, passed straight back to the SAME codec's
   * `encode`. Deliberately opaque: nothing here draws it, and typing it as a
   * `CanvasImageSource` would make the seam impossible to fake in a spec.
   */
  source: unknown;
  close: () => void;
}

/**
 * Decode + re-encode, as one injectable pair.
 *
 * A seam rather than direct calls because the browser's own implementation
 * (`createImageBitmap` + `OffscreenCanvas`) exists in neither jsdom nor node,
 * so without it the ladder below could only ever be tested through a proxy for
 * itself.
 */
export interface ImageCodec {
  decode: (blob: Blob) => Promise<DecodedImage>;
  encode: (
    image: DecodedImage,
    width: number,
    height: number,
    mediaType: 'image/png' | 'image/jpeg',
    quality?: number,
  ) => Promise<Blob>;
}

/**
 * The size an image should be drawn at to fit inside a square of `max`, or
 * null when it already does.
 *
 * Null rather than the original size on purpose: it is what tells the caller
 * to leave the ORIGINAL BYTES alone. Re-encoding an image that was already
 * within the ceiling would re-compress every paste for nothing, and a PNG
 * round-trip of a photo routinely comes out larger than the JPEG it replaced.
 */
export function scaleToFit(
  width: number,
  height: number,
  max: number,
): { width: number; height: number } | null {
  if (width <= max && height <= max) {
    return null;
  }
  // The longer edge decides, so the aspect ratio survives — a 2160x1886 shot
  // becomes 2000x1746 rather than being squared off.
  const factor = max / Math.max(width, height);
  return {
    // `max(1, …)` so a pathological aspect ratio cannot produce a zero-width
    // canvas, which throws rather than degrading.
    width: Math.max(1, Math.round(width * factor)),
    height: Math.max(1, Math.round(height * factor)),
  };
}

/** What a normalization produced: possibly re-encoded, so the type may differ. */
export interface NormalizedImage {
  mediaType: AttachmentMediaType;
  blob: Blob;
}

/**
 * Bring one pasted image within {@link MAX_ATTACHMENT_PIXELS}, and within
 * `maxBytes` if the resize alone does not get it there.
 *
 * An image already inside the ceiling comes back UNTOUCHED — same bytes, same
 * media type — which is the common case and the one where doing nothing is
 * strictly better than re-encoding.
 *
 * PNG first when a resize is needed, because the images being pasted here are
 * screenshots: lossless keeps the text sharp and the alpha channel, and a
 * 2000px screenshot is comfortably inside the byte cap. JPEG is the fallback
 * for the picture that is still too heavy, and it is a real loss — transparency
 * flattens — which is why it is reached only after PNG has failed.
 */
export async function normalizeImage(
  blob: Blob,
  mediaType: AttachmentMediaType,
  maxBytes: number,
  codec: ImageCodec,
): Promise<NormalizedImage> {
  const image = await codec.decode(blob);
  try {
    const target = scaleToFit(image.width, image.height, MAX_ATTACHMENT_PIXELS);
    if (target === null) {
      return { mediaType, blob };
    }
    const png = await codec.encode(
      image,
      target.width,
      target.height,
      'image/png',
    );
    if (png.size <= maxBytes) {
      return { mediaType: AttachmentMediaType.ImagePng, blob: png };
    }
    let smallest = png;
    for (const quality of JPEG_QUALITIES) {
      const jpeg = await codec.encode(
        image,
        target.width,
        target.height,
        'image/jpeg',
        quality,
      );
      if (jpeg.size <= maxBytes) {
        return { mediaType: AttachmentMediaType.ImageJpeg, blob: jpeg };
      }
      // Kept even when it is still too big: the caller's byte check is what
      // refuses the paste, and refusing with the SMALLEST rendering means the
      // message it shows is about a real limit rather than about the first
      // thing tried.
      if (jpeg.size < smallest.size) {
        smallest = jpeg;
      }
    }
    return {
      mediaType:
        smallest === png
          ? AttachmentMediaType.ImagePng
          : AttachmentMediaType.ImageJpeg,
      blob: smallest,
    };
  } finally {
    image.close();
  }
}

/**
 * The renderer's own codec — Chromium's, which is what this app runs in.
 *
 * `createImageBitmap` decodes every type the attachment store accepts without
 * an `<img>` element or an object-URL lifetime to leak, and `OffscreenCanvas`
 * encodes without one either. Neither exists in jsdom, which is exactly why
 * {@link ImageCodec} is a parameter.
 */
export const browserImageCodec: ImageCodec = {
  decode: async (blob) => {
    const bitmap = await createImageBitmap(blob);
    return {
      width: bitmap.width,
      height: bitmap.height,
      source: bitmap,
      close: () => bitmap.close(),
    };
  },
  encode: async (image, width, height, mediaType, quality) => {
    const canvas = new OffscreenCanvas(width, height);
    const context = canvas.getContext('2d');
    if (context === null) {
      throw new Error('could not open a 2d canvas to resize the image');
    }
    context.drawImage(image.source as CanvasImageSource, 0, 0, width, height);
    return canvas.convertToBlob({ type: mediaType, quality });
  },
};
