import type { RunProcess, RunProcessTree } from '../autogenerated';

/**
 * What a part of an agent's process tree is FOR, as a reader thinks of it:
 * the CLI itself, the servers and tools it launched for its whole life, and
 * the commands it ran. A raw tree answers "who started whom", which is the
 * wrong question about a `zsh` wrapping a `sleep` or an `npm` wrapping a
 * `playwright-mcp`.
 */
export type ProcessRole = 'cli' | 'server' | 'command';

export const ROLE_ORDER: readonly ProcessRole[] = ['cli', 'server', 'command'];

export const ROLE_CAPTION: Record<ProcessRole, string> = {
  cli: 'Agent',
  server: 'Servers & tools',
  command: 'Commands',
};

/** One thing the agent runs: a top-level child of the CLI and everything under it. */
export interface ProcessGroup {
  /** Stable across polls — the pid of the subtree's top process. */
  key: string;
  role: ProcessRole;
  label: string;
  /** Every process in it, top first, in tree order. */
  processes: RunProcess[];
  /**
   * How many processes it is, as a reader would count them: a command's shell
   * wrappers are plumbing, so `zsh → perl` is ONE command, not two.
   */
  size: number;
  cpuPercent: number;
  rssBytes: number;
  /** How long its top process has been running, in seconds. */
  elapsedSeconds: number | null;
  /** Outlived the shell that started it — kept only by the process group. */
  detached: boolean;
}

/** A shell is a wrapper around a command, never the thing that was run. */
const SHELLS = new Set(['zsh', 'bash', 'sh', 'dash', 'fish']);

/** Package runners name the package's binary as a CHILD, not themselves. */
const LAUNCHERS = new Set([
  'npm',
  'npx',
  'pnpm',
  'pnpx',
  'bunx',
  'yarn',
  'uvx',
]);

/** Long enough to recognise a command, short enough for one row. */
const MAX_COMMAND_CHARS = 80;

function oneLine(text: string): string {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length > MAX_COMMAND_CHARS
    ? `${flat.slice(0, MAX_COMMAND_CHARS - 1)}…`
    : flat;
}

/**
 * The command a shell subtree is running: the first process under it that is
 * not itself a shell, by its own command line — or, for a shell running only
 * builtins, what it was asked to `eval` (the wrapper claude puts around every
 * command), or the shell itself.
 */
function commandLabel(subtree: readonly RunProcess[]): string {
  const real = subtree.find((process) => !SHELLS.has(process.name));
  if (real !== undefined) {
    return oneLine(real.args);
  }
  const top = subtree[0];
  if (top === undefined) {
    return 'shell';
  }
  const evaluated = /\beval '([^']+)'/.exec(top.args)?.[1];
  return evaluated === undefined ? top.name : oneLine(evaluated);
}

function serverLabel(subtree: readonly RunProcess[]): string {
  const top = subtree[0];
  if (top === undefined) {
    return 'process';
  }
  const child = subtree[1];
  return LAUNCHERS.has(top.name) && child !== undefined ? child.name : top.name;
}

/**
 * Split one agent's tree into the groups a reader thinks in: the CLI alone,
 * then each top-level subtree under it as one server/tool or one command.
 *
 * A subtree whose top is a SHELL, or which outlived its shell (`group` link),
 * is a command; anything else the CLI started directly is a server or tool —
 * an MCP server, a language server, a watcher. That is a reading of what the
 * process tree looks like, not a fact the CLI states, which is why the label
 * always carries the real name and the full command lines stay on hover.
 */
export function groupProcesses(tree: RunProcessTree): ProcessGroup[] {
  const groups: ProcessGroup[] = [];
  let current: RunProcess[] | null = null;
  const subtrees: RunProcess[][] = [];
  for (const process of tree.processes) {
    if (process.depth === 0) {
      groups.push(
        toGroup(String(process.pid), 'cli', process.name, [process], false),
      );
      current = null;
      continue;
    }
    if (process.depth === 1 || current === null) {
      current = [process];
      subtrees.push(current);
    } else {
      current.push(process);
    }
  }
  for (const subtree of subtrees) {
    const top = subtree[0] as RunProcess;
    const detached = top.link === 'group';
    const role: ProcessRole =
      detached || SHELLS.has(top.name) ? 'command' : 'server';
    groups.push(
      toGroup(
        String(top.pid),
        role,
        role === 'command' ? commandLabel(subtree) : serverLabel(subtree),
        subtree,
        detached,
      ),
    );
  }
  return groups.sort(
    (a, b) => ROLE_ORDER.indexOf(a.role) - ROLE_ORDER.indexOf(b.role),
  );
}

function toGroup(
  key: string,
  role: ProcessRole,
  label: string,
  processes: RunProcess[],
  detached: boolean,
): ProcessGroup {
  return {
    key,
    role,
    label,
    processes,
    size:
      role === 'command'
        ? Math.max(
            1,
            processes.filter((process) => !SHELLS.has(process.name)).length,
          )
        : processes.length,
    cpuPercent:
      Math.round(processes.reduce((sum, p) => sum + p.cpuPercent, 0) * 10) / 10,
    rssBytes: processes.reduce((sum, p) => sum + p.rssBytes, 0),
    elapsedSeconds: processes[0]?.elapsedSeconds ?? null,
    detached,
  };
}
