import { createContext } from 'react';

import type { DaemonHandle } from '../../shared/contracts';
import type { ItemDto as ChatItem } from '../autogenerated';
import { daemonBaseUrl } from '../daemon-api';

/**
 * A PAGE an agent published with `show_artifact`, read off the transcript.
 *
 * TWIN PARSER: `apps/daemon/src/v1/agents/chat.types.ts` declares the shape
 * (`HostArtifactRow`) and `apps/daemon/src/v1/agents/services/chat.service.ts`
 * writes these keys for the `show_artifact` item kind. An item payload is
 * `z.unknown()` on the wire BY DESIGN — every kind carries a different shape —
 * so no generated type reaches here and this is an independent reading of one
 * shape. A key renamed on either side must be renamed on both.
 *
 * Not to be confused with `artifact-payload.ts` beside it, which harvests
 * **claude.ai** artifact URLs out of a transcript. That one is a URL and a
 * title scraped from a CLI's prose; this is geniro's own row, naming a document
 * this daemon stored and serves. They share a word and nothing else.
 *
 * What this payload holds that no other card's does is a CAPABILITY: the `key`
 * is what lets the renderer address the page at all, because an `<iframe src>`
 * cannot carry a bearer header. It travels only over the authenticated channel
 * this row already arrives on.
 */

/** One `show_artifact` row, as the card and the panel read it. */
export interface PublishedArtifact {
  /** The agent's own name for the page, and its identity across turns. */
  artifactId: string;
  /** Which revision this row announced — 1 for a first publish. */
  version: number;
  title: string;
  /** Null when the agent named none; the row then shows the title alone. */
  summary: string | null;
  /** The per-artifact capability the serving route authenticates on. */
  key: string;
}

function readString(value: unknown): string | null {
  if (typeof value !== 'string') {
    return null;
  }
  const trimmed = value.trim();
  return trimmed.length === 0 ? null : trimmed;
}

/**
 * Read one `show_artifact` row, or null when the payload cannot address a page.
 *
 * Every field but `summary` is required, and that is not strictness for its own
 * sake: without an id, a version and a key there is no URL to frame, so a row
 * missing any of them describes a page nobody can open. Answering null draws
 * nothing, which is the honest outcome — a card that cannot open its own
 * artifact is worse than no card.
 */
export function readPublishedArtifact(
  item: ChatItem,
): PublishedArtifact | null {
  const payload: unknown = item.payload;
  if (typeof payload !== 'object' || payload === null) {
    return null;
  }
  const row = payload as {
    artifactId?: unknown;
    version?: unknown;
    title?: unknown;
    summary?: unknown;
    key?: unknown;
  };
  const artifactId = readString(row.artifactId);
  const title = readString(row.title);
  const key = readString(row.key);
  const { version } = row;
  if (
    artifactId === null ||
    title === null ||
    key === null ||
    typeof version !== 'number' ||
    !Number.isInteger(version) ||
    version < 1
  ) {
    return null;
  }
  return { artifactId, version, title, summary: readString(row.summary), key };
}

/**
 * Builds the loopback URL one stored artifact page is served at.
 *
 * `raw` asks for the document the AGENT wrote instead of the framed page —
 * what the save path fetches, since geniro's theme-and-height wrapper is a
 * handshake with an embedder and has no business in a file somebody is sent.
 */
export type ArtifactUrlBuilder = (
  artifact: PublishedArtifact,
  options?: { raw?: boolean },
) => string;

/**
 * The URL one published page is served at.
 *
 * Beside the reader rather than in the screen that happens to need it: the
 * query shape is half of this feature's wire contract (the daemon's
 * `ArtifactsController` owns the other half), while the scheme/host/port is
 * `daemonBaseUrl`'s and is not re-derived here.
 *
 * Every part is percent-encoded. The ids are shapes this app itself minted, so
 * this is belt-and-braces rather than the containment — that lives in the
 * store, which re-validates both before joining either into a path.
 */
export function artifactPageUrl(
  handle: DaemonHandle,
  runId: string,
  artifact: PublishedArtifact,
  options?: { raw?: boolean },
): string {
  const path = `/v1/artifacts/${encodeURIComponent(runId)}/${encodeURIComponent(
    artifact.artifactId,
  )}`;
  const query = `key=${encodeURIComponent(artifact.key)}&v=${artifact.version}`;
  // The one literal the route turns the raw reading on for — see its own note
  // on why it is presence rather than a parsed boolean.
  const raw = options?.raw === true ? '&raw=1' : '';
  return `${daemonBaseUrl(handle)}${path}?${query}${raw}`;
}

/**
 * The builder a provider hands down, with the run and the daemon bound.
 *
 * It exists so no call site writes the lambda itself. A provider spelled
 * `(artifact) => artifactPageUrl(handle, runId, artifact)` type-checks —
 * JavaScript lets a shorter function stand in for a longer one — and silently
 * drops `options`, which means the save path is handed the FRAMED page and
 * writes geniro's own frame wrapper into a file meant for somebody else. That
 * shipped once and was caught by opening the saved file, not by the suite:
 * every spec in front of it used a stub provider, so the stub was the only
 * thing being tested. One factory is what makes the mistake unwritable.
 */
export function artifactUrlBuilder(
  handle: DaemonHandle,
  runId: string,
): ArtifactUrlBuilder {
  return (artifact, options) =>
    artifactPageUrl(handle, runId, artifact, options);
}

/**
 * How a published page reaches the screen.
 *
 * A context rather than a prop for {@link LocalImageLoaderContext}'s reason:
 * every shell between `Chats` and a transcript row is memoized, and threading a
 * builder through each would defeat that. The RUN and the daemon's negotiated
 * host and port are bound by the provider rather than passed per call — the
 * consumers render one run's transcript and hold neither.
 *
 * Null outside a provider: a consumer then says the page cannot be opened
 * rather than framing a URL it had to invent.
 */
export const ArtifactUrlContext = createContext<ArtifactUrlBuilder | null>(
  null,
);
