import type { RunGroupColor, RunGroupDto } from '../autogenerated';
import type { RunStatusKind } from './run-status';

/**
 * The sidebar's groups: how a list of runs is folded into the sections the
 * chat list draws, and what a section's header says about what is inside it.
 *
 * Pure and separate from the components for the usual reason — the bucketing
 * and the "is anything in here working" reading are the parts worth pinning,
 * and neither needs a DOM.
 */

/**
 * A group colour's dot class.
 *
 * A LOOKUP rather than `bg-group-${color}`: Tailwind scans source text for
 * whole class names, so an interpolated one is never emitted and every dot
 * would render transparent. Exhaustive over the generated union, so a colour
 * added to the daemon's enum fails type-checking here instead of silently
 * rendering nothing.
 */
export const GROUP_DOT_CLASS: Record<RunGroupColor, string> = {
  blue: 'bg-group-blue',
  purple: 'bg-group-purple',
  green: 'bg-group-green',
  orange: 'bg-group-orange',
  pink: 'bg-group-pink',
  indigo: 'bg-group-indigo',
  teal: 'bg-group-teal',
  red: 'bg-group-red',
};

/**
 * The rail a group's chats hang off — the same hue as its dot, as a BORDER.
 *
 * Spelled in full for the same reason {@link GROUP_DOT_CLASS} is: Tailwind
 * scans source text, so an interpolated class name is never emitted and every
 * rail would render in the default border colour.
 */
export const GROUP_RAIL_CLASS: Record<RunGroupColor, string> = {
  blue: 'border-group-blue/40',
  purple: 'border-group-purple/40',
  green: 'border-group-green/40',
  orange: 'border-group-orange/40',
  pink: 'border-group-pink/40',
  indigo: 'border-group-indigo/40',
  teal: 'border-group-teal/40',
  red: 'border-group-red/40',
};

/** Human labels for the colour picker, in the order the daemon lists them. */
export const GROUP_COLOR_LABEL: Record<RunGroupColor, string> = {
  blue: 'Blue',
  purple: 'Purple',
  green: 'Green',
  orange: 'Orange',
  pink: 'Pink',
  indigo: 'Indigo',
  teal: 'Teal',
  red: 'Red',
};

/** One rendered section of the chat list. */
export interface RunGroupSection<TRun> {
  /** The group, or null for the loose runs that belong to none. */
  group: RunGroupDto | null;
  runs: TRun[];
}

/**
 * Fold a run list into sections: every group in sidebar order, then the runs
 * belonging to none.
 *
 * The loose section is LAST and always present, even when empty — it is where a
 * run lands when it leaves a group, so a sidebar whose every chat is filed
 * still has to show somewhere to drop the next one. An EMPTY GROUP is kept for
 * the same reason: a user who just made one and has not filled it yet must be
 * able to see that it exists.
 *
 * A run whose `groupId` names no group falls into the loose section rather than
 * vanishing. That should not happen — deleting a group releases its runs — but
 * "we lost your chat" is the one outcome a grouping bug must not have.
 */
export function runGroupSections<TRun extends { groupId: string | null }>(
  groups: readonly RunGroupDto[],
  runs: readonly TRun[],
): RunGroupSection<TRun>[] {
  const ordered = [...groups].sort((a, b) => a.position - b.position);
  const byGroup = new Map<string, TRun[]>(
    ordered.map((group) => [group.id, [] as TRun[]]),
  );
  const loose: TRun[] = [];
  for (const run of runs) {
    const bucket = run.groupId === null ? undefined : byGroup.get(run.groupId);
    (bucket ?? loose).push(run);
  }
  return [
    ...ordered.map((group) => ({ group, runs: byGroup.get(group.id) ?? [] })),
    { group: null, runs: loose },
  ];
}

/**
 * How many rows a section draws before the rest go behind "Show all".
 *
 * A sidebar is a list of PLACES TO GO, not an archive: a group holding a
 * hundred finished threads pushed every group below it off the screen, so
 * reaching the next one meant scrolling past conversations nobody was going
 * back to. Eight is roughly one screenful of rows in a 260px rail beside a
 * header, which is the point — a section stays scannable without its neighbours
 * leaving the viewport.
 */
export const SECTION_PREVIEW_LIMIT = 8;

/**
 * Below this many hidden rows the fold is not worth drawing.
 *
 * The toggle is itself a row: hiding one costs a row to show a row, and hiding
 * two saves exactly one. Anything under this reads as the sidebar being coy
 * about nothing.
 */
const MIN_HIDDEN = 3;

/** A section's rows as drawn, and how many the fold is holding back. */
export interface RunGroupPreview<TRun> {
  visible: TRun[];
  /** Rows the fold is hiding; 0 when the section is drawn in full. */
  hidden: number;
}

/**
 * Which of a section's runs are drawn while it is FOLDED — the caller decides
 * whether it is (a `hidden` of 0 is also how it learns there is nothing to
 * unfold, so this answers both questions at once).
 *
 * Two rules, in this order:
 *
 * 1. **Anything `keep` claims is always drawn**, however far down the list it
 *    sits — that is the whole feature. A working thread the user is waiting on
 *    must never be the thing behind "Show all", so a group with thirty live
 *    chats draws thirty rows and hides nothing.
 * 2. The remaining slots up to `limit` go to the runs the caller ordered first
 *    (the list is newest-activity-first), so a folded group still opens on the
 *    threads someone was last in.
 *
 * The caller's ORDER is preserved either way — kept rows are not floated to the
 * top. Reordering on status would make rows jump under the cursor exactly when
 * a turn starts or ends, which is when the user is most likely to be aiming at
 * one.
 */
export function previewSectionRuns<TRun>(
  runs: readonly TRun[],
  {
    keep,
    limit = SECTION_PREVIEW_LIMIT,
  }: {
    /** This run is drawn whatever the limit says. */
    keep: (run: TRun) => boolean;
    limit?: number;
  },
): RunGroupPreview<TRun> {
  if (runs.length <= limit) {
    return { visible: [...runs], hidden: 0 };
  }
  const shown = new Set<number>();
  runs.forEach((run, index) => {
    if (keep(run)) {
      shown.add(index);
    }
  });
  for (let index = 0; index < runs.length && shown.size < limit; index++) {
    shown.add(index);
  }
  const hidden = runs.length - shown.size;
  if (hidden < MIN_HIDDEN) {
    return { visible: [...runs], hidden: 0 };
  }
  return { visible: runs.filter((_, index) => shown.has(index)), hidden };
}

/** What a group header reports about the threads inside it. */
export interface RunGroupSummary {
  count: number;
  /** At least one thread in here is working. */
  busy: boolean;
  /** At least one thread in here is parked waiting on the user. */
  needsInput: boolean;
}

/**
 * Summarize a section from the statuses its rows are ALREADY showing.
 *
 * It takes the display statuses rather than the run rows deliberately: the
 * badge a row draws is `displayRunStatus`'s answer, not the daemon column, and
 * a header computed from the raw column would contradict the rows beneath it in
 * exactly the cases that matter (a live turn under a stale `completed` row, a
 * parked question the row already paints as `needs-input`).
 *
 * `needsInput` is reported alongside `busy` rather than folded into it because
 * a COLLAPSED group would otherwise hide the one state that cannot advance
 * without the user — which is the failure this whole feature would introduce if
 * a header only ever said "something is running".
 */
export function runGroupSummary(
  statuses: readonly RunStatusKind[],
): RunGroupSummary {
  return {
    count: statuses.length,
    busy: statuses.includes('running'),
    needsInput: statuses.includes('needs-input'),
  };
}
