import { ChevronRight } from 'lucide-react';
import { useContext } from 'react';

import {
  agentIconName,
  AgentIdentityContext,
  agentShortName,
} from '../agent-identity';
import type {
  RunProcess,
  RunProcessesDto,
  RunProcessTree,
} from '../autogenerated';
import { AgentGlyph } from '../components/agent-glyph';
import {
  ProcessFigureCells,
  ProcessFigureHeader,
  ShareBar,
} from '../components/process-figures';
import { cn } from '../components/ui/utils';
import { useThreadFlag } from './thread-ui-memory';

/** Deeper than this, a row stops indenting — the column is ~280px wide. */
const MAX_INDENT_DEPTH = 4;

function formatUptime(seconds: number | null): string | null {
  if (seconds === null) {
    return null;
  }
  if (seconds < 60) {
    return `${seconds}s`;
  }
  if (seconds < 3_600) {
    return `${Math.floor(seconds / 60)}m`;
  }
  if (seconds < 86_400) {
    return `${Math.floor(seconds / 3_600)}h ${Math.floor((seconds % 3_600) / 60)}m`;
  }
  return `${Math.floor(seconds / 86_400)}d ${Math.floor((seconds % 86_400) / 3_600)}h`;
}

/**
 * Whose process this is: the workflow node, the callee conversation, or — for
 * a chat, whose one agent has no name of its own — its CLI.
 */
export function treeLabel(tree: RunProcessTree, agentName: string): string {
  if (tree.nodeId !== null) {
    return tree.nodeId;
  }
  if (tree.conversationId !== null) {
    return `call ${tree.conversationId}`;
  }
  return agentName;
}

function processTitle(process: RunProcess): string {
  const uptime = formatUptime(process.elapsedSeconds);
  const how =
    process.link === 'root'
      ? 'the agent CLI geniro started'
      : process.link === 'group'
        ? 'outlived the shell that started it — kept by the CLI’s process group'
        : `started under pid ${process.ppid}`;
  return [
    `pid ${process.pid}${uptime === null ? '' : ` · up ${uptime}`} · ${how}`,
    process.args,
  ].join('\n');
}

function ProcessRow({ process }: { process: RunProcess }): React.JSX.Element {
  return (
    <li
      className="flex items-baseline gap-1.5 py-px text-xs"
      title={processTitle(process)}
      style={{
        paddingLeft: `${Math.min(process.depth, MAX_INDENT_DEPTH) * 12}px`,
      }}>
      <span className="flex min-w-0 flex-1 items-baseline gap-1.5">
        <span
          className={cn(
            'min-w-0 truncate',
            process.link === 'root'
              ? 'font-medium text-foreground'
              : 'text-foreground',
          )}>
          {process.name}
        </span>
        <span className="shrink-0 font-mono text-[10px] text-muted-foreground tabular-nums">
          {process.pid}
        </span>
        {process.link === 'group' ? (
          <span className="shrink-0 rounded border border-border px-1 py-px text-[10px] text-muted-foreground">
            detached
          </span>
        ) : null}
      </span>
      <ProcessFigureCells
        cpuPercent={process.cpuPercent}
        rssBytes={process.rssBytes}
      />
    </li>
  );
}

function ProcessTree({
  tree,
  totalBytes,
  showShare,
}: {
  tree: RunProcessTree;
  totalBytes: number;
  showShare: boolean;
}): React.JSX.Element {
  const identities = useContext(AgentIdentityContext);
  const agentName =
    tree.agentKind === null
      ? 'agent'
      : agentShortName(identities, tree.agentKind);
  const label = treeLabel(tree, agentName);
  // Open by default: the section is folded away with the panel, so a reader
  // who unfolded it came to see these rows. The choice is per thread.
  const [open, setOpen] = useThreadFlag(`processes:${tree.sessionKey}`, true);
  const fraction = totalBytes > 0 ? tree.rssBytes / totalBytes : 0;
  return (
    <li className="flex flex-col gap-1">
      <button
        type="button"
        aria-expanded={open}
        onClick={() => setOpen((value) => !value)}
        title={tree.cwd}
        className="flex items-center gap-1.5 rounded-md text-xs outline-none hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring/50">
        <span className="flex min-w-0 flex-1 items-center gap-1.5">
          <ChevronRight
            aria-hidden="true"
            className={cn(
              'size-3 shrink-0 text-muted-foreground transition-transform',
              open && 'rotate-90',
            )}
          />
          <AgentGlyph
            icon={agentIconName(identities, tree.agentKind ?? '')}
            className="size-3.5 shrink-0 text-muted-foreground"
          />
          <span className="min-w-0 truncate font-medium text-foreground">
            {label}
          </span>
          {label !== agentName ? (
            <span className="shrink-0 text-muted-foreground">{agentName}</span>
          ) : null}
          <span className="shrink-0 text-[11px] text-muted-foreground tabular-nums">
            {tree.processes.length}
          </span>
        </span>
        <ProcessFigureCells
          cpuPercent={tree.cpuPercent}
          rssBytes={tree.rssBytes}
          strong
        />
      </button>
      {showShare ? (
        <ShareBar
          fraction={fraction}
          label={`${Math.round(fraction * 100)}% of this thread’s memory`}
        />
      ) : null}
      {open ? (
        <ul
          aria-label={`Processes of ${label}`}
          className="m-0 ml-1.5 flex list-none flex-col border-l border-border p-0 pl-2">
          {tree.processes.map((process) => (
            <ProcessRow key={process.pid} process={process} />
          ))}
        </ul>
      ) : null}
    </li>
  );
}

/**
 * Every process this thread has running — each agent CLI geniro started for
 * it and the whole tree under it (MCP servers, shells, dev servers,
 * sub-agents' tools) — with CPU and resident memory per process.
 *
 * A LIVE reading, not a history: a process that has ended is simply gone from
 * the next poll.
 */
export function RunProcesses({
  data,
  loading,
  error,
}: {
  data: RunProcessesDto | null;
  loading: boolean;
  error: string | null;
}): React.JSX.Element | null {
  if (data === null) {
    if (error !== null) {
      return <p className="text-xs text-muted-foreground">{error}</p>;
    }
    return loading ? (
      <p className="text-xs text-muted-foreground">reading processes…</p>
    ) : null;
  }
  const several = data.trees.length > 1;
  return (
    <div className="flex flex-col gap-2">
      {data.unavailableReason === null ? null : (
        <p className="text-xs text-muted-foreground">
          {data.unavailableReason}
        </p>
      )}
      {data.trees.length === 0 ? (
        data.unavailableReason === null ? (
          <p className="text-xs text-muted-foreground">
            no agent process is running for this thread
          </p>
        ) : null
      ) : (
        <>
          <ProcessFigureHeader
            label={`${data.processes} process${data.processes === 1 ? '' : 'es'}`}
          />
          {/* A total is only news over SEVERAL agents — over one it is the
              agent's own header, a line below. */}
          {several ? (
            <div
              data-slot="processes-total"
              className="flex items-baseline gap-1.5 text-xs">
              <span className="min-w-0 flex-1 truncate text-muted-foreground">
                all {data.trees.length} agents
              </span>
              <ProcessFigureCells
                cpuPercent={data.cpuPercent}
                rssBytes={data.rssBytes}
                strong
              />
            </div>
          ) : null}
          <ul className="m-0 flex list-none flex-col gap-2.5 p-0">
            {data.trees.map((tree) => (
              <ProcessTree
                key={tree.sessionKey}
                tree={tree}
                totalBytes={data.rssBytes}
                showShare={several}
              />
            ))}
          </ul>
        </>
      )}
      {error === null ? null : (
        <p className="text-[11px] text-muted-foreground">{error}</p>
      )}
    </div>
  );
}
