import type { AgentSession, AgentSessionListingDto } from '../autogenerated';
import { shortenPath } from './directory-select';

/**
 * Searching a CLI's past conversations across EVERY profile the user has, not
 * just the one the composer happens to point at.
 *
 * REPORTED as "i can see only one claude profile there - it should search by
 * ALL profiles". A profile is an account: the picker asked the one config
 * directory the composer held, so conversations from the user's other
 * subscription were not merely hard to find, they were not on the list at all —
 * and nothing on screen said a second store existed.
 *
 * The fan-out is here rather than in the daemon, and the reason is where the
 * knowledge lives: a claude profile is a directory somebody chose, recorded in
 * this app's own `settings.json` (`configDir` + `recentConfigDirs`), and the
 * daemon never opens that file. There is no registry of profiles on disk for it
 * to enumerate. So the renderer asks once per profile and folds the answers —
 * which is honest folding rather than the kind the daemon exists to prevent:
 * each answer is COMPLETE for its own store, so nothing here re-derives a
 * figure out of a partial page.
 */

/**
 * How many profile asks are in flight at once.
 *
 * The fan-out reaches one ask per profile — up to twelve, since the profile
 * list is the default plus the recent config directories, themselves capped at
 * ten — and each ask is a full-profile scan on the daemon, whose per-file
 * budget was measured for ONE profile at a time. Nothing cancels a superseded
 * search either: the daemon's in-flight join keys on the query, so a changed
 * query is a distinct key that runs to completion whatever the client does
 * with the answer. Bounding what is in flight is what keeps an abandoned
 * search's tail short.
 */
export const SESSION_SEARCH_CONCURRENCY = 3;

/**
 * `Promise.all(items.map(fn))` with at most `limit` calls in flight, answering
 * in input order.
 *
 * Rejects like `Promise.all` does; the session fan-out catches per profile
 * before this ever sees a failure.
 */
export async function mapWithLimit<T, R>(
  items: readonly T[],
  limit: number,
  fn: (item: T) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length);
  let next = 0;
  const worker = async (): Promise<void> => {
    while (next < items.length) {
      const index = next;
      next += 1;
      results[index] = await fn(items[index] as T);
    }
  };
  await Promise.all(
    Array.from({ length: Math.max(1, Math.min(limit, items.length)) }, worker),
  );
  return results;
}

/** One conversation, and which profile it was found in. */
export interface ProfiledSession {
  session: AgentSession;
  /**
   * The profile it was listed under; null = the CLI's own default.
   *
   * Carried on the ROW rather than held once for the dialog, and it is
   * load-bearing: an id listed under one profile is not resumable under
   * another, so the import has to be told which store this particular
   * conversation came out of. Before the fan-out there was one answer for the
   * whole list and it could be a prop; now a wrong one opens a chat whose first
   * turn resumes a session that does not exist there.
   */
  configDir: string | null;
}

/** What one profile answered — or, when it could not be asked, why. */
export interface ProfileAnswer {
  configDir: string | null;
  listing: AgentSessionListingDto | null;
  error: string | null;
}

export interface MergedSessions {
  sessions: ProfiledSession[];
  /** Only when NO profile could be asked — see the fold below. */
  unavailableReason: string | null;
  partialReason: string | null;
}

/**
 * Fold every profile's answer into the one list the picker shows.
 *
 * Three rules, each of which is a defect if dropped.
 *
 * **`unavailableReason` survives only when EVERY profile said it.** It is a
 * standing fact about the CLI, so in practice they all agree — but a profile
 * that failed for its own reason (a directory that has since been deleted) must
 * not put "this CLI cannot list its conversations" over a list that is on
 * screen and full of rows.
 *
 * **A profile that could not be READ is named in `partialReason`, not dropped
 * in silence.** A user who moved a profile away sees a shorter list, and
 * without a sentence the missing half is indistinguishable from history they
 * never had.
 *
 * **Rows are deduplicated by id, first profile winning.** Two profiles are two
 * stores and cannot normally hold one id, but the profile list is assembled
 * from paths the user typed and the same directory can be spelled twice.
 */
export function mergeSessionListings(
  answers: readonly ProfileAnswer[],
  limit: number,
): MergedSessions {
  const sessions: ProfiledSession[] = [];
  const seen = new Set<string>();
  const partial = new Set<string>();
  const unreadable: string[] = [];
  const unavailable: string[] = [];
  /** Profiles that answered with a list, rather than with a reason there is none. */
  let usable = 0;

  for (const answer of answers) {
    if (answer.listing === null) {
      unreadable.push(
        answer.configDir === null
          ? 'the default profile'
          : shortenPath(answer.configDir),
      );
      continue;
    }
    if (answer.listing.unavailableReason !== null) {
      unavailable.push(answer.listing.unavailableReason);
    } else {
      usable += 1;
    }
    if (answer.listing.partialReason !== null) {
      partial.add(answer.listing.partialReason);
    }
    for (const session of answer.listing.sessions) {
      if (seen.has(session.id)) {
        continue;
      }
      seen.add(session.id);
      sessions.push({ session, configDir: answer.configDir });
    }
  }

  // Newest first ACROSS profiles, which is the whole point of merging them:
  // interleaved by when the conversation happened, never grouped by which
  // account it happened on — the user is looking for a thread, and they do not
  // remember which subscription they were signed into at the time.
  sessions.sort(
    (a, b) => (b.session.updatedAt ?? 0) - (a.session.updatedAt ?? 0),
  );

  return {
    sessions: sessions.slice(0, limit),
    unavailableReason: usable > 0 ? null : (unavailable[0] ?? null),
    partialReason:
      [
        ...partial,
        unreadable.length === 0
          ? null
          : `Could not read ${unreadable.join(', ')}.`,
      ]
        .filter((reason): reason is string => Boolean(reason))
        .join(' ') || null,
  };
}

/**
 * Every profile to ask about, newest choice first, with the CLI's own default
 * always among them.
 *
 * The default is `null` and is included UNCONDITIONALLY — it is the profile a
 * user has without ever having chosen one, so a list built from their choices
 * alone omits the account most of their history is in. It leads, because a
 * search that has to be capped should cap the profile they most likely mean
 * last.
 *
 * `null` for a CLI that has no config-directory mechanism at all: one profile,
 * which is the CLI's own, and asking under a directory it does not read would
 * be a listing about nothing (and, on the import route, a 400).
 */
export function sessionProfiles(
  current: string | null,
  recent: readonly string[],
  supportsConfigDir: boolean,
): (string | null)[] {
  if (!supportsConfigDir) {
    return [null];
  }
  const profiles: (string | null)[] = [null];
  for (const dir of [current, ...recent]) {
    if (dir !== null && dir !== '' && !profiles.includes(dir)) {
      profiles.push(dir);
    }
  }
  return profiles;
}
