import { describe, expect, it } from 'vitest';

import type { ItemDto as ChatItem } from '../autogenerated';
import { runningShellsByAgent, shellRuns } from './shell-activity';

let seq = 0;
function item(
  kind: ChatItem['kind'],
  payload: unknown,
  nodeId: string | null = null,
): ChatItem {
  seq += 1;
  return {
    id: `i-${seq}`,
    runId: 'run-1',
    nodeId,
    seq,
    kind,
    role: null,
    payload,
    createdAt: '2026-08-24T10:00:00.000Z',
  };
}

/** A claude `Bash` call, as `event-to-item.ts` persists one. */
const bash = (
  id: string,
  command: string,
  extra: Record<string, unknown> = {},
  nodeId: string | null = null,
) =>
  item('tool_call', { id, name: 'Bash', input: { command, ...extra } }, nodeId);

const reply = (id: string, result: unknown, isError = false) =>
  item('tool_result', { id, name: 'Bash', result, isError });

const namedCall = (id: string, name: string, input: unknown) =>
  item('tool_call', { id, name, input });

const namedReply = (
  id: string,
  name: string,
  result: unknown,
  isError = false,
) => item('tool_result', { id, name, result, isError });

describe('shellRuns', () => {
  it('reads a foreground command as running until its reply lands', () => {
    expect(shellRuns([bash('c1', 'pnpm build')])).toEqual([
      expect.objectContaining({
        id: 'c1',
        command: 'pnpm build',
        background: false,
        status: 'running',
      }),
    ]);
    expect(
      shellRuns([bash('c1', 'pnpm build'), reply('c1', 'done')])[0]?.status,
    ).toBe('completed');
  });

  it('reads a reply the CLI marked as an error as a failure', () => {
    expect(
      shellRuns([bash('c1', 'pnpm build'), reply('c1', 'boom', true)])[0]
        ?.status,
    ).toBe('failed');
  });

  it('keeps a BACKGROUND command running after its launch replies', () => {
    // The whole point of the background arm: the reply arrives within the
    // second and the command runs on. Read like a foreground one it would be
    // retired the moment it started.
    const shells = shellRuns([
      bash('c1', 'pnpm dev', { run_in_background: true }),
      reply('c1', 'Command running in background with ID: bash_3. Output…'),
    ]);
    expect(shells[0]).toEqual(
      expect.objectContaining({
        background: true,
        handle: 'bash_3',
        status: 'running',
      }),
    );
  });

  it('settles a background command from the probe that reports it done', () => {
    const shells = shellRuns([
      bash('c1', 'pnpm dev', { run_in_background: true }),
      reply('c1', 'Command running in background with ID: bash_3.'),
      namedCall('c2', 'BashOutput', { bash_id: 'bash_3' }),
      namedReply(
        'c2',
        'BashOutput',
        '<status>failed</status>\n<exit_code>1</exit_code>',
      ),
    ]);
    expect(shells[0]).toEqual(
      expect.objectContaining({ status: 'failed', exitCode: 1 }),
    );
  });

  it('leaves a background command running while its probe says so', () => {
    const shells = shellRuns([
      bash('c1', 'pnpm dev', { run_in_background: true }),
      reply('c1', 'Command running in background with ID: bash_3.'),
      namedCall('c2', 'BashOutput', { bash_id: 'bash_3' }),
      namedReply('c2', 'BashOutput', '<status>running</status>\nReady in 1s'),
    ]);
    expect(shells[0]?.status).toBe('running');
  });

  it('reads a kill as one, and a FAILED kill as no kill at all', () => {
    const kill = (resultIsError: boolean) =>
      shellRuns([
        bash('c1', 'pnpm dev', { run_in_background: true }),
        reply('c1', 'Command running in background with ID: bash_3.'),
        namedCall('c2', 'KillShell', { shell_id: 'bash_3' }),
        namedReply('c2', 'KillShell', 'x', resultIsError),
      ])[0]?.status;
    expect(kill(false)).toBe('killed');
    // A handle the CLI cannot find answers with an error — retiring the row off
    // that would report a shell nothing stopped as stopped.
    expect(kill(true)).toBe('running');
  });

  it('reads a command the CLI detached ITSELF as detached', () => {
    // The agent asked for a foreground command and the CLI backgrounded it —
    // measured wordings: one the user pushed to the background, and one that
    // outran its own timeout. Read off the input flag alone, such a command is
    // retired the instant it is detached, which is the opposite of the truth.
    const shells = shellRuns([
      bash('c1', 'pnpm dev'),
      reply(
        'c1',
        'Command timed out after 2m. Command running in background with ID: bash_7.',
      ),
    ]);
    expect(shells[0]).toEqual(
      expect.objectContaining({
        background: true,
        handle: 'bash_7',
        status: 'running',
      }),
    );
    // …and it is then closed by the same settle any other detached command is.
    expect(
      shellRuns([
        bash('c1', 'pnpm dev'),
        reply('c1', 'Command running in background with ID: bash_7.'),
        item('shell_info', { id: null, workId: 'bash_7' }),
      ])[0]?.status,
    ).toBe('completed');
  });

  it('retires a background shell when the DAEMON says it finished', () => {
    // The one ending no tool call reports. Without this row the command is
    // listed for as long as the turn lasts, and a long turn accumulates every
    // one it ever launched.
    const shells = shellRuns([
      bash('c1', 'pnpm dev', { run_in_background: true }),
      reply('c1', 'Command running in background with ID: bash_3.'),
      item('shell_info', { id: 'c1', workId: 'bash_3' }),
    ]);
    expect(shells[0]?.status).toBe('completed');
  });

  it('matches a settle that names only the CLI’s own work id', () => {
    // One of the two settle channels carries no tool call at all, and a session
    // that resumed after the launch never saw the line that would have paired
    // them — so the handle parsed out of the launch reply is the match.
    const shells = shellRuns([
      bash('c1', 'pnpm dev', { run_in_background: true }),
      reply('c1', 'Command running in background with ID: bash_3.'),
      item('shell_info', { id: null, workId: 'bash_3' }),
    ]);
    expect(shells[0]?.status).toBe('completed');
  });

  it('does not coarsen an outcome a probe already reported', () => {
    // The settle says only that the unit is no longer open. A probe said HOW it
    // ended, with an exit code, and that is the better answer.
    const shells = shellRuns([
      bash('c1', 'pnpm dev', { run_in_background: true }),
      reply('c1', 'Command running in background with ID: bash_3.'),
      namedCall('c2', 'BashOutput', { bash_id: 'bash_3' }),
      namedReply(
        'c2',
        'BashOutput',
        '<status>failed</status>\n<exit_code>1</exit_code>',
      ),
      item('shell_info', { id: 'c1', workId: 'bash_3' }),
    ]);
    expect(shells[0]).toEqual(
      expect.objectContaining({ status: 'failed', exitCode: 1 }),
    );
  });

  it('ignores a settle for a command it has never seen', () => {
    // A transcript paged from the middle: the settle is in the window and the
    // launch is not. Nothing to retire, and nothing to invent either.
    expect(
      shellRuns([item('shell_info', { id: 'gone', workId: 'bash_9' })]),
    ).toEqual([]);
  });

  it('never lists the tools that READ a shell as shells of their own', () => {
    expect(
      shellRuns([
        namedCall('c2', 'BashOutput', { bash_id: 'bash_3' }),
        namedCall('c3', 'KillShell', { shell_id: 'bash_3' }),
      ]),
    ).toEqual([]);
  });

  it("takes an ACP agent's own classification, and its title when it discloses nothing", () => {
    // cursor sends `toolKind` and routinely withholds the arguments; a row
    // named by the call is the honest answer, and dropping it would answer
    // "what is running" with silence on that CLI.
    const shells = shellRuns([
      item('tool_call', {
        id: 'c1',
        name: 'Run terminal command',
        input: {},
        toolKind: 'execute',
      }),
    ]);
    expect(shells).toEqual([
      expect.objectContaining({
        command: 'Run terminal command',
        status: 'running',
      }),
    ]);
  });

  it('ignores tool calls that are not shells', () => {
    expect(
      shellRuns([
        item('tool_call', {
          id: 'c1',
          name: 'Read',
          input: { file_path: '/tmp/x' },
        }),
        item('message', { text: 'hello' }),
      ]),
    ).toEqual([]);
  });
});

describe('runningShellsByAgent', () => {
  it('groups the LIVE shells by the node that started them', () => {
    const byAgent = runningShellsByAgent([
      bash('c1', 'sleep 30', {}, 'node-a'),
      bash('c2', 'echo hi', {}, 'node-b'),
      reply('c2', 'hi'),
      bash('c3', 'sleep 60'),
    ]);
    expect([...byAgent.keys()]).toEqual(['node-a', null]);
    expect(byAgent.get('node-a')?.map((s) => s.command)).toEqual(['sleep 30']);
    expect(byAgent.get(null)?.map((s) => s.command)).toEqual(['sleep 60']);
  });

  it("keeps a DELEGATE's shell, which the task-list fold drops", () => {
    // A delegate's task list is its own bookkeeping; a delegate's `pnpm build`
    // is a process on the user's machine, which is the question this answers.
    const call = bash('c1', 'pnpm build');
    (call.payload as Record<string, unknown>).parentToolUseId = 'sub-1';
    expect(runningShellsByAgent([call]).get(null)?.length).toBe(1);
  });
});
