import { describe, expect, it } from 'vitest';

import type { ItemDto as ChatItem } from '../autogenerated';
import { subagentIdOf } from './subagent-payload';
import {
  foldTaskList,
  readTaskAnnouncement,
  type TaskAnnouncement,
  taskListsByThread,
  taskProgress,
} from './task-payload';

let seq = 0;
function taskItem(payload: unknown): ChatItem {
  seq += 1;
  return {
    id: `i-${seq}`,
    runId: 'run-1',
    nodeId: null,
    seq,
    kind: 'task_list',
    role: null,
    payload,
    createdAt: 'now',
  };
}

const snapshot = (tasks: unknown[], toolCallId: string | null = null) =>
  ({ mode: 'snapshot', tasks, toolCallId }) as unknown;
const patch = (tasks: unknown[], toolCallId: string | null = null) =>
  ({ mode: 'patch', tasks, toolCallId }) as unknown;

const row = (
  id: string,
  title: string | null,
  status: string | null,
  activeForm: string | null = null,
) => ({ id, title, status, activeForm });

describe('readTaskAnnouncement', () => {
  it('reads the shape the daemon writes', () => {
    expect(
      readTaskAnnouncement(
        taskItem(
          snapshot([row('1', 'Read it', 'completed', 'Reading it')], 'tc'),
        ),
      ),
    ).toEqual({
      mode: 'snapshot',
      toolCallId: 'tc',
      tasks: [
        {
          id: '1',
          title: 'Read it',
          status: 'completed',
          activeForm: 'Reading it',
        },
      ],
    });
  });

  it('reads an unrecognised mode as a PATCH — the direction that fails safely', () => {
    // A patch mistaken for a snapshot deletes every task it did not name,
    // turning a list of seven into the two that just moved. The other way round
    // leaves one stale row.
    const announcement = readTaskAnnouncement(
      taskItem({
        mode: 'whole-list-honest',
        tasks: [row('1', 'x', 'pending')],
      }),
    );
    expect(announcement?.mode).toBe('patch');
  });

  it('drops a row with no id and keeps the rest', () => {
    const announcement = readTaskAnnouncement(
      taskItem(snapshot([{ title: 'nameless' }, row('2', 'real', 'pending')])),
    );
    expect(announcement?.tasks).toEqual([
      { id: '2', title: 'real', status: 'pending', activeForm: null },
    ]);
  });

  it('reads an unknown status as unknown rather than as pending', () => {
    const announcement = readTaskAnnouncement(
      taskItem(patch([row('1', null, 'deferred')])),
    );
    expect(announcement?.tasks[0]?.status).toBeNull();
  });

  it('refuses a payload that is not an announcement', () => {
    expect(readTaskAnnouncement(taskItem({ mode: 'patch' }))).toBeNull();
    expect(readTaskAnnouncement(taskItem(null))).toBeNull();
  });
});

describe('foldTaskList', () => {
  const read = (payloads: unknown[]): TaskAnnouncement[] =>
    payloads
      .map((payload) => readTaskAnnouncement(taskItem(payload)))
      .filter((a): a is TaskAnnouncement => a !== null);

  it('keeps the TITLE when a patch moves only the status', () => {
    // The claude shape, and the reason a patch merges per field: `TaskUpdate`
    // sends `{taskId, status}` and no text, so a replacing merge would blank the
    // title of every task the moment it started running.
    const list = foldTaskList(
      read([
        patch([row('1', 'Read the file', 'pending')]),
        patch([row('1', null, 'in_progress')]),
      ]),
    );
    expect(list).toEqual([
      {
        id: '1',
        title: 'Read the file',
        status: 'in_progress',
        activeForm: null,
      },
    ]);
  });

  it('grows the list as a patch names a task it has not seen', () => {
    // Three `TaskCreate` results in a row, which is how a claude list is born.
    const list = foldTaskList(
      read([
        patch([row('1', 'One', 'pending')]),
        patch([row('2', 'Two', 'pending')]),
        patch([row('3', 'Three', 'pending')]),
      ]),
    );
    expect(list.map((task) => task.title)).toEqual(['One', 'Two', 'Three']);
  });

  it('lets a SNAPSHOT remove a task the list still held', () => {
    // The whole point of the distinction: a snapshot is the CLI stating the list,
    // so a task absent from it is gone. A patch must never do this.
    const dropped = foldTaskList(
      read([
        snapshot([row('1', 'One', 'pending'), row('2', 'Two', 'pending')]),
        snapshot([row('1', 'One', 'completed')]),
      ]),
    );
    expect(dropped.map((task) => task.id)).toEqual(['1']);

    const kept = foldTaskList(
      read([
        snapshot([row('1', 'One', 'pending'), row('2', 'Two', 'pending')]),
        patch([row('1', null, 'completed')]),
      ]),
    );
    expect(kept.map((task) => task.id)).toEqual(['1', '2']);
  });

  it('carries a title through a snapshot that repeated none', () => {
    const list = foldTaskList(
      read([
        patch([row('1', 'Read the file', 'pending')]),
        snapshot([row('1', null, 'completed')]),
      ]),
    );
    expect(list[0]?.title).toBe('Read the file');
  });

  it('moves a task even when the new status is unknown', () => {
    // The status IS what a patch is for, so a null takes effect: the CLI moved
    // this row somewhere we cannot name, which is not it standing still.
    const list = foldTaskList(
      read([
        patch([row('1', 'One', 'in_progress')]),
        patch([row('1', null, 'deferred')]),
      ]),
    );
    expect(list[0]?.status).toBeNull();
  });
});

describe('taskProgress', () => {
  it('counts the completed ones and names the running one', () => {
    expect(
      taskProgress([
        { id: '1', title: 'a', status: 'completed', activeForm: null },
        { id: '2', title: 'b', status: 'in_progress', activeForm: 'Doing b' },
        { id: '3', title: 'c', status: 'pending', activeForm: null },
      ]),
    ).toEqual({
      done: 1,
      total: 3,
      current: {
        id: '2',
        title: 'b',
        status: 'in_progress',
        activeForm: 'Doing b',
      },
    });
  });

  it('names NO current task when several are running at once', () => {
    // Calling the first of them "the current one" would state a sequence the
    // CLI never gave.
    const progress = taskProgress([
      { id: '1', title: 'a', status: 'in_progress', activeForm: null },
      { id: '2', title: 'b', status: 'in_progress', activeForm: null },
    ]);
    expect(progress.current).toBeNull();
    expect(progress.total).toBe(2);
  });
});

describe('taskListsByThread', () => {
  it('keeps a DELEGATE’s list apart from the main agent’s', () => {
    // Both CLIs number tasks from 1, so a single fold would make task `1` mean
    // two different things and each thread would overwrite the other's status.
    const delegated = (payload: Record<string, unknown>): ChatItem =>
      taskItem({ ...payload, parentToolUseId: 'toolu_parent' });
    const lists = taskListsByThread(
      [
        taskItem(snapshot([row('1', 'main task', 'in_progress')])),
        delegated({
          mode: 'snapshot',
          tasks: [row('1', 'delegate task', 'completed')],
          toolCallId: null,
        }),
      ],
      subagentIdOf,
    );
    expect(lists.get(null)).toEqual([
      { id: '1', title: 'main task', status: 'in_progress', activeForm: null },
    ]);
    expect(lists.get('toolu_parent')).toEqual([
      {
        id: '1',
        title: 'delegate task',
        status: 'completed',
        activeForm: null,
      },
    ]);
  });

  it('ignores every other item kind', () => {
    const other: ChatItem = { ...taskItem({}), kind: 'message' };
    expect(taskListsByThread([other], subagentIdOf).size).toBe(0);
  });
});
