import type { ItemDto as ChatItem } from '../autogenerated';
import { CHAT_LIVE_KEY, type LiveState } from './live-text';
import {
  mergeSubagentDeclarations,
  readSubagentDeclaration,
  type SubagentDeclaration,
  subagentIdOf,
} from './subagent-payload';
// The PURE payload module, deliberately not `transcript-item.tsx` (which
// re-exports these): reaching into the component module from here is what
// closed the `agent-activity → transcript-groups → transcript-item →
// live-row → agent-activity` import cycle.
import type { AgentTaskRow, TaskAnnouncement } from './task-payload';
import { foldTaskList, readTaskAnnouncement } from './task-payload';
import {
  AGENT_TOOLS,
  toolKindOf,
  type ToolOperation,
  toolOperationOf,
} from './tool-kind';
import { resultDiffsOf, toolResultText } from './tool-render';
import { payloadString } from './transcript-payload';

/**
 * The open-group bucket an item belongs to: its node AND its originating
 * thread.
 *
 * A node id and a sub-agent id are opaque strings from different namespaces —
 * a node id is authored by hand in a workflow YAML — so they are joined by NUL
 * rather than concatenated. Without a separator, node `a` with sub-agent `b`
 * and node `ab` with none would share a bucket, and any PRINTABLE separator is
 * one a hand-written node id could itself contain.
 */
function groupKey(item: ChatItem): string {
  return `${item.nodeId ?? ''}\u0000${subagentIdOf(item) ?? ''}`;
}

/**
 * The renderer's own agent-call tools ride the transcript as raw
 * tool_call/tool_result items too, but the dedicated call kinds
 * (call_started/call_result/call_question/call_answer/await_collected)
 * already tell that story in a readable form — the raw envelope JSON rows
 * are pure duplication, so they are hidden from the transcript.
 */
const GENIRO_TOOL_PREFIX = 'mcp__geniro__';

/** One tool invocation: its call and (once it arrived) its paired result. */
export interface ToolPair {
  call: ChatItem;
  result: ChatItem | null;
}

/** A run of tool calls collapsed into one expandable transcript row. */
export interface ToolGroupEntry {
  type: 'tools';
  /** Stable identity for React keys and expansion state: the first call's id. */
  id: string;
  nodeId: string | null;
  /**
   * The sub-agent whose work this is — the id of the tool call that started
   * it — or null for the agent's own thread.
   *
   * A group never mixes the two. A CLI running sub-agents emits their tool
   * calls on the SAME stream as its own, so folding by node alone produced one
   * interleaved sequence in which each thread's chatter closed the other's
   * group: several sub-agents working at once turned into a long flat run of
   * single-call rows with nothing saying where any of them came from.
   */
  parentToolUseId: string | null;
  /**
   * A turn ended after this group — so whatever result was coming has come.
   *
   * An unpaired call means "still running" only while its turn is open. Once
   * the turn is over, a missing `tool_result` is a result that never arrived,
   * and a spinner over it claims work that stopped long ago. (A result that
   * lands between turns IS persisted now, along with its call — but it takes a
   * fresh seq, so it appears later in the transcript rather than inside this
   * closed group.) That is the reported bug: a chat whose
   * header read `completed` with a sub-agent row working forever.
   *
   * Per-GROUP rather than per-run, and that distinction is the point: the run
   * reads `running` again the moment the user sends another message, so a
   * run-level flag let the same stale group start spinning through every
   * later turn.
   */
  closed: boolean;
  pairs: ToolPair[];
}

export interface ItemEntry {
  type: 'item';
  item: ChatItem;
}

/**
 * One agent-to-agent call folded into a single nested block: the
 * call_started row becomes the header (callee, mode, ask, LIVE status) and
 * every item of the callee's sub-turn renders inside — so two parallel
 * callees never interleave their messages in the main flow.
 */
export interface CallBlockEntry {
  type: 'call-block';
  /** Stable identity (the call_started item's id) for keys and expansion. */
  id: string;
  /** The call_started item's timestamp — the block's metadata time. */
  createdAt: string;
  callId: string;
  calleeNodeId: string | null;
  /** The caller node the call_started row was attributed to. */
  callerNodeId: string | null;
  mode: string | null;
  /** The caller's ask — the block's REQUEST. */
  message: string | null;
  /** Sub-turn lifecycle, from the callId-tagged status items. */
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
  /**
   * The callee's final message once the sub-turn COMPLETED — the block's
   * RESULT, pulled out of {@link entries} (geniro-style request → result
   * framing). Null while running or when the sub-turn did not complete.
   */
  result: string | null;
  entries: TranscriptEntry[];
}

/**
 * One agent's contiguous run of work — geniro-style: the agent's messages,
 * tool groups and communication cards folded into ONE avatar-framed block,
 * so a turn reads top-to-bottom as a single story.
 */
export interface TurnBlockEntry {
  type: 'turn-block';
  /** Stable identity: the first inner entry's identity. */
  id: string;
  createdAt: string;
  /** Owner node; null = the 1:1 chat's agent. */
  nodeId: string | null;
  /**
   * The sub-agent whose work this block is, or null for the main thread.
   *
   * The fold already SPLITS on this, so it is carried rather than re-derived.
   * Without it the two kinds of block render identically, and a delegate's run
   * of near-identical openers reads as the main agent's own words — which is
   * how the defect was reported. The per-row caption in `TranscriptItem`
   * cannot cover this: `TurnBlock` renders message rows itself and never
   * reaches it.
   */
  subagentId: string | null;
  entries: TranscriptEntry[];
}

/**
 * One background sub-agent folded into a single collapsed block: everything
 * the delegate produced, nested under the tool call that launched it.
 *
 * The rows were already SPLIT per sub-agent ({@link groupKey} folds on
 * `parentToolUseId`), but they rendered as top-level siblings of the main
 * thread — a delegate's whole run of work sitting in the conversation as
 * though the main agent had said it. This block is the enclosure: one row in
 * the flow, closed by default, that opens into the delegate's own thread.
 *
 * Deliberately parallel to {@link CallBlockEntry}, and the two are different
 * things: a call block is one agent asking ANOTHER NODE of the workflow to
 * work (the geniro call runtime), while this is one CLI's own in-process
 * delegate. They share the card and nothing else — a call has a callee node
 * and a mode; a sub-agent has only the tool call that spawned it.
 */
export interface SubagentBlockEntry {
  type: 'subagent-block';
  /**
   * Stable identity for keys and expansion state: the launching tool call's
   * id, which is exactly the `parentToolUseId` every row inside carries.
   */
  id: string;
  createdAt: string;
  /** The node that ran the delegation; null = the 1:1 chat's agent. */
  nodeId: string | null;
  /** What the delegate was asked to BE — the Task call's `subagent_type`. */
  kind: string | null;
  /** The Task call's one-line `description`. */
  label: string | null;
  /** The Task call's `prompt` — the block's REQUEST. */
  prompt: string | null;
  /**
   * The launching tool call returned — the ONLY signal that the delegate
   * finished, since there is no per-sub-agent status item on the wire.
   *
   * Deliberately separate from {@link result}: a tool can return with no text
   * at all, and folding the two let a missing body read as "still running"
   * while stringifying it printed the four characters `null` into the result
   * panel as though the delegate had said them.
   */
  returned: boolean;
  /**
   * The CLI's own word on whether this delegate is still working, outranking
   * {@link returned} while it is `true`.
   *
   * `returned` is normally the end of a delegate, and for one the agent WAITS
   * for it is. For a fire-and-forget delegate the launching call returns in
   * under a second and the delegate runs on — measured on claude 2.1.232, three
   * of them still working 50s after their blocks read `done` — so the block
   * needs a signal that survives the return. `null` is "the CLI said nothing",
   * which is every agent but claude's background tasks, and leaves the old
   * reading untouched.
   */
  backgroundOpen: boolean | null;
  /**
   * That result was an error — `isError` on the `tool_result` payload, which
   * `apps/daemon/src/v1/agents/utils/event-to-item.ts` persists verbatim.
   */
  failed: boolean;
  /** The launching tool call's result TEXT, or null when it carried none. */
  result: string | null;
  /** The model the delegate ran, when the CLI named one. */
  model: string | null;
  /** How long it took, when the CLI reported it. */
  durationMs: number | null;
  /**
   * Why this block opens onto no conversation — the daemon's own sentence, from
   * the CLI whose delegate this is.
   *
   * Non-null only for a CLI that announces a delegation and streams none of the
   * work inside it (cursor). Absent-and-empty and present-with-a-reason are
   * different states and must read differently: the first is a delegate that has
   * not spoken YET, the second one whose words were never going to arrive.
   */
  stepsUnavailableReason: string | null;
  /**
   * A turn ended after this block's last row — so whatever was coming has
   * come. Same rule, and the same reason, as {@link ToolGroupEntry.closed}: a
   * delegate with no result is only evidence of work in flight while its turn
   * could still be running, and a spinner past that claims work that stopped.
   */
  closed: boolean;
  /**
   * When this delegate last put anything on screen (ms), or null if it never
   * has — the newest row inside the block, else its own launch.
   *
   * Read against the moment the RUN settled, which is a different question from
   * {@link closed} and cannot be answered by it: `closed` is a seq comparison
   * against a turn-end ITEM, and the paths that settle a run without writing
   * one (a cancel) or that settle it wrongly (a stale `completed`) leave no seq
   * to compare with. A timestamp is what makes "this delegate has spoken since"
   * answerable at all.
   */
  lastRowAt: number | null;
  entries: TranscriptEntry[];
}

/**
 * The agent's own task list, at the point in the conversation where it last
 * moved — one card standing in for a contiguous run of announcements.
 *
 * A run rather than a row per announcement, because working a list is chatty:
 * the measured cursor turn sent four announcements for a three-item list and
 * claude sends one per create and one per status change, so a row each would
 * bury the conversation under near-identical checklists. One card per run reads
 * as "here is where the list stood after that burst of work".
 *
 * {@link tasks} is folded from EVERY announcement of this thread from the
 * beginning, not just the ones in this run — two of the three shapes on the wire
 * are patches, so a run holding one `TaskUpdate` knows about exactly one task
 * and the list is only ever the fold.
 */
export interface TaskListEntry {
  type: 'task-list';
  /** Stable identity for keys: the first announcement in the run. */
  id: string;
  createdAt: string;
  /** The highest `seq` in the run — for the readers that order nested work. */
  seq: number;
  nodeId: string | null;
  /** The thread that owns the list: a delegate's is its own. */
  parentToolUseId: string | null;
  /** The list as it stood after the last announcement in this run. */
  tasks: AgentTaskRow[];
  /**
   * This is the thread's LAST card — the list as it stands now, rather than a
   * step on the way there.
   *
   * Load-bearing for one thing only: whether an `in_progress` row may spin. An
   * earlier card is a historical snapshot, and every one of them animating its
   * own in-progress task meant a transcript of three spinners for a job with one
   * task running — none of which was true any more.
   */
  latest: boolean;
}

export type TranscriptEntry =
  | ItemEntry
  | ToolGroupEntry
  | CallBlockEntry
  | TurnBlockEntry
  | SubagentBlockEntry
  | TaskListEntry;

/** Sentinel: entry has no agent owner and breaks a turn block. */
const NO_OWNER = Symbol('no-owner');

/**
 * The node AND originating thread an entry belongs to — the same pairing
 * {@link groupKey} folds tool groups by. `nodeId` alone is not enough: a
 * sub-agent's rows carry the MAIN agent's nodeId, so keying on it alone
 * folded a delegate's words into the main agent's block under its own
 * SenderRow.
 */
interface EntryOwner {
  nodeId: string | null;
  subagentId: string | null;
}

function sameOwner(a: EntryOwner, b: EntryOwner): boolean {
  return a.nodeId === b.nodeId && a.subagentId === b.subagentId;
}

/** The agent a top-level entry belongs to (NO_OWNER breaks the block). */
function ownerOf(entry: TranscriptEntry): EntryOwner | typeof NO_OWNER {
  if (entry.type === 'tools') {
    return { nodeId: entry.nodeId, subagentId: entry.parentToolUseId };
  }
  if (entry.type === 'call-block') {
    return { nodeId: entry.callerNodeId, subagentId: null };
  }
  if (entry.type === 'subagent-block') {
    // The DELEGATING agent's, not the delegate's — the block belongs in the
    // turn where the delegation happened, which is what puts it beside the
    // tool row that launched it. Its own rows are already inside it.
    return { nodeId: entry.nodeId, subagentId: null };
  }
  if (entry.type === 'turn-block') {
    return { nodeId: entry.nodeId, subagentId: null };
  }
  if (entry.type === 'task-list') {
    return { nodeId: entry.nodeId, subagentId: entry.parentToolUseId };
  }
  const item = entry.item;
  if (item.kind === 'message' && item.role !== 'user') {
    return { nodeId: item.nodeId, subagentId: subagentIdOf(item) };
  }
  if (
    item.kind === 'reasoning' ||
    item.kind === 'error' ||
    item.kind === 'system'
  ) {
    return { nodeId: item.nodeId, subagentId: subagentIdOf(item) };
  }
  return NO_OWNER;
}

function entryId(entry: TranscriptEntry): string {
  return entry.type === 'item' ? entry.item.id : entry.id;
}

function entryCreatedAt(entry: TranscriptEntry): string {
  if (entry.type === 'item') {
    return entry.item.createdAt;
  }
  if (entry.type === 'tools') {
    return entry.pairs[0]?.call.createdAt ?? '';
  }
  return entry.createdAt;
}

/**
 * Fold consecutive same-agent entries into turn blocks. Applied by the
 * MAIN flow only (a communication card's inner content is already one
 * story); user messages, notes and approval cards break a block.
 */
export function buildTurnBlocks(
  entries: readonly TranscriptEntry[],
): TranscriptEntry[] {
  const out: TranscriptEntry[] = [];
  let open: TurnBlockEntry | null = null;
  let openOwner: EntryOwner | null = null;
  for (const entry of entries) {
    const owner = ownerOf(entry);
    if (owner === NO_OWNER) {
      open = null;
      openOwner = null;
      out.push(entry);
      continue;
    }
    if (open && openOwner && sameOwner(openOwner, owner)) {
      open.entries.push(entry);
      continue;
    }
    open = {
      type: 'turn-block',
      id: entryId(entry),
      createdAt: entryCreatedAt(entry),
      nodeId: owner.nodeId,
      subagentId: owner.subagentId,
      entries: [entry],
    };
    openOwner = owner;
    out.push(open);
  }
  return out;
}

/**
 * Kinds that stay in the MAIN flow even when a delegate produced them — the
 * same carve-out {@link UNCLAIMABLE_KINDS} makes for call blocks, and for the
 * same reason: a permission card folded into a collapsed block is a card
 * nobody can see they have to answer.
 */
const SUBAGENT_UNCLAIMABLE_KINDS = new Set<ChatItem['kind']>([
  'approval_request',
  'approval_verdict',
]);

/** The sub-agent an already-folded entry belongs to, or null for the main thread. */
function subagentOwnerOf(entry: TranscriptEntry): string | null {
  if (entry.type === 'tools') {
    return entry.parentToolUseId;
  }
  if (entry.type === 'item') {
    return SUBAGENT_UNCLAIMABLE_KINDS.has(entry.item.kind)
      ? null
      : subagentIdOf(entry.item);
  }
  if (entry.type === 'turn-block') {
    return entry.subagentId;
  }
  if (entry.type === 'task-list') {
    return entry.parentToolUseId;
  }
  // A call block is a NODE-to-node call and a sub-agent block is already an
  // enclosure — neither is a delegate's row needing one.
  return null;
}

/** The node an already-folded entry belongs to. */
function entryNodeId(entry: TranscriptEntry): string | null {
  if (entry.type === 'item') {
    return entry.item.nodeId;
  }
  if (entry.type === 'call-block') {
    return entry.callerNodeId;
  }
  return entry.nodeId;
}

/** The highest `seq` any row inside these entries carries (0 when empty). */
function maxSeqOf(list: readonly TranscriptEntry[]): number {
  let max = 0;
  for (const entry of list) {
    if (entry.type === 'item') {
      max = Math.max(max, entry.item.seq);
      continue;
    }
    if (entry.type === 'tools') {
      for (const pair of entry.pairs) {
        max = Math.max(max, pair.result?.seq ?? pair.call.seq);
      }
      continue;
    }
    if (entry.type === 'task-list') {
      max = Math.max(max, entry.seq);
      continue;
    }
    max = Math.max(max, maxSeqOf(entry.entries));
  }
  return max;
}

/**
 * When a run stopped, for the readers that must ask whether a piece of nested
 * work has spoken SINCE.
 *
 * Three states, not two, because a settle with no readable moment is not the
 * same as no settle. Folding them lost the FACT the moment was meant to refine:
 * an unparseable `updatedAt` silently re-enabled every spinner on a cancelled
 * run. `'unknown'` keeps the old, conservative reading — the run is over and
 * everything unreturned is stopped — while a number allows the exception.
 */
export type RunSettleAt = number | 'unknown' | null;

/** The newest `createdAt` (ms) any row inside these entries carries. */
function lastRowAtOf(list: readonly TranscriptEntry[]): number | null {
  let latest: number | null = null;
  const consider = (createdAt: string): void => {
    const at = Date.parse(createdAt);
    if (Number.isFinite(at) && (latest === null || at > latest)) {
      latest = at;
    }
  };
  for (const entry of list) {
    if (entry.type === 'item') {
      consider(entry.item.createdAt);
      continue;
    }
    if (entry.type === 'tools') {
      for (const pair of entry.pairs) {
        consider(pair.result?.createdAt ?? pair.call.createdAt);
      }
      continue;
    }
    if (entry.type === 'task-list') {
      consider(entry.createdAt);
      continue;
    }
    const nested = lastRowAtOf(entry.entries);
    if (nested !== null && (latest === null || nested > latest)) {
      latest = nested;
    }
  }
  return latest;
}

/**
 * Where a sub-agent's work stands — the ONE derivation, shared by the block
 * that renders it, the panel that lists it, and the run badge that reports it,
 * so the three can never disagree about whether a delegate is still working.
 *
 * `stopped` is the honest reading of a delegate whose turn ended without its
 * tool ever returning: it is not running (nothing more is coming) and it did
 * not complete (there is no result), and calling it either would be a claim
 * the transcript does not support.
 *
 * `runSettledAt` is WHEN the run settled — see {@link RunSettleAt}, and
 * {@link RunSettledContext} for why the moment and not merely the fact.
 */
export function subagentBlockStatus(
  block: SubagentBlockEntry,
  runSettledAt: RunSettleAt = null,
): 'running' | 'completed' | 'failed' | 'stopped' {
  if (block.failed) {
    return 'failed';
  }
  // Ahead of `returned`, and ONLY when the CLI has actually said so: a delegate
  // nobody is waiting for has its launching call answered immediately, so the
  // return says the delegation was accepted rather than that the work is over.
  // Ranked below `failed` because a delegate that errored is finished whatever
  // its lifecycle channel last announced.
  if (block.backgroundOpen === true) {
    return 'running';
  }
  if (block.returned) {
    return 'completed';
  }
  // Two independent things end a delegate that never returned, and neither
  // subsumes the other — the same pairing `ToolGroupEntry.closed` documents.
  // `closed` is its own turn ending; the run settling is the whole run
  // stopping, which on the cancel path writes no turn-end item at all. Reading
  // `closed` alone left a cancelled run's delegate spinning "is working…"
  // forever.
  //
  // But a run settling only ends a delegate that has said nothing SINCE. The
  // reported defect: a delegate rendered `stopped` while its rows were still
  // landing, because the run row had settled and that alone painted every
  // unreturned block in the chat at once. Measured on the author's own
  // `geniro.db` — 1346 delegate rows arrived in run `f42bfe2d` after the item
  // that settled it. Whatever the row says, a delegate that has spoken since is
  // working: the transcript is the evidence and the status is the claim, so
  // where they disagree the evidence wins.
  const endedByRun =
    runSettledAt !== null &&
    (runSettledAt === 'unknown' ||
      block.lastRowAt === null ||
      block.lastRowAt <= runSettledAt);
  return block.closed || endedByRun ? 'stopped' : 'running';
}

/**
 * What to call a delegate: its own description, else its type, else generic.
 *
 * One derivation, beside the status one and for the same reason — the block
 * header, the panel row and the dialog title must never disagree about a
 * delegate's name.
 */
export function subagentTitle(block: SubagentBlockEntry): string {
  return block.label ?? block.kind ?? 'sub-agent';
}

/**
 * How many tool invocations these entries hold, at any depth.
 *
 * One recursion, shared by both block kinds: a shallow count and a deep count
 * of the same "N tools" label meant different things per card.
 */
export function countTools(entries: readonly TranscriptEntry[]): number {
  return entries.reduce((sum, entry) => {
    if (entry.type === 'tools') {
      return sum + entry.pairs.length;
    }
    if (entry.type === 'item' || entry.type === 'task-list') {
      // A task card holds no tool invocations: the calls that produced it are
      // hidden BY it, and counting them would report work with no row to open.
      return sum;
    }
    return sum + countTools(entry.entries);
  }, 0);
}

/** Every sub-agent block in a folded transcript, at any depth. */
export function collectSubagentBlocks(
  entries: readonly TranscriptEntry[],
): SubagentBlockEntry[] {
  const out: SubagentBlockEntry[] = [];
  const walk = (list: readonly TranscriptEntry[]): void => {
    for (const entry of list) {
      if (entry.type === 'subagent-block') {
        out.push(entry);
        continue;
      }
      if (entry.type === 'turn-block' || entry.type === 'call-block') {
        walk(entry.entries);
      }
    }
  };
  walk(entries);
  return out;
}

/** One sub-agent block under assembly. */
interface SubagentLaunch {
  call: ChatItem;
  result: ChatItem | null;
}

/**
 * Read one string field off a tool call's `input` object.
 *
 * TWIN PARSER: the keys read through this — `subagent_type`, `description`,
 * `prompt` — are claude's own Task-tool argument schema, which reaches the
 * renderer inside a `tool_call` payload's `input` and so carries no generated
 * type (`apps/daemon/src/v1/agents/utils/event-to-item.ts` forwards
 * `event.input` verbatim; the shape originates in
 * `apps/daemon/src/v1/agents/adapters/claude/`). If that CLI renames one of
 * them, it must be renamed here, and vice versa — nothing type-checks the two
 * against each other. Every key is read defensively, so a rename degrades to
 * an unlabelled block rather than a crash.
 */
function inputString(call: ChatItem | undefined, key: string): string | null {
  const input = (call?.payload as { input?: unknown } | null)?.input;
  if (typeof input !== 'object' || input === null) {
    return null;
  }
  const value = (input as Record<string, unknown>)[key];
  return typeof value === 'string' && value !== '' ? value : null;
}

/**
 * Fold every background sub-agent's rows into one {@link SubagentBlockEntry},
 * placed where that delegate's FIRST row appeared — which is directly after
 * the tool call that launched it.
 *
 * Runs BETWEEN {@link groupTranscript} and {@link buildTurnBlocks}: the former
 * has already split each delegate's tool runs onto their own groups, and the
 * latter must see the finished block as a single entry of the DELEGATING
 * agent's turn rather than fold the delegate's loose rows into it.
 *
 * The launching `tool_call` supplies the block's identity and its request; its
 * paired `tool_result` supplies the result and is the only "the delegate
 * finished" signal on the wire. Rows whose launcher is missing entirely (a
 * transcript replayed from mid-run, a `Task` call the fold dropped) still get
 * a block — an unlabelled enclosure beats spilling a delegate's work back into
 * the main conversation, which is the defect this whole fold exists to fix.
 *
 * A launch is recognised TWO ways, because CLIs disclose a delegation
 * differently and neither reading covers the other:
 * - by the tool's NAME ({@link AGENT_TOOLS}), whose own arguments carry the
 *   description, the prompt and the type — claude's `Task`;
 * - by a `subagent_info` row the DAEMON wrote, which names the launching tool
 *   call explicitly — for a CLI whose delegation frame carries no usable name
 *   and whose brief arrives later on its own channel (cursor over ACP, where the
 *   call is titled `Task: Subagent task` and its input holds only `_toolName`).
 *
 * The second is why nothing here needs a second CLI's tool-name spellings: which
 * calls launched delegates is the adapter layer's fact, and it is stated on the
 * wire rather than pattern-matched at this end.
 *
 * One level deep, like the other blocks: a claude sub-agent is a leaf and
 * cannot itself delegate, so no block nests inside another.
 */
export function buildSubagentBlocks(
  entries: readonly TranscriptEntry[],
  items: readonly ChatItem[],
): TranscriptEntry[] {
  // Merged rather than taken: a CLI announces the same delegate once at launch
  // (anchor only) and again with its brief, so the last non-null field wins.
  const declarations = new Map<string, SubagentDeclaration>();
  for (const item of items) {
    if (item.kind !== 'subagent_info') {
      continue;
    }
    const declaration = readSubagentDeclaration(item);
    if (declaration === null) {
      continue;
    }
    const previous = declarations.get(declaration.id);
    declarations.set(
      declaration.id,
      previous === undefined
        ? declaration
        : mergeSubagentDeclarations(previous, declaration),
    );
  }
  const launches = new Map<string, SubagentLaunch>();
  for (const item of items) {
    if (item.kind !== 'tool_call') {
      continue;
    }
    const id = payloadString(item.payload, 'id');
    const name = payloadString(item.payload, 'name') ?? '';
    if (id && (AGENT_TOOLS.has(name) || declarations.has(id))) {
      launches.set(id, { call: item, result: null });
    }
  }
  for (const item of items) {
    if (item.kind !== 'tool_result') {
      continue;
    }
    const id = payloadString(item.payload, 'id');
    const launch = id ? launches.get(id) : undefined;
    if (launch) {
      launch.result = item;
    }
  }

  const out: TranscriptEntry[] = [];
  const blocks = new Map<string, SubagentBlockEntry>();
  /**
   * The `seq` the delegation was ISSUED at, per block.
   *
   * Only load-bearing while a block has no rows of its own: `maxSeqOf([])` is
   * 0, so without an anchor ANY earlier turn-end of the delegating node reads
   * as "this delegate's turn is over" and a Task call the CLI has not yet
   * produced a single row for renders `stopped` the instant it appears.
   */
  const anchorSeq = new Map<string, number>();
  const openBlock = (
    subagentId: string,
    /** Where to read identity from when the launching call is missing. */
    fallback: TranscriptEntry,
  ): SubagentBlockEntry => {
    const existing = blocks.get(subagentId);
    if (existing) {
      return existing;
    }
    const launch = launches.get(subagentId);
    const payload = launch?.result?.payload as {
      result?: unknown;
      isError?: unknown;
    } | null;
    const body = payload?.result;
    // What the DAEMON said about this delegate, when its CLI announces one apart
    // from the launching call. Read as a FALLBACK per field rather than as an
    // alternative source: claude's Task arguments are richer and already carry
    // three of these, so the declaration fills only what the call did not say.
    const declared = declarations.get(subagentId) ?? null;
    const block: SubagentBlockEntry = {
      type: 'subagent-block',
      id: subagentId,
      // A ternary, not `??`: every 1:1 chat row carries `nodeId: null`
      // legitimately, so coalescing would fall through to the first row's
      // node whenever the launcher IS the chat agent.
      createdAt: launch ? launch.call.createdAt : entryCreatedAt(fallback),
      nodeId: launch ? launch.call.nodeId : entryNodeId(fallback),
      kind:
        inputString(launch?.call, 'subagent_type') ?? declared?.kind ?? null,
      label:
        inputString(launch?.call, 'description') ?? declared?.label ?? null,
      prompt: inputString(launch?.call, 'prompt') ?? declared?.prompt ?? null,
      model: declared?.model ?? null,
      durationMs: declared?.durationMs ?? null,
      stepsUnavailableReason: declared?.stepsUnavailableReason ?? null,
      backgroundOpen: declared?.backgroundOpen ?? null,
      returned: launch?.result != null,
      failed: payload?.isError === true,
      // Only stringify a body that EXISTS. `toolResultText(null)` returns
      // the four characters `null`, which the result panel then framed as
      // the delegate's own answer.
      result: body == null ? null : toolResultText(body),
      closed: false,
      lastRowAt: null,
      entries: [],
    };
    if (launch) {
      anchorSeq.set(subagentId, launch.result?.seq ?? launch.call.seq);
    }
    blocks.set(subagentId, block);
    out.push(block);
    return block;
  };

  for (const entry of entries) {
    const subagentId = subagentOwnerOf(entry);
    if (subagentId !== null) {
      openBlock(subagentId, entry).entries.push(entry);
      continue;
    }
    // A MAIN-thread tool group is where the delegations were issued. The
    // launching `Task` pair is pulled OUT of it and rendered as the block it
    // opened: the block already says a delegate was started, who it is and
    // how it ended, so leaving the pair in the group produced a second,
    // poorer telling of it directly above ("Delegated to 5 subagents").
    if (entry.type === 'tools') {
      const kept: ToolPair[] = [];
      const launched: string[] = [];
      for (const pair of entry.pairs) {
        const id = payloadString(pair.call.payload, 'id');
        if (id !== null && launches.has(id)) {
          launched.push(id);
          continue;
        }
        kept.push(pair);
      }
      if (kept.length > 0) {
        // `id` is carried over UNCHANGED even when the pair it names was the
        // one just stripped. It is a React key, and re-deriving it from the
        // first surviving pair would change it the moment a delegation is
        // followed by real work in the same group — remounting the row and
        // discarding whatever the reader had expanded.
        out.push({ ...entry, pairs: kept });
      }
      // AFTER the group, so a turn that both worked and delegated still reads
      // in the order it happened.
      for (const id of launched) {
        openBlock(id, entry);
      }
      continue;
    }
    out.push(entry);
  }
  if (blocks.size === 0) {
    return out;
  }

  const turnEnds = items.filter((item) => TURN_END_KINDS.has(item.kind));
  for (const block of blocks.values()) {
    // Scoped to the delegating NODE, not the whole run. Under graph fan-out
    // several nodes settle independently, so an unscoped read let node A's
    // `turn_complete` mark node B's still-working delegate `stopped` — the
    // failure showing up exactly when several agents run at once, which is
    // when this feature matters most.
    const lastSeq = Math.max(
      maxSeqOf(block.entries),
      anchorSeq.get(block.id) ?? 0,
    );
    block.closed = turnEnds.some(
      (item) => item.nodeId === block.nodeId && item.seq > lastSeq,
    );
    // Taken BEFORE the fold, while the rows are still flat. Falls back to the
    // LAUNCH when the delegate has produced nothing yet: a delegation issued
    // after the run settled is itself evidence of life, and reading null there
    // would call a delegate that started one second ago `stopped`.
    const launchedAt = Date.parse(block.createdAt);
    block.lastRowAt =
      lastRowAtOf(block.entries) ??
      (Number.isFinite(launchedAt) ? launchedAt : null);
    // Folded so the nested thread reads exactly like the main flow does.
    block.entries = buildTurnBlocks(block.entries);
  }
  return out;
}

/**
 * Caller-attributed rows of the SAME call (the parked question, its answer,
 * the settle envelope) — everything about a sub-agent call belongs inside
 * its block, so these claim into the bucket by callId alone (their nodeId
 * is the CALLER's).
 */
const CALL_FOLLOWUP_KINDS = new Set<ChatItem['kind']>([
  'call_question',
  'call_answer',
  'call_result',
]);

/**
 * Kinds that must stay in the MAIN flow even when callId-tagged: the block
 * anchor itself, the broker's pickup note (renders as nothing), and
 * approval requests/verdicts — a pending card hidden inside a block's flow
 * could never be answered.
 */
const UNCLAIMABLE_KINDS = new Set<ChatItem['kind']>([
  'call_started',
  'await_collected',
  'approval_request',
  'approval_verdict',
]);

const BLOCK_STATUSES = new Set(['running', 'completed', 'failed', 'cancelled']);

/** A pending agent-call block under assembly (one per call_started). */
interface CallShell {
  started: ChatItem;
  calleeNodeId: string | null;
  bucket: ChatItem[];
}

/**
 * Fold a transcript into render entries: agent calls collapse into nested
 * call blocks, tool calls collapse into per-node groups (Claude/Cursor-style
 * "used N tools" rows), everything else stays a plain item entry.
 *
 * Call-block rules:
 * - a `call_started` opens a block; every item TAGGED with that callId and
 *   attributed to the callee node folds inside it (its status items drive
 *   the block's live status instead of rendering as rows — merging the old
 *   redundant "call → B" + "B started" pair into one block header).
 * - the caller-attributed rows about the call (question/answer/settle)
 *   claim in too — the WHOLE exchange lives in the block; only the anchor
 *   and approval requests/verdicts stay out (see {@link UNCLAIMABLE_KINDS}),
 *   and untagged items (legacy transcripts) keep the flat flow.
 *
 * Tool-grouping rules:
 * - a `tool_call` joins its node's OPEN group (or opens one); any other
 *   rendered kind from the SAME node closes that node's group — another
 *   node's interleaved rows do not, so a parallel branch doesn't shred the
 *   caller's tool run into fragments.
 * - a `tool_result` attaches to its call by payload id wherever that call
 *   lives (the pairing survives a closed group); an orphan result (no known
 *   call) stays a plain item entry.
 * - `mcp__geniro__*` tool calls and their results are dropped entirely (see
 *   {@link GENIRO_TOOL_PREFIX}).
 */
export function groupTranscript(items: readonly ChatItem[]): TranscriptEntry[] {
  // Pass 1 — collect the call shells and claim each callee sub-turn's items.
  const shells = new Map<string, CallShell>();
  for (const item of items) {
    if (item.kind !== 'call_started') {
      continue;
    }
    const callId = payloadString(item.payload, 'callId');
    if (callId && !shells.has(callId)) {
      shells.set(callId, {
        started: item,
        calleeNodeId: payloadString(item.payload, 'calleeNodeId'),
        bucket: [],
      });
    }
  }
  const claimed = new Set<string>();
  if (shells.size > 0) {
    for (const item of items) {
      if (UNCLAIMABLE_KINDS.has(item.kind)) {
        continue;
      }
      const callId = payloadString(item.payload, 'callId');
      const shell = callId ? shells.get(callId) : undefined;
      if (!shell) {
        continue;
      }
      // The callee's own streamed items claim by callId + callee nodeId; the
      // caller-attributed rows ABOUT this call (question/answer/settle)
      // claim by callId alone — the whole exchange lives in the block.
      if (
        CALL_FOLLOWUP_KINDS.has(item.kind) ||
        (item.nodeId !== null && item.nodeId === shell.calleeNodeId)
      ) {
        shell.bucket.push(item);
        claimed.add(item.id);
      }
    }
  }

  // Pass 2 — which tool calls a task announcement SPEAKS FOR.
  //
  // The list is rendered INSTEAD of the row that produced it, not beside it,
  // because that row is the whole complaint: claude's `TaskUpdate` collapses to
  // `TaskUpdate` in a tool group, and cursor's discloses no arguments at all
  // (`rawInput:{_toolName:"updateTodos"}`), so the reader learns that a tool
  // ran and nothing about the work. Both halves of the pair go, which is why
  // this has to be known BEFORE the fold: the result arrives later in the
  // stream than the announcement that claims it.
  const taskToolCallIds = new Set<string>();
  for (const item of items) {
    if (item.kind !== 'task_list') {
      continue;
    }
    const toolCallId = readTaskAnnouncement(item)?.toolCallId;
    if (toolCallId) {
      taskToolCallIds.add(toolCallId);
    }
  }

  // Pass 3 — the main fold over everything not claimed into a block.
  const entries: TranscriptEntry[] = [];
  const hiddenCallIds = new Set<string>();
  // The running fold per thread, and the card currently open for it. Kept per
  // thread because both CLIs number tasks from 1, so a delegate's task `1` and
  // the main agent's are different tasks.
  const taskLists = new Map<string | null, TaskAnnouncement[]>();
  const openTaskCards = new Map<string, TaskListEntry>();
  const pairsByCallId = new Map<string, ToolPair>();
  // Keyed by node AND by originating thread, so a sub-agent's calls collapse
  // into their own row and neither thread's narrative closes the other's group.
  const openGroups = new Map<string, ToolGroupEntry>();

  for (const item of items) {
    if (claimed.has(item.id)) {
      continue;
    }
    if (item.kind === 'call_started') {
      const callId = payloadString(item.payload, 'callId');
      const shell = callId ? shells.get(callId) : undefined;
      openGroups.delete(groupKey(item));
      if (
        callId &&
        shell &&
        shell.started.id === item.id &&
        shell.bucket.length > 0
      ) {
        entries.push(buildCallBlock(callId, shell));
      } else {
        // No tagged sub-turn yet (a legacy transcript, a call rejected
        // before any turn started, or the spawn racing this render) — keep
        // the flat call row; it upgrades to a block once tagged items land.
        entries.push({ type: 'item', item });
      }
      continue;
    }
    if (item.kind === 'tool_call') {
      const name = payloadString(item.payload, 'name') ?? '';
      const callId = payloadString(item.payload, 'id');
      if (
        name.startsWith(GENIRO_TOOL_PREFIX) ||
        (callId !== null && taskToolCallIds.has(callId))
      ) {
        if (callId) {
          hiddenCallIds.add(callId);
        }
        continue;
      }
      const pair: ToolPair = { call: item, result: null };
      if (callId) {
        pairsByCallId.set(callId, pair);
      }
      const key = groupKey(item);
      // A VISIBLE tool call closes this thread's open task card, so the next
      // announcement starts a fresh one. Without it a card floated above the
      // work done after it while showing the list as it stood afterwards. A
      // HIDDEN call never reaches here, which is what keeps a burst of task
      // tools — every one of them hidden — collapsed into the single card.
      openTaskCards.delete(key);
      const open = openGroups.get(key);
      if (open) {
        open.pairs.push(pair);
      } else {
        const group: ToolGroupEntry = {
          type: 'tools',
          id: item.id,
          nodeId: item.nodeId,
          parentToolUseId: subagentIdOf(item),
          // Filled by the closing sweep below, once the whole stream is known.
          closed: false,
          pairs: [pair],
        };
        openGroups.set(key, group);
        entries.push(group);
      }
      continue;
    }
    if (item.kind === 'tool_result') {
      const callId = payloadString(item.payload, 'id');
      if (callId && hiddenCallIds.has(callId)) {
        continue;
      }
      const pair = callId ? pairsByCallId.get(callId) : undefined;
      if (pair) {
        pair.result = item;
        continue;
      }
      entries.push({ type: 'item', item });
      continue;
    }
    if (item.kind === 'task_list') {
      const announcement = readTaskAnnouncement(item);
      if (announcement === null) {
        continue;
      }
      const thread = subagentIdOf(item);
      const history = taskLists.get(thread) ?? [];
      history.push(announcement);
      taskLists.set(thread, history);
      // Folded from the thread's WHOLE history rather than this run's rows: a
      // run holding one `TaskUpdate` knows about one task, and the list is only
      // ever the fold of everything before it.
      const tasks = foldTaskList(history);
      const key = groupKey(item);
      const open = openTaskCards.get(key);
      if (open) {
        open.tasks = tasks;
        open.seq = Math.max(open.seq, item.seq);
        continue;
      }
      // A card is a narrative row of its own, so it closes the tool group of the
      // thread that produced it — the same boundary any other rendered row is.
      openGroups.delete(key);
      const card: TaskListEntry = {
        type: 'task-list',
        id: item.id,
        createdAt: item.createdAt,
        seq: item.seq,
        nodeId: item.nodeId,
        parentToolUseId: thread,
        tasks,
        // Decided by the sweep below, once the whole stream is known — the same
        // shape `closed` on a tool group takes, and for the same reason: a card
        // cannot know whether a later one exists while it is being built.
        latest: false,
      };
      openTaskCards.set(key, card);
      entries.push(card);
      continue;
    }
    // Any other rendered kind from this node is a narrative boundary — the
    // node "said something", so its next tool call starts a fresh group. Only
    // for the thread that said it: a sub-agent reporting mid-way must not
    // split the main thread's group, which is what produced runs of one-call
    // rows while several sub-agents were talking at once.
    openGroups.delete(groupKey(item));
    openTaskCards.delete(groupKey(item));
    entries.push({ type: 'item', item });
  }
  closeGroupsBeforeTurnEnds(entries, items);
  // The last card of each thread is the current list. Keyed by the same
  // (node, thread) pair the cards were folded on, so a delegate's last card and
  // the agent's own are both current — they are different lists.
  const lastCard = new Map<string, TaskListEntry>();
  for (const entry of entries) {
    if (entry.type === 'task-list') {
      lastCard.set(
        `${entry.nodeId ?? ''}\u0000${entry.parentToolUseId ?? ''}`,
        entry,
      );
    }
  }
  for (const card of lastCard.values()) {
    card.latest = true;
  }
  return entries;
}

/**
 * Whether anything is still working through the list this card shows.
 *
 * Two conditions, and both are needed. An earlier card is a SNAPSHOT of a list
 * that has since moved on, so its in-progress row is history however live the
 * run is. And the latest card is only live while the run is: a turn that ended
 * with a task still in progress leaves a row that will never advance, and a
 * spinner on it claims work that stopped — the reported "finished one task,
 * still in progress for some reason".
 *
 * `runSettledAt` is read exactly as {@link subagentBlockStatus} reads it: a
 * MOMENT rather than a flag, so a card written AFTER the settle (the CLI
 * carrying on by itself past its own turn-end line) is still live, and an
 * unparseable settle keeps the conservative reading rather than putting every
 * spinner back.
 */
export function taskCardIsLive(
  entry: TaskListEntry,
  runSettledAt: RunSettleAt,
): boolean {
  if (!entry.latest) {
    return false;
  }
  if (runSettledAt === null) {
    return true;
  }
  if (runSettledAt === 'unknown') {
    return false;
  }
  const at = Date.parse(entry.createdAt);
  return Number.isFinite(at) && at > runSettledAt;
}

/** Item kinds that end a turn — after one, nothing more is coming for it. */
const TURN_END_KINDS = new Set(['turn_complete', 'turn_cancelled', 'error']);

/**
 * Mark every tool group that a turn ended after.
 *
 * Answered against the ITEM stream rather than the run's status, because the
 * question is per-turn: the run goes back to `running` on the user's next
 * message, and a group left open by turn 1 must stay closed through turn 5
 * rather than start spinning again with it.
 *
 * Recursive over blocks, since the fold nests groups inside turn- and
 * call-blocks and a nested group is exactly the sub-agent case that was
 * reported spinning.
 *
 * Scoped to the group's own NODE, for the same reason {@link
 * buildSubagentBlocks} scopes its own turn-end read: under graph fan-out each
 * node settles independently, so an unscoped comparison let node A's
 * `turn_complete` close node B's still-open group and drop the spinner off a
 * tool call genuinely in flight. In a 1:1 chat every `nodeId` is null, so the
 * scoping is a no-op there — which is why it went unnoticed.
 */
function closeGroupsBeforeTurnEnds(
  entries: readonly TranscriptEntry[],
  items: readonly ChatItem[],
): void {
  const turnEnds = items.filter((item) => TURN_END_KINDS.has(item.kind));
  if (turnEnds.length === 0) {
    return;
  }
  const walk = (list: readonly TranscriptEntry[]): void => {
    for (const entry of list) {
      if (entry.type === 'tools') {
        const lastSeq = entry.pairs.reduce(
          (max, pair) => Math.max(max, pair.result?.seq ?? pair.call.seq),
          0,
        );
        // A turn of THIS node ended after this group's last row, so this
        // group's turn is among the ones that finished.
        entry.closed = turnEnds.some(
          (item) => item.nodeId === entry.nodeId && item.seq > lastSeq,
        );
        continue;
      }
      if (entry.type === 'turn-block' || entry.type === 'call-block') {
        walk(entry.entries);
      }
    }
  };
  walk(entries);
}

/**
 * Assemble one call's block: status items drive the header's live status
 * (they never render as rows — the old "▸ B started"/"✓ B finished" pair
 * folds into the header icon), everything else re-folds recursively (tool
 * groups work inside a block; the bucket holds no call rows, so no blocks
 * nest from here).
 */
function buildCallBlock(callId: string, shell: CallShell): CallBlockEntry {
  let status: CallBlockEntry['status'] = 'pending';
  const inner: ChatItem[] = [];
  for (const item of shell.bucket) {
    if (item.kind === 'status') {
      const value = payloadString(item.payload, 'status');
      if (value && BLOCK_STATUSES.has(value)) {
        status = value as CallBlockEntry['status'];
      }
      continue;
    }
    inner.push(item);
  }
  // A COMPLETED sub-turn's last message is the call's RESULT — pull it out
  // of the flow so the block can frame it (request at the top, result at
  // the bottom). While running the tail message is just the latest stream.
  let result: string | null = null;
  if (status === 'completed') {
    for (let i = inner.length - 1; i >= 0; i--) {
      if (inner[i]!.kind === 'message') {
        result = payloadString(inner[i]!.payload, 'text');
        if (result !== null) {
          inner.splice(i, 1);
        }
        break;
      }
    }
  }
  // The ok settle envelope is pure bookkeeping once the block shows the
  // result and the done chip; only the error arm keeps a row (in-block).
  const visibleInner = inner.filter(
    (item) =>
      !(
        item.kind === 'call_result' &&
        payloadString(item.payload, 'status') === 'ok'
      ),
  );
  return {
    type: 'call-block',
    id: shell.started.id,
    createdAt: shell.started.createdAt,
    callId,
    calleeNodeId: shell.calleeNodeId,
    callerNodeId: shell.started.nodeId,
    mode: payloadString(shell.started.payload, 'mode'),
    message: payloadString(shell.started.payload, 'message'),
    status,
    result,
    // A callee runs its own delegates, so its sub-turn gets the same fold the
    // main flow gets. Without this a workflow callee's `Task` work spilled
    // loose into the call block, invisible to the panel and to the run badge —
    // and `collectSubagentBlocks`' recursion into call blocks could never find
    // anything, making its "at any depth" claim false.
    entries: buildSubagentBlocks(groupTranscript(visibleInner), visibleInner),
  };
}

/**
 * The file a tool RESULT names, when the call itself named none.
 *
 * An agent may disclose nothing about an edit up front and then report the whole
 * diff, path included, on completion (measured on cursor-agent — see
 * `resultDiffsOf`). That path is the only way to tell two edits of the same file
 * from edits of two files, which is the difference between "edited 1 file" and
 * "edited 2 files".
 */
function diffPathOf(result: ChatItem | null): string | null {
  if (result === null) {
    return null;
  }
  const payload = result.payload as { result?: unknown } | null;
  const [first] = resultDiffsOf(payload?.result ?? null);
  return first?.path ?? null;
}

/**
 * The collapsed group's one-line summary, Claude/Cursor-style:
 * "Read 4 files · ran 3 commands · edited 1 file".
 *
 * Every bucket names what the agent DID, because a bare "Used 7 tools" is the
 * one thing a reader cannot act on — seven reads and seven edits are the same
 * number and completely different turns. The buckets cover the tools a coding
 * agent actually spends its calls on: opening files, searching, running
 * commands, editing, writing, fetching, delegating, and calling MCP servers.
 *
 * The tool TOTAL is dropped when the breakdown already accounts for every call
 * in the group, because otherwise the same work is counted twice in one line:
 * a group holding one `Bash` read "Used 1 tool · ran 1 command", two figures
 * for a single action. Once some call falls outside the named buckets the total
 * is the only thing that reports it, so it comes back.
 *
 * `accounted` counts CALLS, while the file figures count DISTINCT paths — three
 * edits to one file are three accounted tools and one edited file, and comparing
 * the displayed numbers instead would have kept the total on exactly the groups
 * that need it least.
 *
 * A file-shaped tool with no `file_path` stays unaccounted ON PURPOSE: it would
 * otherwise be reported as an edit of nothing, and the total is the honest
 * answer for a call this cannot describe.
 */
export function toolGroupSummary(pairs: readonly ToolPair[]): string {
  const { spoken, accounted } = foldToolGroup(pairs);
  const parts = spoken.map((phrase) => phrase.text);
  if (parts.length === 0 || accounted < pairs.length) {
    parts.unshift(`Used ${countOf(pairs.length, 'tool')}`);
    return parts.join(' · ');
  }
  // The breakdown is now the whole line, so it opens the sentence.
  const [first, ...rest] = parts;
  return [first!.charAt(0).toUpperCase() + first!.slice(1), ...rest].join(
    ' · ',
  );
}

/**
 * How many operation glyphs a collapsed group's header carries.
 *
 * Three because the header is a one-line summary sitting in a narrow column and
 * a strip of glyphs long enough to need counting has stopped being a glance —
 * and because the phrases behind them are already spelled out in the sentence
 * beside it, so the icons are an index into that sentence rather than a
 * replacement for it.
 */
const MAX_GROUP_OPERATION_ICONS = 3;

/**
 * The operations a collapsed group's header should draw glyphs for — the same
 * ones {@link toolGroupSummary} SPEAKS, in the same order, capped.
 *
 * Off the same fold as the sentence, deliberately: a second pass over the pairs
 * is how an icon strip comes to disagree with the words next to it (a group
 * reading "read 2 files" under a terminal glyph). It also means the strip
 * inherits the summary's own honesty rules for free — an operation the sentence
 * cannot account for gets no glyph either, rather than a picture asserting
 * something the text declined to.
 *
 * `delegate`, `delete` and `move` are counted by the fold and never spoken, so
 * they draw nothing here either — see the note beside their phrases.
 */
export function toolGroupOperations(
  pairs: readonly ToolPair[],
): ToolOperation[] {
  return foldToolGroup(pairs)
    .spoken.map((phrase) => phrase.operation)
    .slice(0, MAX_GROUP_OPERATION_ICONS);
}

/** `1 file` / `3 files` — the shared pluralizer for the phrases below. */
function countOf(n: number, noun: string): string {
  return `${n} ${noun}${n === 1 ? '' : 's'}`;
}

/** One thing a group is reported to have done: the operation, and its wording. */
interface ToolGroupPhrase {
  operation: ToolOperation;
  text: string;
}

/**
 * The ONE pass over a group's pairs, feeding both the header's sentence and its
 * glyphs.
 *
 * Split out of {@link toolGroupSummary} rather than copied so the two readings
 * cannot drift — the same reason `toolOperationOf` is one classifier serving
 * both the summary and the per-row icon.
 */
function foldToolGroup(pairs: readonly ToolPair[]): {
  spoken: ToolGroupPhrase[];
  accounted: number;
} {
  let commands = 0;
  let searches = 0;
  let fetches = 0;
  let mcpCalls = 0;
  let accounted = 0;
  const opened = new Set<string>();
  const edited = new Set<string>();
  const created = new Set<string>();
  for (const { call, result } of pairs) {
    const input = (call.payload as { input?: unknown } | null)?.input;
    const file =
      input && typeof input === 'object' && 'file_path' in input
        ? String((input as { file_path: unknown }).file_path)
        : null;
    // What the call DID, from the ONE classifier — the agent's own answer when it
    // made one, else its tool name. The name buckets are one CLI's vocabulary:
    // cursor titles its calls "Read File", "Edit File", "grep" and discloses no
    // arguments at all, so before the agent's own answer was consulted a turn
    // that read, edited and ran a command summarised as "Used 2 tools" and named
    // nothing it had done.
    const operation = toolOperationOf(call.payload);
    // Whether the AGENT classified this call itself, which is a different
    // question and decides how a call with no path is counted. An agent-declared
    // kind is trusted with no target (cursor discloses none, so every one of its
    // calls would otherwise go unaccounted); a name-matched file tool is not —
    // it would be reported as an edit of nothing, and the "Used N tools" total is
    // the honest answer for a call this cannot describe.
    const selfDeclared = toolKindOf(call.payload) !== null;
    // A path when one is known — an edit's diff reports it even when the call did
    // not. Counting DISTINCT paths is what makes three edits of one file read as
    // one edited file.
    const path = file ?? diffPathOf(result);
    /** Count this call against a file bucket, or leave it unaccounted. */
    const addPath = (bucket: Set<string>): void => {
      if (path !== null) {
        bucket.add(path);
        accounted += 1;
      } else if (selfDeclared) {
        // No path to tell it apart, so the CALL is the unit. Keyed off the count
        // so two such calls never collapse into one.
        accounted += 1;
        bucket.add(`#${accounted}`);
      }
    };
    switch (operation) {
      case 'read':
        addPath(opened);
        break;
      case 'edit':
        addPath(edited);
        break;
      case 'create':
        addPath(created);
        break;
      case 'search':
        searches += 1;
        accounted += 1;
        break;
      case 'execute':
        commands += 1;
        accounted += 1;
        break;
      case 'fetch':
        fetches += 1;
        accounted += 1;
        break;
      case 'mcp':
        mcpCalls += 1;
        accounted += 1;
        break;
      case 'delegate':
        // Accounted but never SPOKEN — see the note where the other phrases are
        // assembled below.
        accounted += 1;
        break;
      case 'delete':
      case 'move':
        // Accounted but not SPOKEN either: neither has a phrase here, and
        // inventing one ("moved 1 file") for a kind never yet seen on the wire
        // would be guessing at wording no measurement supports.
        accounted += 1;
        break;
      case null:
        break;
    }
  }
  const count = countOf;
  const spoken: ToolGroupPhrase[] = [];
  if (opened.size > 0) {
    spoken.push({
      operation: 'read',
      text: `read ${count(opened.size, 'file')}`,
    });
  }
  if (searches > 0) {
    spoken.push({
      operation: 'search',
      text: `searched ${count(searches, 'time')}`,
    });
  }
  if (commands > 0) {
    spoken.push({
      operation: 'execute',
      text: `ran ${count(commands, 'command')}`,
    });
  }
  if (edited.size > 0) {
    spoken.push({
      operation: 'edit',
      text: `edited ${count(edited.size, 'file')}`,
    });
  }
  if (created.size > 0) {
    spoken.push({
      operation: 'create',
      text: `created ${count(created.size, 'file')}`,
    });
  }
  if (fetches > 0) {
    spoken.push({
      operation: 'fetch',
      text: `fetched ${count(fetches, 'page')}`,
    });
  }
  // `delegations` is counted into `accounted` and then deliberately NOT
  // spoken: a delegation already renders as its own sub-agent block directly
  // below this row, so naming it here says the same thing twice — which is
  // what "Delegated to 5 subagents" sitting over five sub-agent cards actually
  // looked like. It stays ACCOUNTED for so a group that MIXES delegations with
  // real work still reads as its breakdown ("Read 3 files") rather than
  // falling through to the "Used N tools" catch-all. A group of nothing BUT
  // delegations never reaches a reader at all: `buildSubagentBlocks` strips
  // those pairs out and drops the emptied group.
  if (mcpCalls > 0) {
    spoken.push({
      operation: 'mcp',
      text: `called ${count(mcpCalls, 'MCP tool')}`,
    });
  }
  return { spoken, accounted };
}

/** One-line argument preview for a tool row (the command, the path, …). */
export function toolCallSummary(call: ChatItem): string {
  const input = (call.payload as { input?: unknown } | null)?.input;
  if (!input || typeof input !== 'object') {
    return '';
  }
  const record = input as Record<string, unknown>;
  // An agent that named a call and disclosed no arguments has nothing to preview,
  // and `compactJson({})` below would render the literal `{}` — the reported
  // defect, on the line that is visible while the row is COLLAPSED. This is the
  // sibling of the same guard in `tool-render.ts`; it is a separate check rather
  // than a shared call because this function summarizes, it does not decide
  // whether to draw a body. It also covers rows persisted BEFORE the daemon
  // started normalizing the empty bag, which is why replaying an old cursor chat
  // still needs it.
  if (Object.keys(record).length === 0) {
    return '';
  }
  const first = (...keys: string[]): string | null => {
    for (const key of keys) {
      const value = record[key];
      if (typeof value === 'string' && value.length > 0) {
        return value;
      }
    }
    return null;
  };
  const questions = record.questions;
  if (Array.isArray(questions) && questions.length > 0) {
    const q = questions[0] as { question?: unknown };
    if (typeof q?.question === 'string') {
      return q.question;
    }
  }
  return (
    first(
      'command',
      'file_path',
      'pattern',
      'description',
      'query',
      'prompt',
      'path',
      'url',
    ) ?? compactJson(record)
  );
}

function compactJson(value: unknown): string {
  try {
    return JSON.stringify(value) ?? '';
  } catch {
    return String(value);
  }
}

/**
 * Flatten a tool_result payload's `result` for display.
 *
 * MOVED to `tool-render.ts`, which had to normalize the result itself — a diff an
 * agent reported cannot be recognised once it has been stringified. Re-exported
 * here because this module's own callers (and its spec) already read it from this
 * name.
 */
export { toolResultText } from './tool-render';

/**
 * Marks the synthetic entry carrying an agent's not-yet-durable words, so a
 * renderer can style the live tail (and a test can find it) without a new
 * entry kind threading through every switch in this file.
 */
export const LIVE_TEXT_ITEM_PREFIX = 'live:';

/** A live entry's owning node id, from the per-agent map's key. */
function nodeIdOf(key: string): string | null {
  return key === CHAT_LIVE_KEY ? null : key;
}

/**
 * Append each agent's live tail to the transcript it belongs to.
 *
 * Applied POST-fold, on the finished block list: the tail belongs to the turn
 * that is still being written, which is the LAST block that agent owns. When
 * the agent has no open block yet — its very first words, before any durable
 * item exists — a block is created so the text has somewhere to appear
 * (without this, the first thing you type would show nothing until the whole
 * paragraph landed, which is the entire bug being fixed).
 *
 * The tail rides as an ordinary assistant `message` item so it renders through
 * the same path as the durable text it is about to become. It is injected into
 * the RENDER list only — never into the `items` state — so nothing here can be
 * mistaken for persisted history.
 *
 * `workingAgents` names the agents whose turn is in flight. One that has
 * nothing to show right now — no words, no open reasoning stretch — still gets
 * a row, because the alternative is what the transcript did before: go
 * completely silent between a tool batch and the next words, leaving the chat
 * header as the only place saying anything was happening.
 */
export function withLiveText(
  blocks: readonly TranscriptEntry[],
  liveText: ReadonlyMap<string, LiveState>,
  workingAgents: ReadonlySet<string> = new Set(),
): TranscriptEntry[] {
  if (liveText.size === 0 && workingAgents.size === 0) {
    return blocks as TranscriptEntry[];
  }
  const out = [...blocks];
  /** Agents already given a row, so the working fallback does not double up. */
  const spokenFor = new Set<string>();
  for (const [key, state] of liveText) {
    // A stretch is open when the daemon says which one — never inferred from
    // the token count, which is legitimately 0 on a stretch's first delta.
    // WORDS WIN when both are present: the tail is text the user is already
    // watching appear, and replacing it with a thinking row would take the
    // sentence off the screen until its durable item landed.
    const thinking = state.text === '' && state.thinkingStretch !== null;
    // An entry can survive carrying only a context figure — the meter reads
    // that after the words went durable. There is no bubble to draw for it.
    if (state.text === '' && !thinking) {
      continue;
    }
    spokenFor.add(key);
    // Words render as the assistant message they are about to become; a
    // reasoning stretch has NO text to show (headless claude redacts it), so
    // its numbers ride the `reasoning` kind instead.
    //
    // The stretch id is IN the row's identity, which is what makes each wait
    // its own row: React remounts on the new key, so the clock starts at zero
    // and the row lands below whatever ran in between, instead of one row at
    // the bottom whose timer grew for the whole turn while tool groups piled
    // up above it.
    const entry = liveEntry(
      key,
      thinking
        ? {
            id: `${LIVE_TEXT_ITEM_PREFIX}${key}:think:${state.thinkingStretch}`,
            kind: 'reasoning',
            payload: {
              live: 'thinking',
              thinkingSince: state.thinkingSince,
              thinkingTokens: state.thinkingTokens ?? 0,
            },
          }
        : {
            id: `${LIVE_TEXT_ITEM_PREFIX}${key}`,
            kind: 'message',
            payload: { text: state.text },
          },
    );
    attach(out, entry);
  }
  for (const key of workingAgents) {
    if (spokenFor.has(key)) {
      continue;
    }
    // Measured from the last row this agent put on screen, NEVER from the row's
    // own mount — see {@link WorkingRow}'s `since`. Read from `blocks` rather
    // than `out`: the loop above may already have attached a live row, whose
    // `createdAt` is empty by construction.
    const since = lastMainThreadRowAt(blocks, nodeIdOf(key));
    attach(
      out,
      liveEntry(key, {
        id: `${LIVE_TEXT_ITEM_PREFIX}${key}:working`,
        kind: 'reasoning',
        payload: {
          live: 'working',
          ...(since === null ? {} : { workingSince: since }),
        },
      }),
    );
  }
  return out;
}

/**
 * When this agent's MAIN thread last put a row on screen, in epoch ms — the
 * anchor the working row counts from. Null when it never has.
 *
 * Its own thread only, matching {@link attach}'s rule and for a sharper reason
 * than symmetry: a delegate writes rows continuously while the agent that
 * launched it sits silent, so counting those would hold the clock near zero for
 * the whole delegation and answer the opposite of the question. What the row
 * reports is how long the agent you are talking to has shown you nothing.
 *
 * Unparseable and empty `createdAt` values are skipped rather than coerced: the
 * synthetic live entries carry `''`, and `Date.parse('')` is NaN, which would
 * poison a plain `Math.max`.
 */
function lastMainThreadRowAt(
  entries: readonly TranscriptEntry[],
  nodeId: string | null,
): number | null {
  let latest: number | null = null;
  const consider = (createdAt: string): void => {
    const at = Date.parse(createdAt);
    if (Number.isFinite(at) && (latest === null || at > latest)) {
      latest = at;
    }
  };
  const walk = (list: readonly TranscriptEntry[]): void => {
    for (const entry of list) {
      if (subagentOwnerOf(entry) !== null || entryNodeId(entry) !== nodeId) {
        continue;
      }
      if (entry.type === 'item') {
        consider(entry.item.createdAt);
        continue;
      }
      if (entry.type === 'tools') {
        for (const pair of entry.pairs) {
          consider(pair.result?.createdAt ?? pair.call.createdAt);
        }
        continue;
      }
      if (entry.type === 'task-list') {
        consider(entry.createdAt);
        continue;
      }
      walk(entry.entries);
    }
  };
  walk(entries);
  return latest;
}

/** One synthetic row, shaped like the durable item it renders through. */
function liveEntry(
  key: string,
  spec: {
    id: string;
    kind: ChatItem['kind'];
    payload: Record<string, unknown>;
  },
): ItemEntry {
  return {
    type: 'item',
    item: {
      id: spec.id,
      runId: '',
      nodeId: nodeIdOf(key),
      // Sorts after everything durable; this list is already ordered, so the
      // value only has to be larger than any real seq.
      seq: Number.MAX_SAFE_INTEGER,
      kind: spec.kind,
      role: 'assistant',
      payload: spec.payload,
      createdAt: '',
    },
  };
}

/**
 * Put a live row at the end of the block its agent is writing, or open one.
 *
 * The owner is read off the entry rather than passed in: two sources for one
 * value that must agree is how a row ends up attached to a block it does not
 * belong to.
 *
 * Only the LAST entry is a candidate, and that is the whole correctness of it.
 * A live row describes what is happening RIGHT NOW, so it belongs after
 * everything already on screen — but the fold breaks a turn block on every
 * user message, `turn_complete` divider and approval card, which leaves the
 * agent's previous block sitting further up. Searching backwards for it put
 * the row INSIDE that older block, and the three reported symptoms are all
 * that one walk:
 *
 * - press stop, send again, and the new turn's "Thinking…" appears above the
 *   message that started it;
 * - answer a question and the streaming reply renders above the answer, then
 *   snaps below it the moment the text goes durable (the durable item's seq
 *   puts it after the verdict, where it always belonged);
 * - the same for the `turn_complete` divider between two turns.
 *
 * When the last entry is not this agent's block, a NEW block is opened at the
 * end. That is also what makes the row's position stable across the
 * live→durable seam: both land after the same divider.
 */
function attach(out: TranscriptEntry[], entry: ItemEntry): void {
  const nodeId = entry.item.nodeId;
  // Matched on the thread as well as the node, exactly as `ownerOf` does. A
  // live row is the MAIN thread's — the daemon drops a sub-agent's deltas from
  // the live tail — so on nodeId alone it would be appended to a delegate's
  // block whenever one happened to be last, and rendered under that block's
  // `sub-agent` label as the delegate's own words.
  const subagentId = subagentIdOf(entry.item);
  const last = out[out.length - 1];
  if (
    last?.type === 'turn-block' &&
    last.nodeId === nodeId &&
    last.subagentId === subagentId
  ) {
    out[out.length - 1] = { ...last, entries: [...last.entries, entry] };
    return;
  }
  out.push({
    type: 'turn-block',
    id: entry.item.id,
    createdAt: entry.item.createdAt,
    nodeId,
    subagentId,
    entries: [entry],
  });
}
