import { useCallback } from 'react';

import type { CliKind } from '../../shared/contracts';
import type { AgentEffortListing } from '../autogenerated';
import type { DaemonApis } from '../daemon-api';
import { useAgentVocabulary } from './use-agent-vocabulary';

/** Nothing known yet — one frozen value, so an effect keyed on it is stable. */
const NOTHING_YET: AgentEffortListing = {
  efforts: [],
  unavailableReason: null,
};

/**
 * The reasoning-effort levels one agent CLI accepts FOR ONE MODEL, as its
 * adapter reports them.
 *
 * Nothing is hardcoded on this side — the levels are a CLI's own vocabulary
 * (`claude --effort`, whose accepted set is wider than its `--help` admits), so
 * the daemon owns the list and this hook only fetches it.
 *
 * `model` is part of the QUESTION, not a refinement of it, and that is the fix
 * this hook exists in its current shape for: the levels turned out to belong to
 * the model rather than to the CLI — measured on cursor-agent
 * 2026.08.11-e8db854, `claude-opus-5` takes `max` and `grok-4.6` does not,
 * while `auto-smart` has no effort axis at all — so a per-CLI list OFFERED a
 * value the chosen model refuses. Passing it here is what makes the chip show
 * exactly what will apply, and switching models re-asks rather than serving the
 * previous model's answer.
 *
 * A null model is legitimate and means "nothing chosen yet": the daemon answers
 * with the CLI-wide union, because the picker exists before a model does.
 *
 * An EMPTY list always arrives with the reason for it — a CLI with no effort
 * control, or a model with none — so the chip can say so rather than vanish.
 * Caching (keyed by kind AND model), the stale-response guard and the failure
 * fallback are {@link useAgentVocabulary}'s, shared with the model picker.
 */
export function useAgentEfforts(
  agentsApi: DaemonApis['agents'] | null,
  kind: CliKind | null,
  model: string | null = null,
): AgentEffortListing {
  const fetchFor = useCallback(
    async (agent: CliKind) => [
      await agentsApi!.listAgentEfforts({
        agent,
        // Omitted rather than sent empty: the daemon reads an absent model as
        // "answer with the union", and `''` is not that question.
        ...(model ? { model } : {}),
      }),
    ],
    [agentsApi, model],
  );
  const { items } = useAgentVocabulary<AgentEffortListing>(
    kind,
    agentsApi && fetchFor,
    // The cache key's second half. Without it a model switch serves the
    // previous model's levels from cache — which is the whole defect, moved
    // one layer up from the daemon.
    model,
  );
  return items[0] ?? NOTHING_YET;
}
