import {
  type Dispatch,
  type MutableRefObject,
  type RefObject,
  type SetStateAction,
  useCallback,
  useEffect,
  useRef,
  useState,
} from 'react';

import type { ChatsApi, ItemDto as ChatItem } from '../autogenerated';
import type { DaemonClient, VerdictAck } from '../daemon-client';
import { reportRendererIssue } from '../debug/report-ui-errors';
import { discardsContextReading } from './compaction-payload';
import { mergeAnchorRows } from './history-anchors';
import { applyLiveText, type LiveState, type LiveTextEvent } from './live-text';
import { useLiveAnchorAsks } from './use-live-anchor-asks';

/** Stable identity for "nobody is mid-sentence" — one value, so a reset that changes nothing re-renders nothing. */
export const EMPTY_LIVE_TEXT: ReadonlyMap<string, LiveState> = new Map();

/** A replacement of the window's rows, or a function of the rows it holds. */
type RowsUpdate = ChatItem[] | ((prev: ChatItem[]) => ChatItem[]);

export interface RunStreamOptions {
  /** The daemon's socket; null while there is none. */
  client: DaemonClient | null;
  /** Reads the rows a reconnect missed and the anchors they refer to. */
  chatApi: Pick<ChatsApi, 'listRunItems'> | null;
  /** The run on screen, read whenever an event arrives and never captured. */
  runIdRef: RefObject<string | null>;
  /** Rows a reconnect asks for when nothing is held, read at request time. */
  pageSizeRef: RefObject<number>;
  /**
   * False while the window shows the MIDDLE of the conversation: rows are then
   * not appended, and the live plane is not drawn over them. The chat screen's
   * jump state; a dock that holds only its tail always answers true.
   */
  atTail: () => boolean;
  /**
   * The consumer's own effects for a row, after the window has taken it. `live`
   * is false for a row out of a history or reconnect read. Every row takes this
   * path, so a consumer gates on `live` itself where a replay must not act.
   */
  onRow?: (item: ChatItem, live: boolean) => void;
  /** Every live-plane event for the run on screen, after it is applied. */
  onLiveEvent?: (event: LiveTextEvent) => void;
  /** The socket re-joined. Called first, whether or not a run is open. */
  onReconnect?: (joinError: boolean) => void;
  /**
   * The rows a reconnect read brought back for `runId`, after they are merged.
   * The consumer decides what a replayed tail means; the stream does not.
   */
  onMissed?: (runId: string, rows: readonly ChatItem[]) => void;
  /** A reconnect read failed. The stream has nothing merged for it. */
  onReplayFailed?: (runId: string, err: unknown) => void;
}

export interface RunStream {
  /** The rows of the run on screen, in seq order. */
  items: ChatItem[];
  /** Rows OUTSIDE {@link items} that rows inside it belong to — see `history-anchors.ts`. */
  anchors: ChatItem[];
  /** The agent's not-yet-durable words, folded by `withLiveText`. */
  liveText: ReadonlyMap<string, LiveState>;
  setLiveText: Dispatch<SetStateAction<ReadonlyMap<string, LiveState>>>;
  /** Keys `runId:requestId` of requests the daemon reported expired. */
  deadRequestKeys: Set<string>;
  /** Replace or update the rows, holding them to the run on screen alone. */
  commitItems: (update: RowsUpdate) => void;
  /** {@link commitItems} for the anchors. */
  commitAnchors: (update: RowsUpdate) => void;
  /** Forget which anchors the live rows have asked for — the thread changed. */
  forgetAnchorAsks: () => void;
  /** Mirror of {@link items}, for readers that run outside a render. */
  itemsRef: RefObject<ChatItem[]>;
  /** The newest seq taken into the window — the replay cursor when a socket drops. */
  lastSeqRef: MutableRefObject<number>;
  /**
   * The replay cursor itself, taken at the DROP: a live row can reach the
   * re-joined room before the replay runs and push {@link lastSeqRef} past the
   * rows that were missed.
   */
  reconnectAfterSeqRef: MutableRefObject<number>;
  /**
   * The one entry point for a row of the run on screen, live or replayed:
   * merged into the window when the window is at its tail, the cursor advanced,
   * the anchors it names asked for when it is live, a compaction's context
   * reading cleared, and then the consumer's {@link RunStreamOptions.onRow}.
   * A row of any other run is refused here, before anything else.
   */
  ingest: (item: ChatItem, live: boolean) => void;
}

/**
 * The per-run stream a transcript renders from — rows, anchors, the live plane,
 * request expiry, and the socket's reconnect replay — shared by the chat screen
 * and the workflow dock.
 *
 * It owns the state and the event handling. What differs between the two
 * surfaces (the sidebar, the queue, the notifications, a builder's canvas) is
 * passed in as options, so the rules for one run's rows are written once.
 *
 * The listeners are registered once per client and read the run and the options
 * through refs, so a consumer that changes identity per render does not tear
 * the socket subscriptions down and up.
 */
export function useRunStream(options: RunStreamOptions): RunStream {
  const { client, chatApi, runIdRef } = options;
  // The listeners read the latest callbacks through this ref, not through a
  // captured copy: the consumers' callbacks close over their own state and
  // would otherwise be stale for the life of the subscription.
  const optionsRef = useRef(options);
  optionsRef.current = options;

  const [items, setItems] = useState<ChatItem[]>([]);
  const [anchors, setAnchors] = useState<ChatItem[]>([]);
  const [liveText, setLiveText] =
    useState<ReadonlyMap<string, LiveState>>(EMPTY_LIVE_TEXT);
  const [deadRequestKeys, setDeadRequestKeys] = useState<Set<string>>(
    () => new Set(),
  );
  const itemsRef = useRef<ChatItem[]>([]);
  useEffect(() => {
    itemsRef.current = items;
  }, [items]);
  const lastSeqRef = useRef(-1);
  const reconnectAfterSeqRef = useRef(-1);

  const commitItems = useCallback(
    (update: RowsUpdate): void => {
      setItems((prev) => {
        const next = typeof update === 'function' ? update(prev) : update;
        const runId = runIdRef.current;
        const foreign = next.filter((item) => item.runId !== runId);
        if (foreign.length === 0) {
          return next;
        }
        for (const item of foreign) {
          reportRendererIssue(
            `transcript held an item from another run (${item.kind})`,
            {
              kind: 'foreign-transcript-item',
              activeRunId: runId ?? 'none',
              itemRunId: item.runId,
              itemKind: item.kind,
              itemSeq: String(item.seq),
            },
          );
        }
        return next.filter((item) => item.runId === runId);
      });
    },
    [runIdRef],
  );

  const commitAnchors = useCallback(
    (update: RowsUpdate): void => {
      setAnchors((prev) => {
        const next = typeof update === 'function' ? update(prev) : update;
        const runId = runIdRef.current;
        return next.every((item) => item.runId === runId)
          ? next
          : next.filter((item) => item.runId === runId);
      });
    },
    [runIdRef],
  );

  const anchorAsks = useLiveAnchorAsks({
    api: chatApi,
    items,
    anchors,
    isCurrentRun: (runId) => runIdRef.current === runId,
    onAnchors: (rows) => commitAnchors((prev) => mergeAnchorRows(prev, rows)),
  });
  const forgetAnchorAsks = anchorAsks.forget;
  // Read through a ref by `ingest`, which is stable and would otherwise hold
  // the first ask this hook was given.
  const askAnchorsRef = useRef(anchorAsks.ask);
  useEffect(() => {
    askAnchorsRef.current = anchorAsks.ask;
  }, [anchorAsks.ask]);

  const ingest = useCallback(
    (item: ChatItem, live: boolean): void => {
      if (item.runId !== runIdRef.current) {
        return;
      }
      // While the window shows the middle of the conversation there is no end
      // on screen to append to: doing it would draw the newest row directly
      // beneath one from hours earlier. The row is on the daemon, and the
      // consumer's return-to-tail fetches it. The append is what is suppressed,
      // and nothing else — the cursor and the consumer's effects still run.
      if (optionsRef.current.atTail()) {
        commitItems((prev) => {
          const last = prev[prev.length - 1];
          // Fast path: items carry a monotonic seq and are emitted persist-first,
          // so a strictly-newer item just appends. A full copy and resort per
          // streamed item is only needed on the rare out-of-order case below.
          if (last === undefined || item.seq > last.seq) {
            return [...prev, item];
          }
          // The replay/live seam, or a reconnect delta, can re-deliver an item.
          // De-duplicate BY ID, never by seq: identity is what `id` means, and
          // `seq` is only the order. Then insert in seq order.
          if (prev.some((existing) => existing.id === item.id)) {
            return prev;
          }
          // A stable sort keeps two rows that share a seq in arrival order.
          return [...prev, item].sort((a, b) => a.seq - b.seq);
        });
        if (live) {
          askAnchorsRef.current(item);
        }
      }
      if (item.seq > lastSeqRef.current) {
        lastSeqRef.current = item.seq;
      }
      // A compaction the app performed ITSELF, or a CLI's own that did not say
      // what it left behind, discards the conversation the live plane measured.
      // The window's copy of that reading is cleared here; the daemon clears its
      // own, and the transcript fold resets at the row. The window (the model's)
      // is not cleared — a compaction does not change it.
      if (discardsContextReading(item)) {
        setLiveText((prev) => {
          const next = new Map(prev);
          for (const [key, state] of next) {
            next.set(key, { ...state, contextTokens: null });
          }
          return next;
        });
      }
      optionsRef.current.onRow?.(item, live);
    },
    [runIdRef, commitItems],
  );

  useEffect(() => {
    if (client === null) {
      return;
    }
    const unsubscribeItem = client.onItem((item) => {
      ingest(item, true);
    });
    const unsubscribeLiveText = client.onLiveText((event) => {
      // Throwaway by design: shown only for the run on screen, and dropped
      // wholesale on a run switch or a disconnect.
      if (event.runId !== runIdRef.current) {
        return;
      }
      // The sibling of `ingest`'s append guard, for the same reason: parked on
      // a window from the middle of the conversation, the streaming row would
      // be drawn under rows from hours earlier.
      if (!optionsRef.current.atTail()) {
        return;
      }
      setLiveText((prev) => applyLiveText(prev, event));
      optionsRef.current.onLiveEvent?.(event);
    });
    const unsubscribeDisconnect = client.onDisconnect(() => {
      reconnectAfterSeqRef.current = lastSeqRef.current;
      // What we hold is arbitrarily stale the moment the socket drops; the
      // durable replay below is complete on its own.
      setLiveText(EMPTY_LIVE_TEXT);
    });
    const unsubscribeReconnect = client.onReconnect((error) => {
      const joinError = error !== undefined;
      optionsRef.current.onReconnect?.(joinError);
      const runId = runIdRef.current;
      const api = optionsRef.current.chatApi;
      // A re-join nobody answered has already dropped the transport, so another
      // reconnect — and this replay with it — is on its way.
      if (runId === null || joinError || api === null) {
        return;
      }
      // Never `-1` on a cursor that was never taken: the daemon reads that as
      // the whole transcript, and a socket dropped while a thread was still
      // opening would pull every row of a long run over a phone's connection.
      const cursor = reconnectAfterSeqRef.current;
      const pageSize = optionsRef.current.pageSizeRef.current;
      void (async () => {
        let read: { items: ChatItem[]; anchors: ChatItem[] };
        try {
          read = await api.listRunItems(
            cursor < 0
              ? { runId, limit: pageSize }
              : { runId, afterSeq: cursor },
          );
        } catch (err) {
          optionsRef.current.onReplayFailed?.(runId, err);
          return;
        }
        const own = read.items.filter((row) => row.runId === runId);
        // Rows FIRST, anchors after: a row's anchors are only useful once the
        // row is on screen. The replay is not live, so no row may fire the
        // consumer's live decisions — `ingest` passes `live: false` through.
        for (const row of own) {
          ingest(row, false);
        }
        // Anchors follow the rows they belong to: away from the tail `ingest`
        // refused every row, so their anchors would place cards for work the
        // window does not hold.
        if (optionsRef.current.atTail()) {
          const ownAnchors = read.anchors.filter((row) => row.runId === runId);
          commitAnchors((prev) => mergeAnchorRows(prev, ownAnchors));
        }
        optionsRef.current.onMissed?.(runId, own);
      })();
    });
    const unsubscribeVerdict = client.onVerdictAck((ack: VerdictAck) => {
      if (
        ack.status === 'expired' &&
        ack.runId === runIdRef.current &&
        ack.requestId !== null
      ) {
        const requestKey = `${ack.runId}:${ack.requestId}`;
        setDeadRequestKeys((prev) => new Set(prev).add(requestKey));
      }
    });
    return () => {
      unsubscribeItem();
      unsubscribeLiveText();
      unsubscribeDisconnect();
      unsubscribeReconnect();
      unsubscribeVerdict();
    };
  }, [client, ingest, commitAnchors, runIdRef]);

  return {
    items,
    anchors,
    liveText,
    setLiveText,
    deadRequestKeys,
    commitItems,
    commitAnchors,
    forgetAnchorAsks,
    itemsRef,
    lastSeqRef,
    reconnectAfterSeqRef,
    ingest,
  };
}
