// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { NO_TOTALS } from '../__tests__/chat-totals';
import type { NodeStateDto, WorkflowsApi } from '../autogenerated';
import type { DaemonClient } from '../daemon-client';
import {
  type NodeDurableReading,
  useNodeDurableReadings,
} from './use-node-context';

const roots: Root[] = [];

afterEach(() => {
  act(() => {
    for (const root of roots.splice(0)) {
      root.unmount();
    }
  });
});

function node(
  nodeId: string,
  tokens: number | null,
  window: number | null,
  calls: NodeStateDto['calls'] = [],
) {
  return {
    runId: 'run-1',
    nodeId,
    status: 'running',
    contextTokens: tokens,
    contextWindowTokens: window,
    calls,
    totals: NO_TOTALS,
    mainTotals: NO_TOTALS,
    startedAt: null,
    endedAt: null,
    error: null,
  } as NodeStateDto;
}

/** Renders the hook and hands its latest value back through a box. */
function drive(
  api: WorkflowsApi,
  initial: {
    runId: string | null;
    isWorkflow: boolean;
    nonce: number;
    settled?: number;
    client?: Pick<DaemonClient, 'onRunStatus'>;
  },
): {
  seen: {
    readings: ReadonlyMap<string, NodeDurableReading>;
    /**
     * One entry per RENDER, so a test can read the frame before effects flush —
     * `act` runs them before it returns, so the post-`set` value alone cannot
     * tell a render-time guard from the effect that follows it.
     */
    renders: { runId: string | null; size: number }[];
  };
  set: (next: Partial<typeof initial>) => Promise<void>;
} {
  const seen = {
    readings: new Map() as ReadonlyMap<string, NodeDurableReading>,
    renders: [] as { runId: string | null; size: number }[],
  };
  let props = initial;

  function Probe({
    runId,
    isWorkflow,
    nonce,
    settled,
    client,
  }: typeof initial): React.JSX.Element {
    const readings = useNodeDurableReadings(
      runId,
      isWorkflow,
      api,
      nonce,
      settled,
      client ?? null,
    );
    seen.readings = readings;
    seen.renders.push({ runId, size: readings.size });
    return <div />;
  }

  const container = document.createElement('div');
  document.body.appendChild(container);
  const root = createRoot(container);
  roots.push(root);
  act(() => root.render(<Probe {...props} />));

  return {
    seen,
    set: async (next) => {
      props = { ...props, ...next };
      await act(async () => {
        root.render(<Probe {...props} />);
      });
    },
  };
}

/** Let the hook's own promise chain settle inside `act`. */
async function settle(): Promise<void> {
  await act(async () => {
    await Promise.resolve();
    await Promise.resolve();
  });
}

describe('useNodeDurableReadings', () => {
  it('carries the PER-CALL readings through, not only the node’s own', async () => {
    // The reader hop of the wire field. The node figures collapse to whichever
    // call wrote last, so a node called twice needs both rows here or the
    // sidebar's per-call rings have no durable source to fall back on.
    const listWorkflowRunNodes = vi.fn(async () => [
      node('reviewer', 91_000, 200_000, [
        {
          callId: 'call-1',
          contextTokens: 10_000,
          contextWindowTokens: 200_000,
          totals: NO_TOTALS,
        },
        {
          callId: 'call-2',
          contextTokens: 91_000,
          contextWindowTokens: 200_000,
          totals: NO_TOTALS,
        },
      ]),
    ]);
    const { seen } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      { runId: 'run-1', isWorkflow: true, nonce: 0 },
    );
    await settle();

    expect(seen.readings.get('reviewer')?.calls).toEqual([
      {
        callId: 'call-1',
        contextTokens: 10_000,
        contextWindowTokens: 200_000,
        totals: NO_TOTALS,
      },
      {
        callId: 'call-2',
        contextTokens: 91_000,
        contextWindowTokens: 200_000,
        totals: NO_TOTALS,
      },
    ]);
  });

  it('reads the daemon’s per-node rows when a workflow run opens', async () => {
    const listWorkflowRunNodes = vi.fn(async () => [
      // The running turn's start is carried too: it is what the live clocks
      // count from when the turn opened above the loaded page.
      { ...node('reviewer', 42_000, 200_000), startedAt: 1_000 },
      node('poet', null, null),
    ]);
    const { seen } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      {
        runId: 'run-1',
        isWorkflow: true,
        nonce: 0,
      },
    );
    await settle();

    expect(listWorkflowRunNodes).toHaveBeenCalledWith({ runId: 'run-1' });
    expect(seen.readings.get('reviewer')).toEqual({
      contextTokens: 42_000,
      contextWindowTokens: 200_000,
      calls: [],
      status: 'running',
      startedAt: 1_000,
      totals: NO_TOTALS,
      mainTotals: NO_TOTALS,
    });
    // A node that has never reported is carried as nulls rather than dropped —
    // the caller's own chain is what decides to fall through it.
    expect(seen.readings.get('poet')).toEqual({
      contextTokens: null,
      contextWindowTokens: null,
      calls: [],
      status: 'running',
      startedAt: null,
      totals: NO_TOTALS,
      mainTotals: NO_TOTALS,
    });
  });

  it('re-reads when a turn SETTLES, keeping the previous answer until the new one lands', async () => {
    // A node's SPEND moves only when a turn completes and has no live twin, so
    // a reading taken at open froze every agent's cost for the life of the
    // window. The re-read must not blank the rings while it is in flight.
    const listWorkflowRunNodes = vi
      .fn()
      .mockResolvedValueOnce([node('reviewer', 42_000, 200_000)])
      .mockReturnValueOnce(new Promise(() => {}));
    const { seen, set } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      { runId: 'run-1', isWorkflow: true, nonce: 0, settled: 1 },
    );
    await settle();
    expect(seen.readings.size).toBe(1);

    await set({ settled: 2 });

    expect(listWorkflowRunNodes).toHaveBeenCalledTimes(2);
    expect(
      seen.renders.every(
        (frame) => frame.size === 1 || frame === seen.renders[0],
      ),
    ).toBe(true);
    expect(seen.readings.get('reviewer')?.contextTokens).toBe(42_000);
  });

  it('re-reads when the daemon announces a new cursor PRICE for this run, and only this run', async () => {
    // A cursor node's bill lands up to a minute after its turn, with no settled
    // turn after it — so without this the card never showed the last price.
    let listener: ((event: never) => void) | null = null;
    const client = {
      onRunStatus: (fn: (event: never) => void) => {
        listener = fn;
        return () => {
          listener = null;
        };
      },
    } as unknown as Pick<DaemonClient, 'onRunStatus'>;
    const listWorkflowRunNodes = vi.fn(async () => [node('reviewer', 1, 2)]);
    drive({ listWorkflowRunNodes } as unknown as WorkflowsApi, {
      runId: 'run-1',
      isWorkflow: true,
      nonce: 0,
      client,
    });
    await settle();
    expect(listWorkflowRunNodes).toHaveBeenCalledTimes(1);

    await act(async () => {
      listener?.({ runId: 'run-2', status: null, spendUpdatedAt: 5 } as never);
    });
    expect(listWorkflowRunNodes).toHaveBeenCalledTimes(1);

    await act(async () => {
      listener?.({ runId: 'run-1', status: null, spendUpdatedAt: 5 } as never);
    });
    await settle();
    expect(listWorkflowRunNodes).toHaveBeenCalledTimes(2);
  });

  it('does not ask about a CHAT run, which has no nodes', async () => {
    const listWorkflowRunNodes = vi.fn(async () => []);
    drive({ listWorkflowRunNodes } as unknown as WorkflowsApi, {
      runId: 'run-1',
      isWorkflow: false,
      nonce: 0,
    });
    await settle();

    expect(listWorkflowRunNodes).not.toHaveBeenCalled();
  });

  it('asks again on RECONNECT — the readings are not rows to replay', async () => {
    // The item delta covers everything that is a row; a figure on a
    // `node_state` column is not one, so a window that was away while the
    // nodes went on working has no other way to learn what it missed.
    const listWorkflowRunNodes = vi
      .fn<() => Promise<NodeStateDto[]>>()
      .mockResolvedValueOnce([node('reviewer', 10_000, 200_000)])
      .mockResolvedValueOnce([node('reviewer', 90_000, 200_000)]);
    const { seen, set } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      { runId: 'run-1', isWorkflow: true, nonce: 0 },
    );
    await settle();
    expect(seen.readings.get('reviewer')?.contextTokens).toBe(10_000);

    await set({ nonce: 1 });
    await settle();

    expect(listWorkflowRunNodes).toHaveBeenCalledTimes(2);
    expect(seen.readings.get('reviewer')?.contextTokens).toBe(90_000);
  });

  it('shows NOTHING rather than a stale map when the re-ask fails', async () => {
    // The effect clears on entry, so a failed fetch costs this run's rings
    // their durable source — it never leaves another run's figures, or an older
    // reading of this one, standing in for a request that did not answer. The
    // ring falls back to the live plane and the transcript, which is what the
    // other two sources are for.
    const listWorkflowRunNodes = vi
      .fn<() => Promise<NodeStateDto[]>>()
      .mockResolvedValueOnce([node('reviewer', 10_000, 200_000)])
      .mockRejectedValueOnce(new Error('daemon GET failed (500)'));
    const { seen, set } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      { runId: 'run-1', isWorkflow: true, nonce: 0 },
    );
    await settle();

    await set({ nonce: 1 });
    await settle();

    expect(seen.readings.size).toBe(0);
  });

  it('drops the previous run’s readings the moment the run CHANGES', async () => {
    // Two runs of one workflow share node ids, so a map left mounted while the
    // new run's fetch is in flight resolves every ring against the wrong run's
    // row — the defect `apps/ui/CLAUDE.md` states the rule for on the metrics
    // panel. Asserted BEFORE the second fetch settles, which is the window.
    const listWorkflowRunNodes = vi
      .fn<() => Promise<NodeStateDto[]>>()
      .mockResolvedValueOnce([node('reviewer', 10_000, 200_000)])
      // run-2's request never answers, which IS the window under test.
      .mockImplementationOnce(() => new Promise<NodeStateDto[]>(() => {}));
    const { seen, set } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      { runId: 'run-1', isWorkflow: true, nonce: 0 },
    );
    await settle();
    expect(seen.readings.size).toBe(1);

    await set({ runId: 'run-2' });
    await settle();

    expect(seen.readings.size).toBe(0);
  });

  it('shows nothing on the very render that changes the run', async () => {
    // The window the effect cannot cover. It clears on entry — but it runs
    // AFTER the render that changed `runId`, and two runs of one workflow share
    // node ids, so that one render resolves every ring against the previous
    // run's row. The case above asserts once `act` has flushed effects, so it
    // holds with the render-time guard deleted; this one reads the render.
    const listWorkflowRunNodes = vi
      .fn<() => Promise<NodeStateDto[]>>()
      .mockResolvedValueOnce([node('reviewer', 10_000, 200_000)])
      .mockImplementationOnce(() => new Promise<NodeStateDto[]>(() => {}));
    const { seen, set } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      { runId: 'run-1', isWorkflow: true, nonce: 0 },
    );
    await settle();
    expect(seen.readings.size).toBe(1);
    const beforeSwitch = seen.renders.length;

    await set({ runId: 'run-2' });

    // The FIRST render under the new run, before its effect had run at all.
    expect(seen.renders[beforeSwitch]).toEqual({ runId: 'run-2', size: 0 });
  });

  it('lets a superseded fetch resolve without repainting the new run', async () => {
    // The stale-response guard. Without a case that actually races it, the
    // `if (cancelled) return` arm ships unpinned and a later cleanup could
    // delete the one thing standing between a slow run-1 reply and run-2's
    // rings.
    let releaseFirst: (rows: NodeStateDto[]) => void = () => undefined;
    const listWorkflowRunNodes = vi
      .fn<() => Promise<NodeStateDto[]>>()
      .mockImplementationOnce(
        () =>
          new Promise<NodeStateDto[]>((resolve) => {
            releaseFirst = resolve;
          }),
      )
      .mockResolvedValueOnce([]);
    const { seen, set } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      { runId: 'run-1', isWorkflow: true, nonce: 0 },
    );

    // Switch away while run-1's request is still in flight, THEN answer it.
    await set({ runId: 'run-2' });
    await act(async () => {
      releaseFirst([node('reviewer', 10_000, 200_000)]);
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(seen.readings.size).toBe(0);
  });

  it('drops every reading when the run is closed', async () => {
    const listWorkflowRunNodes = vi.fn(async () => [
      node('reviewer', 10_000, 200_000),
    ]);
    const { seen, set } = drive(
      { listWorkflowRunNodes } as unknown as WorkflowsApi,
      { runId: 'run-1', isWorkflow: true, nonce: 0 },
    );
    await settle();
    expect(seen.readings.size).toBe(1);

    await set({ runId: null });
    await settle();

    expect(seen.readings.size).toBe(0);
  });
});
