import { useEffect, useRef, useState } from 'react';

import type { CliKind } from '../../shared/contracts';
import type { AgentSkillDto as AgentSkill } from '../autogenerated';
import type { DaemonApis } from '../daemon-api';
import { mergeSkills } from './skill-autocomplete';

/**
 * The composer target's invokable skills, fetched from the daemon per
 * (agent kind, cwd) and cached for the session (the underlying disk layout
 * rarely changes mid-session; a restart re-scans). `kinds` may hold several
 * kinds — a workflow trigger fanning out to mixed agents — whose lists union
 * de-duped by name. A fetch failure just yields an empty list: the
 * autocomplete is a nicety, never an error surface.
 */
export function useAgentSkills(
  agentsApi: DaemonApis['agents'],
  kinds: readonly CliKind[],
  cwd: string | null,
): AgentSkill[] {
  const cacheRef = useRef(new Map<string, AgentSkill[]>());
  const [skills, setSkills] = useState<AgentSkill[]>([]);
  // The kinds array is rebuilt every render — key the effect on its value.
  const kindsKey = kinds.join(',');
  useEffect(() => {
    const targetKinds =
      kindsKey === '' ? [] : (kindsKey.split(',') as CliKind[]);
    if (cwd === null || targetKinds.length === 0) {
      setSkills([]);
      return;
    }
    let stale = false;
    void Promise.all(
      targetKinds.map(async (kind) => {
        const key = `${kind}\u0000${cwd}`;
        const cached = cacheRef.current.get(key);
        if (cached) {
          return cached;
        }
        try {
          const list = await agentsApi.listAgentSkills({ agent: kind, cwd });
          cacheRef.current.set(key, list);
          return list;
        } catch {
          return [];
        }
      }),
    ).then((lists) => {
      if (!stale) {
        setSkills(mergeSkills(lists));
      }
    });
    return () => {
      stale = true;
    };
  }, [agentsApi, kindsKey, cwd]);
  return skills;
}
