import { useCallback, useState } from 'react';

import {
  AttachmentMediaType,
  type SendMessageDtoImagesInner,
} from '../autogenerated';

/**
 * TWIN LIMIT: apps/daemon/src/v1/agents/chat.types.ts
 * MAX_ATTACHMENT_BYTES / MAX_ATTACHMENTS_PER_MESSAGE.
 *
 * The daemon enforces these for real. Repeating them here is what turns a
 * refusal into a message the user reads BEFORE composing a whole prompt around
 * an image that was never going to be accepted.
 */
export const MAX_ATTACHMENT_BYTES = 5 * 1024 * 1024;
export const MAX_ATTACHMENTS = 8;

const ACCEPTED: string[] = Object.values(AttachmentMediaType);

/** One image staged in the composer, not yet sent. */
export interface StagedAttachment {
  /** Local-only id — the daemon mints the durable one when the message lands. */
  key: string;
  mediaType: AttachmentMediaType;
  /** base64 bytes, ready for the send body. */
  data: string;
  /** `data:` URL for the thumbnail. */
  preview: string;
  name: string;
}

const readAsBase64 = (file: File): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error(`could not read ${file.name}`));
    reader.onload = () => {
      const result = String(reader.result);
      // A data URL is `data:<media-type>;base64,<payload>` — the wire wants
      // only the payload.
      resolve(result.slice(result.indexOf(',') + 1));
    };
    reader.readAsDataURL(file);
  });

/**
 * Images staged on the composer.
 *
 * A pasted screenshot arrives as a `File` on the clipboard event; it is read
 * to base64 once, here, so the send path is a plain object and the thumbnail
 * needs no object-URL lifecycle to leak.
 */
export function useAttachments(): {
  attachments: StagedAttachment[];
  error: string | null;
  /** Returns true when the event carried images (so the caller can preventDefault). */
  addFromClipboard: (data: DataTransfer | null) => boolean;
  remove: (key: string) => void;
  clear: () => void;
  clearError: () => void;
  /** The send-body projection. */
  toWire: () => SendMessageDtoImagesInner[];
} {
  const [attachments, setAttachments] = useState<StagedAttachment[]>([]);
  const [error, setError] = useState<string | null>(null);

  const addFromClipboard = useCallback((data: DataTransfer | null): boolean => {
    const files = [...(data?.files ?? [])].filter((file) =>
      file.type.startsWith('image/'),
    );
    if (files.length === 0) {
      return false;
    }
    setError(null);
    for (const file of files) {
      if (!ACCEPTED.includes(file.type)) {
        setError(`${file.type} images are not supported`);
        continue;
      }
      if (file.size > MAX_ATTACHMENT_BYTES) {
        setError(
          `${file.name || 'image'} is larger than ${Math.floor(MAX_ATTACHMENT_BYTES / 1024 / 1024)}MB`,
        );
        continue;
      }
      void readAsBase64(file)
        .then((base64) => {
          setAttachments((current) => {
            if (current.length >= MAX_ATTACHMENTS) {
              setError(`at most ${MAX_ATTACHMENTS} images per message`);
              return current;
            }
            return [
              ...current,
              {
                // A pasted screenshot has no name and two pastes of the same
                // image are indistinguishable by content, so the key is
                // positional + random rather than derived from the file.
                key: `${Date.now()}-${current.length}-${Math.random().toString(36).slice(2, 8)}`,
                mediaType: file.type as AttachmentMediaType,
                data: base64,
                preview: `data:${file.type};base64,${base64}`,
                name: file.name || 'pasted image',
              },
            ];
          });
        })
        .catch((err: unknown) => {
          setError(err instanceof Error ? err.message : 'could not read image');
        });
    }
    return true;
  }, []);

  const remove = useCallback((key: string): void => {
    setAttachments((current) => current.filter((item) => item.key !== key));
  }, []);

  const clear = useCallback((): void => {
    setAttachments([]);
    setError(null);
  }, []);

  const clearError = useCallback((): void => setError(null), []);

  const toWire = useCallback(
    (): SendMessageDtoImagesInner[] =>
      attachments.map(({ mediaType, data }) => ({ mediaType, data })),
    [attachments],
  );

  return {
    attachments,
    error,
    addFromClipboard,
    remove,
    clear,
    clearError,
    toWire,
  };
}
