import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import type { CliKind } from '../../shared/contracts';
import {
  type AgentMcpListingDto as AgentMcpListing,
  FetchError,
} from '../autogenerated';
import { type DaemonApis, MCP_ROUTE_TIMEOUT_MS } from '../daemon-api';
import { usePendingRetry } from '../use-pending-retry';

/** Shown when the daemon itself could not be reached or timed out. */
const TRANSPORT_FAILURE = 'could not load MCP servers';

/**
 * What to tell the user when the request itself failed.
 *
 * An abort is named as one: it is the only failure whose cause the user can act
 * on (their servers are slow to start), and "could not load MCP servers" gave
 * them nothing to act on at all. Everything else carries the daemon's own line,
 * which `daemon-api.ts` has already reduced to one sentence.
 *
 * UNWRAPPED FIRST, and that is the whole reason this is not a one-liner: the
 * generated runtime catches every transport rejection and re-throws it as a
 * `FetchError` carrying the original on `.cause`, with a message about
 * interceptors that means nothing to anyone. Testing the outer error directly
 * therefore never matched a real timeout — the one failure this budget exists
 * to explain would have printed the generator's own boilerplate instead.
 */
function transportReason(err: unknown): string {
  const root = err instanceof FetchError ? err.cause : err;
  if (root instanceof DOMException && root.name === 'TimeoutError') {
    return 'could not load MCP servers — they took too long to answer (a server that has to start up can be slow)';
  }
  const detail = root instanceof Error ? root.message.trim() : '';
  return detail ? `${TRANSPORT_FAILURE} — ${detail}` : TRANSPORT_FAILURE;
}

/** Shown when the daemon refused or never received the toggle. */
const TOGGLE_FAILURE = 'could not change that server';

/** Stable empty map, so a folder with no answers yet keeps a steady identity. */
const EMPTY_LISTINGS: ReadonlyMap<string, AgentMcpListing> = new Map();

/**
 * What a listing is ABOUT: a CLI, plus the plugin directory the node running
 * it names — a plugin can ship its own MCP servers, so two nodes on the same
 * CLI pointed at different directories genuinely load different sets.
 */
export interface AgentMcpScope {
  agent: CliKind;
  pluginDir: string | null;
}

/**
 * The map key for one scope. NUL-joined, the one byte neither an agent kind
 * nor a path can contain — the same key shape the daemon's own cache uses.
 */
export function mcpScopeKey(scope: AgentMcpScope): string {
  return `${scope.agent}\u0000${scope.pluginDir ?? ''}`;
}

/** One agent scope's servers, as the panel reads them. */
export interface AgentMcpState {
  /**
   * Listing per {@link mcpScopeKey}. A scope absent from the map has not
   * answered yet.
   */
  byScope: ReadonlyMap<string, AgentMcpListing>;
  loading: boolean;
  /** Re-read health from the CLIs, bypassing the daemon's cached reading. */
  refresh: () => void;
  /**
   * Switch one server on or off for one CLI kind in the run's folder.
   *
   * Deliberately NOT optimistic. The daemon refuses a toggle it cannot honour
   * — a non-project server, or one the user disabled in their own settings —
   * and painting the switch first would show the user a state the next turn
   * will not have. The answer it returns IS the new listing.
   *
   * KNOWN LIMITATION: the in-flight write raises the same `loading` flag the
   * read does, so every switch in the panel goes disabled, not just the one
   * clicked — including an unrelated CLI's card. Accepted rather than fixed:
   * the window is sub-second on a cache hit and the header's refresh control
   * already spins as feedback. A per-row pending set is the fix if the wait
   * ever becomes visible (a first read after the TTL lapses re-dials, and
   * that one is not sub-second).
   */
  setEnabled: (kind: CliKind, server: string, enabled: boolean) => void;
  /** The last toggle failure, or null. Cleared by dismissing or by a new try. */
  toggleError: string | null;
  dismissToggleError: () => void;
}

/**
 * The MCP servers each agent SCOPE loads in the run's folder.
 *
 * Keyed by (CLI kind, plugin directory) rather than by node, because that is
 * the grain the answer actually has: two nodes driving the same CLI with the
 * same plugin directory necessarily load the same servers, and asking once per
 * node would health-check the user's servers N times over for one answer.
 *
 * It was keyed by CLI kind ALONE until the plugin directory became a per-NODE
 * field. The rationale written here then — "a run has one folder, so two nodes
 * on the same CLI load the same servers" — stopped being true at that moment,
 * and the panel went on painting one node's answer onto another's card.
 *
 * Unlike the skills hook this deliberately holds NO session cache of its own —
 * the daemon already caches per (agent, cwd, version), and a second cache in
 * front of it would make Refresh a lie: the user would clear the daemon's
 * reading and still be shown the renderer's copy.
 *
 * A failure yields an empty listing for that kind. This is an informational
 * panel, not an error surface.
 */
export function useAgentMcp(
  agentsApi: DaemonApis['agents'],
  scopes: readonly AgentMcpScope[],
  cwd: string | null,
  /**
   * Whether anything is actually SHOWING this listing right now.
   *
   * The read is not free and it is not passive: the daemon health-checks each
   * server, which LAUNCHES the user's own MCP servers. Doing that on mount —
   * for a panel band nobody had asked to look at — is what made a chat greet
   * the user with a wall of connection failures from servers they never
   * intended to start. Gated, the launch happens when the list is opened.
   */
  enabled = true,
): AgentMcpState {
  // The answers are stored WITH the (kinds, folder) they answer for. Without
  // that pairing, switching chats leaves the previous folder's rows on screen
  // until the new read resolves — and the panel would be stating folder A's
  // servers as folder B's, which is wrong rather than merely stale.
  const [answered, setAnswered] = useState<{
    scope: string;
    byScope: ReadonlyMap<string, AgentMcpListing>;
  }>({ scope: '', byScope: EMPTY_LISTINGS });
  const [pending, setPending] = useState(false);
  // Bumped by refresh; the effect keys on it, so a bump re-runs the read.
  const [reloadToken, setReloadToken] = useState(0);
  // The token the last read already spent. Refresh is a ONE-SHOT intent about
  // the folder on screen, so it must be consumed rather than latched: the
  // effect also re-runs on cwd and kind changes, and a monotonic
  // `reloadToken > 0` would make every later navigation re-dial — re-launching
  // the user's own MCP servers — for the rest of the session.
  const consumedToken = useRef(0);
  // Bumped when a WRITE's answer lands. A read that was already in flight was
  // composed by the daemon BEFORE the toggle was stored, so its rows still
  // show the old state; letting it land would flip the switch back while the
  // next turn honours the toggle, and nothing re-reads to correct it.
  const writeSeq = useRef(0);
  /**
   * Toggle writes still out.
   *
   * STATE, not a ref, and separate from the read's `pending`: a write outlives
   * both the list being closed and any read that resolves meanwhile, and each
   * of those clears `pending`. Folded into one flag, closing the popover mid
   * write — or simply letting a cached read land — put the switch back in play
   * while the daemon had yet to answer, reopening the double-write race the
   * flag exists to close.
   */
  const [writing, setWriting] = useState(0);
  /**
   * Re-read WITHOUT bypassing the daemon's cache. A toggle is stored per
   * (agent, folder) and the daemon merges the disabled set on every exit path
   * — cache hits included — so the other scopes of that agent can be corrected
   * for the price of a cached read, rather than re-dialling the user's servers
   * the way {@link refresh} deliberately does.
   */
  const [rereadToken, setRereadToken] = useState(0);
  // Serialized rather than joined on a single byte: a scope is two fields, and
  // flattening them would let ('a', 'b/c') and ('a/b', 'c') collide.
  const scopesKey = JSON.stringify(
    scopes.map((scope) => [scope.agent, scope.pluginDir ?? '']),
  );
  /**
   * Identity of the question being asked — which scopes, in which folder.
   *
   * Declared with the pending-retry block below it rather than beside the
   * render-time reads, because the read effect's dependency list needs the
   * retry token, and a hook cannot be referenced before it is called.
   */
  const readScope = `${scopesKey}\u0000${cwd ?? ''}`;

  // Answers for a different folder are not this folder's answers.
  const byScope =
    answered.scope === readScope ? answered.byScope : EMPTY_LISTINGS;
  /**
   * A scope the daemon is still reading. Empty rows under this flag are NOT a
   * claim that the folder has no servers — the daemon says so explicitly so the
   * two cannot be confused, and the panel must not settle on the empty one.
   */
  const stillReading = [...byScope.values()].some((listing) => listing.pending);
  // A PLAIN re-read, never a refresh: the dial the daemon already has running
  // is the one being waited on, and bypassing its cache would start a SECOND
  // one — launching the user's MCP servers all over again. The read effect
  // below therefore takes this token WITHOUT setting `refresh`.
  const pendingRetryToken = usePendingRetry(answered, stillReading && enabled);

  // `scopes` is a fresh array on every render of the caller, so keying the read
  // effect on it directly would re-dial the user's MCP servers on every render
  // of the panel. `scopesKey` IS its content, so this hands the effect an
  // identity that changes exactly when the content does — and hands it the
  // TYPED scopes, rather than a `JSON.parse` of the key that would have to
  // assert its way back to `CliKind`.
  //
  // Depending on `scopesKey` rather than on `scopes` is the whole point, and is
  // what an exhaustive-deps lint would object to if this repo ran one.
  const targetScopes = useMemo(() => scopes, [scopesKey]);

  useEffect(() => {
    if (!enabled) {
      // Deliberately BEFORE the token is consumed: a refresh cannot be raised
      // while the list is closed (its control lives inside), and leaving the
      // token unspent keeps this a pure no-op rather than a state change.
      setPending(false);
      return;
    }
    const bypassCache = reloadToken > consumedToken.current;
    // Spent even when there is nothing to ask: a refresh raised with no folder
    // in scope must not be banked and then applied to whichever folder the
    // user opens next, which would re-dial a read nobody asked to refresh.
    consumedToken.current = reloadToken;
    if (cwd === null || targetScopes.length === 0) {
      setAnswered({ scope: readScope, byScope: EMPTY_LISTINGS });
      // Also clears a spinner left by a read that was in flight when the run
      // lost its folder — nothing below will resolve to clear it.
      setPending(false);
      return;
    }
    let stale = false;
    const startedAtWrite = writeSeq.current;
    setPending(true);
    void Promise.all(
      targetScopes.map(async (scope): Promise<[string, AgentMcpListing]> => {
        try {
          return [
            mcpScopeKey(scope),
            await agentsApi.listAgentMcpServers(
              {
                agent: scope.agent,
                cwd,
                ...(scope.pluginDir ? { pluginDir: scope.pluginDir } : {}),
                ...(bypassCache ? { refresh: 'true' } : {}),
              },
              { signal: AbortSignal.timeout(MCP_ROUTE_TIMEOUT_MS) },
            ),
          ];
        } catch (err) {
          // A transport failure is OURS, not a fact about the user's config.
          // It still needs a sentence: an empty listing with no reason is what
          // the panel renders as "No servers", so returning one here would
          // undo the daemon's whole failure-vs-empty distinction at the last
          // hop.
          //
          // The reason the daemon produced is CARRIED THROUGH rather than
          // replaced. `daemon-api.ts` already shapes every failure into one
          // line, and dropping it left the panel saying only that something
          // went wrong — with no way to tell a timeout from a missing binary
          // from a folder the CLI refused to read.
          return [
            mcpScopeKey(scope),
            {
              servers: [],
              unavailableReason: transportReason(err),
              // Null, not a sentence invented here: the note is the DAEMON's
              // statement about a CLI, and this listing exists precisely
              // because the daemon never answered.
              interactiveOnlyNote: null,
              // Settled, not still being read: the request never reached an
              // answer, so asking again on a timer would retry forever.
              pending: false,
            },
          ];
        }
      }),
    ).then((entries) => {
      if (stale || writeSeq.current !== startedAtWrite) {
        return;
      }
      setAnswered({ scope: readScope, byScope: new Map(entries) });
      setPending(false);
    });
    return () => {
      // Guards against out-of-order resolution AND against setting state on a
      // panel the user has already closed.
      stale = true;
    };
  }, [
    agentsApi,
    targetScopes,
    cwd,
    readScope,
    reloadToken,
    rereadToken,
    pendingRetryToken,
    enabled,
  ]);

  const refresh = useCallback(() => {
    setReloadToken((token) => token + 1);
  }, []);

  const [toggleError, setToggleError] = useState<string | null>(null);
  const dismissToggleError = useCallback(() => setToggleError(null), []);

  const setEnabled = useCallback(
    (kind: CliKind, server: string, enabled: boolean) => {
      if (cwd === null) {
        return;
      }
      setToggleError(null);
      setPending(true);
      setWriting((count) => count + 1);
      void agentsApi
        .setAgentMcpServerEnabled(
          {
            setMcpServerEnabledDto: { agent: kind, cwd, server, enabled },
          },
          // Its handler recomposes the listing, which re-dials on a lapsed
          // cache — so this write reaches the same slow path the read does.
          { signal: AbortSignal.timeout(MCP_ROUTE_TIMEOUT_MS) },
        )
        .then((listing) => {
          writeSeq.current += 1;
          setAnswered((prev) => {
            // The folder may have changed while the write was in flight.
            // Landing this answer in the new folder's map would state one
            // folder's servers as another's.
            if (prev.scope !== readScope) {
              return prev;
            }
            // Applied ONLY to the plugin-less scope of that CLI, because that
            // is the one the write's answer describes: the toggle route takes
            // no plugin directory, so its recomposed listing is the folder's
            // servers alone. Painting it onto a scope that carries a plugin
            // would drop exactly the servers that plugin contributes.
            const key = mcpScopeKey({ agent: kind, pluginDir: null });
            if (!prev.byScope.has(key)) {
              return prev;
            }
            const byScope = new Map(prev.byScope);
            byScope.set(key, listing);
            return { scope: prev.scope, byScope };
          });
          // Any OTHER scope of that CLI now carries a stale `disabled` flag —
          // the store is per (agent, folder), so one toggle applies to all of
          // them. A plain re-read corrects them off the daemon's cache.
          //
          // Only when such a scope EXISTS. With the single scope every chat
          // and most workflows have, the write's own answer is already the
          // whole truth, and re-reading would spend a round trip to replace it
          // with a value that cannot differ.
          if (scopes.some((s) => s.agent === kind && s.pluginDir !== null)) {
            setRereadToken((token) => token + 1);
          }
        })
        .catch((err: unknown) => {
          // The daemon's own sentence when it has one — it explains WHY the
          // toggle was refused, which a generic message cannot.
          setToggleError(err instanceof Error ? err.message : TOGGLE_FAILURE);
        })
        .finally(() => {
          setWriting((count) => count - 1);
          setPending(false);
        });
    },
    [agentsApi, cwd, readScope, scopes],
  );

  // "Asked for, not answered yet" counts as loading. The effect runs after
  // paint, so without this the panel renders one frame of "No servers" — a
  // claim about the user's configuration — before it has asked anything.
  //
  // `enabled` first: with nothing showing the listing, nothing has been asked
  // for, so there is nothing to be awaiting. Without it a closed list reports
  // `loading` forever — a spinner on a control the user has not pressed, and a
  // refresh button disabled before it was ever available.
  const awaitingFirstAnswer =
    enabled && cwd !== null && scopes.length > 0 && byScope.size === 0;

  return {
    byScope,
    // `stillReading` included, or the panel would drop its spinner and render
    // the daemon's placeholder empty rows as "No servers" — the exact claim
    // the `pending` flag exists to withhold.
    loading: pending || writing > 0 || awaitingFirstAnswer || stillReading,
    refresh,
    setEnabled,
    toggleError,
    dismissToggleError,
  };
}
