import { useCallback, useEffect, useRef, useState } from 'react';

import type {
  ChatsApi,
  ItemDto as ChatItem,
  RunStateDto,
} from '../autogenerated';
import type { DaemonClient, RunStatusEvent } from '../daemon-client';
import { isArtifactToolName } from './artifact-payload';
import { isAgentToolName } from './tool-kind';

/**
 * Rows whose arrival can change what the run holds as a whole — a card opening
 * or closing, a call or delegate starting or ending, a command detaching or
 * finishing, a workflow announcing itself.
 */
const STRUCTURAL_KINDS = new Set<ChatItem['kind']>([
  'approval_request',
  'approval_verdict',
  'unanswerable',
  'call_started',
  'call_result',
  'subagent_info',
  'workflow_info',
  'shell_open',
  'shell_info',
]);

/**
 * A row that changes what the run holds as a whole: a structural kind, a tool
 * call that launches a delegate or publishes an artifact, or the reply to one
 * the state already lists — off the tail the window never sees any of them,
 * and a sync delegate writes no declaration to announce itself.
 */
function movesStructure(item: ChatItem, listed: ReadonlySet<string>): boolean {
  if (STRUCTURAL_KINDS.has(item.kind)) {
    return true;
  }
  const payload = item.payload as { name?: unknown; id?: unknown } | null;
  if (item.kind === 'tool_call' && typeof payload?.name === 'string') {
    return isAgentToolName(payload.name) || isArtifactToolName(payload.name);
  }
  return (
    item.kind === 'tool_result' &&
    typeof payload?.id === 'string' &&
    listed.has(payload.id)
  );
}

/** The tool-call ids the state lists — delegates, workflows, artifacts. */
function listedIds(state: RunStateDto): Set<string> {
  const ids = new Set(state.delegates.map((delegate) => delegate.id));
  for (const row of [...state.workflowRows, ...state.artifactRows]) {
    const id = (row.payload as { id?: unknown } | null)?.id;
    if (typeof id === 'string') {
      ids.add(id);
    }
  }
  return ids;
}

/**
 * How long a burst of such rows is gathered before one re-read. A fan-out
 * declares a dozen delegates in a second, and each is the same question.
 */
const REREAD_DELAY_MS = 400;

const EMPTY: RunStateDto = {
  openRequests: [],
  calls: [],
  delegates: [],
  workflowRows: [],
  artifactRows: [],
  shells: [],
  turnStartedAt: null,
};

interface Stamped {
  /** Which run this was read from — see the guard below. */
  runId: string | null;
  state: RunStateDto;
}

/** An announce that can move what the run holds, rather than what it is doing. */
function movesRunState(event: RunStatusEvent): boolean {
  return (
    event.status !== null ||
    event.awaiting !== undefined ||
    event.holdingFor !== undefined ||
    event.awaitingCalls !== undefined ||
    event.shellsOpen !== undefined ||
    event.subagentsOut !== undefined
  );
}

/**
 * What the OPEN run holds as a whole, read from the daemon
 * (`GET /v1/chats/:runId/state`) — its open cards, its calls, its delegates,
 * its running commands, its dynamic workflows, when its open turn began.
 *
 * Every readout that is not the transcript's own rows reads this rather than a
 * fold of the loaded window, which answers about the newest page while
 * presenting itself as the run. Where the window ALSO holds a thing, the
 * window's reading is fresher and wins; this fills in everything else.
 *
 * Kept current by what can move it, and nothing else: the run opening, a
 * reconnect, a structural row arriving on the socket, and a status announce
 * that is about the run's standing rather than its activity phrase. Both
 * socket triggers are read straight off the client, so the readouts stay live
 * while the reader has jumped to the middle of the conversation and the window
 * is not receiving live rows at all.
 */
export function useRunState(
  api: Pick<ChatsApi, 'readRunState'> | null,
  client: Pick<DaemonClient, 'onItem' | 'onRunStatus'> | null,
  runId: string | null,
  reconnectNonce: number,
): { state: RunStateDto; refresh: () => void } {
  const [read, setRead] = useState<Stamped>(() => ({ runId, state: EMPTY }));
  const listedRef = useRef<ReadonlySet<string>>(new Set());
  useEffect(() => {
    listedRef.current = listedIds(read.state);
  }, [read]);
  const [nonce, setNonce] = useState(0);
  const refresh = useCallback(() => setNonce((n) => n + 1), []);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (api === null || runId === null) {
      setRead({ runId, state: EMPTY });
      return;
    }
    let cancelled = false;
    void api
      .readRunState({ runId })
      .then((state) => {
        if (!cancelled) {
          setRead({ runId, state });
        }
      })
      // A state that could not be read leaves what the window holds standing,
      // never an error over a working conversation.
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, [api, runId, reconnectNonce, nonce]);

  useEffect(() => {
    if (client === null || runId === null) {
      return;
    }
    const schedule = (): void => {
      if (timerRef.current !== null) {
        return;
      }
      timerRef.current = setTimeout(() => {
        timerRef.current = null;
        refresh();
      }, REREAD_DELAY_MS);
    };
    const offItem = client.onItem((item) => {
      if (item.runId === runId && movesStructure(item, listedRef.current)) {
        schedule();
      }
    });
    const offStatus = client.onRunStatus((event) => {
      if (event.runId === runId && movesRunState(event)) {
        schedule();
      }
    });
    return () => {
      offItem();
      offStatus();
      if (timerRef.current !== null) {
        clearTimeout(timerRef.current);
        timerRef.current = null;
      }
    };
  }, [client, runId, refresh]);

  // Belongs to the run it was read from: a thread switch renders once before
  // the effect can replace it, and the previous conversation's cards and calls
  // under the new thread's name are the one place they could not be recognised
  // as stale.
  return { state: read.runId === runId ? read.state : EMPTY, refresh };
}
