import { useCallback } from 'react';

import type { CliKind } from '../../shared/contracts';
import type { AgentContextWindowListingDto } from '../autogenerated';
import type { DaemonApis } from '../daemon-api';
import { useAgentVocabulary } from './use-agent-vocabulary';

/** Nothing known yet — one frozen value, so an effect keyed on it is stable. */
const NOTHING_YET: AgentContextWindowListingDto = {
  windows: [],
  unavailableReason: null,
};

/**
 * The context-window sizes one agent CLI can run ONE MODEL at, as its adapter
 * reports them.
 *
 * The twin of {@link useAgentEfforts}, and per model even more strictly: swept
 * on the daemon side across a cursor account's thirty-four models, twelve carry
 * the setting at all and the vocabularies differ between them (`300k|1m`,
 * `272k|1m`, `200k|1m`). Nothing is hardcoded here — the sizes are the CLI's
 * own words, and the number they actually produce is what the agent then
 * reports about its own window, which the context meter already draws.
 *
 * A null model answers with the sentence saying a model has to be picked first:
 * unlike the effort chip there is no CLI-wide union to stand in, because a
 * window size means nothing apart from the model that offered it.
 *
 * An EMPTY list always arrives with its reason — this CLI has no such control,
 * this model runs at one fixed window, or the CLI could not be asked — so the
 * chip can say so rather than vanish. Caching (keyed by kind AND model), the
 * stale-response guard and the failure fallback are
 * {@link useAgentVocabulary}'s, shared with the model and effort pickers.
 */
export function useAgentContextWindows(
  agentsApi: DaemonApis['agents'] | null,
  kind: CliKind | null,
  model: string | null = null,
): AgentContextWindowListingDto {
  const fetchFor = useCallback(
    async (agent: CliKind) => [
      await agentsApi!.listAgentContextWindows({
        agent,
        // Omitted rather than sent empty — `''` is not the question the daemon
        // reads an absent model as.
        ...(model ? { model } : {}),
      }),
    ],
    [agentsApi, model],
  );
  const { items } = useAgentVocabulary<AgentContextWindowListingDto>(
    kind,
    agentsApi && fetchFor,
    // The cache key's second half: without it a model switch serves the
    // previous model's sizes, which is the defect this whole shape prevents.
    model,
  );
  return items[0] ?? NOTHING_YET;
}
