// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type {
  ChatsApi,
  ItemDto as ChatItem,
  RunDto as ChatRun,
  WorkflowsApi,
} from '../autogenerated';
import type {
  DaemonClient,
  RunStatusEvent,
  VerdictAck,
} from '../daemon-client';
import { type ChatRunState, useChatRun } from './use-chat-run';

(
  globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

const run1: ChatRun = {
  id: 'r1',
  status: 'running',
  awaiting: null,
  holdingFor: 0,
  title: 'My chat',
  agentKind: 'claude',
  workflowId: null,
  cwd: '/proj',
  model: null,
  approval: null,
  effort: null,
  contextWindow: null,
  contextTokens: null,
  contextWindowTokens: null,
  configDir: null,
  groupId: null,
  createdAt: 'now',
  updatedAt: 'now',
  lastMessage: null,
};
const run2: ChatRun = { ...run1, id: 'r2', title: 'Other chat' };

function msg(
  runId: string,
  seq: number,
  role: 'user' | 'assistant',
  text: string,
): ChatItem {
  return {
    id: `${runId}-i${seq}`,
    runId,
    nodeId: null,
    seq,
    kind: 'message',
    role,
    payload: { text },
    createdAt: 'now',
  };
}

/** A run-level turn end — what settles the working state and releases a queue. */
function turnEnd(
  runId: string,
  seq: number,
  kind: 'turn_complete' | 'turn_cancelled' = 'turn_complete',
): ChatItem {
  return {
    id: `${runId}-t${seq}`,
    runId,
    nodeId: null,
    seq,
    kind,
    role: null,
    payload: {},
    createdAt: 'now',
  };
}

/** A fake DaemonClient whose listeners the test fires by hand. */
function makeClient(): {
  client: DaemonClient;
  joinRun: ReturnType<typeof vi.fn>;
  leaveRun: ReturnType<typeof vi.fn>;
  emitItem: (item: ChatItem) => void;
  emitRunStatus: (event: RunStatusEvent) => void;
  fireDisconnect: () => void;
  fireReconnect: (error?: Error) => void;
  fireVerdictAck: (ack: VerdictAck) => void;
  listenerCount: () => number;
} {
  let itemListener: ((item: ChatItem) => void) | null = null;
  let runStatusListener: ((event: RunStatusEvent) => void) | null = null;
  let disconnectListener: (() => void) | null = null;
  let reconnectListener: ((error?: Error) => void) | null = null;
  let verdictAckListener: ((ack: VerdictAck) => void) | null = null;
  let liveTextSubscribed = false;
  const joinRun = vi.fn(async () => {});
  const leaveRun = vi.fn();
  const client = {
    onItem: (l: (item: ChatItem) => void) => {
      itemListener = l;
      return () => {
        itemListener = null;
      };
    },
    onRunStatus: (l: (event: RunStatusEvent) => void) => {
      runStatusListener = l;
      return () => {
        runStatusListener = null;
      };
    },
    onDisconnect: (l: () => void) => {
      disconnectListener = l;
      return () => {
        disconnectListener = null;
      };
    },
    onReconnect: (l: (error?: Error) => void) => {
      reconnectListener = l;
      return () => {
        reconnectListener = null;
      };
    },
    onVerdictAck: (l: (ack: VerdictAck) => void) => {
      verdictAckListener = l;
      return () => {
        verdictAckListener = null;
      };
    },
    onLiveText: () => {
      liveTextSubscribed = true;
      return () => {
        liveTextSubscribed = false;
      };
    },
    joinRun,
    leaveRun,
  } as unknown as DaemonClient;
  return {
    client,
    joinRun,
    leaveRun,
    emitItem: (item) => itemListener?.(item),
    emitRunStatus: (event) => runStatusListener?.(event),
    fireDisconnect: () => disconnectListener?.(),
    fireReconnect: (error) => reconnectListener?.(error),
    fireVerdictAck: (ack) => verdictAckListener?.(ack),
    listenerCount: () =>
      [
        itemListener,
        runStatusListener,
        disconnectListener,
        reconnectListener,
        verdictAckListener,
        liveTextSubscribed ? true : null,
      ].filter(Boolean).length,
  };
}

const chatApi = vi.hoisted(() => ({
  listChats: vi.fn(),
  listRunItems: vi.fn(),
}));
const workflowApi = vi.hoisted(() => ({ listWorkflowRuns: vi.fn() }));

let root: Root | null = null;
let container: HTMLDivElement | null = null;

beforeEach(() => {
  chatApi.listChats.mockReset().mockResolvedValue([run1, run2]);
  chatApi.listRunItems.mockReset().mockResolvedValue([]);
  workflowApi.listWorkflowRuns.mockReset().mockResolvedValue([]);
});

afterEach(() => {
  act(() => {
    root?.unmount();
  });
  container?.remove();
  root = null;
  container = null;
});

interface Harness {
  state: () => ChatRunState;
  swapDraft: ReturnType<typeof vi.fn>;
  resetSteerStatus: ReturnType<typeof vi.fn>;
  drain: ReturnType<typeof vi.fn>;
  /** Which runs the composer is holding follow-ups for. */
  queued: Set<string>;
  unmount: () => void;
}

/** Drive the hook alone, through a probe component that renders nothing. */
async function mount(client: DaemonClient): Promise<Harness> {
  let latest: ChatRunState | null = null;
  const swapDraft = vi.fn();
  const resetSteerStatus = vi.fn();
  const drain = vi.fn();
  const queued = new Set<string>();
  const drainQueueRef = { current: drain };
  function Probe(): null {
    latest = useChatRun({
      client,
      chatApi: chatApi as unknown as ChatsApi,
      workflowApi: workflowApi as unknown as WorkflowsApi,
      swapDraft,
      resetSteerStatus,
      hasQueuedMessages: (runId) => queued.has(runId),
      drainQueueRef,
    });
    return null;
  }
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
  await act(async () => {
    root?.render(<Probe />);
  });
  return {
    state: () => {
      if (latest === null) {
        throw new Error('the hook has not rendered');
      }
      return latest;
    },
    swapDraft,
    resetSteerStatus,
    drain,
    queued,
    unmount: () => {
      act(() => {
        root?.unmount();
      });
      root = null;
    },
  };
}

/** Open a thread and let its join + history replay settle. */
async function open(harness: Harness, runId: string): Promise<void> {
  await act(async () => {
    await harness.state().activateRun(runId);
  });
}

describe('useChatRun', () => {
  it('loads the run list on mount and reports the fetch as settled', async () => {
    const { client } = makeClient();
    const harness = await mount(client);

    expect(harness.state().runs.map((run) => run.id)).toEqual(['r1', 'r2']);
    expect(harness.state().runsLoaded).toBe(true);
  });

  it('leaves the previous room before joining the next, and empties the transcript', async () => {
    const { client, joinRun, leaveRun } = makeClient();
    chatApi.listRunItems.mockResolvedValue([msg('r1', 0, 'user', 'hello')]);
    const harness = await mount(client);

    await open(harness, 'r1');
    expect(harness.state().items).toHaveLength(1);

    chatApi.listRunItems.mockResolvedValue([]);
    await open(harness, 'r2');

    expect(leaveRun).toHaveBeenCalledWith('r1');
    expect(joinRun).toHaveBeenNthCalledWith(2, 'r2');
    // r1's rows must not survive into r2's transcript.
    expect(harness.state().items).toEqual([]);
    expect(harness.state().activeRunId).toBe('r2');
    // A Send-now outcome belongs to the run it was pressed in.
    expect(harness.resetSteerStatus).toHaveBeenCalled();
    // The draft plane is told about the switch; re-opening the SAME thread is
    // not a switch and must not swap a draft out and back.
    expect(harness.swapDraft).toHaveBeenCalledWith('r1', 'r2');
    harness.swapDraft.mockClear();
    await open(harness, 'r2');
    expect(harness.swapDraft).not.toHaveBeenCalled();
  });

  it('renders a live item for the open run and drops one for another', async () => {
    const { client, emitItem } = makeClient();
    const harness = await mount(client);
    await open(harness, 'r1');

    await act(async () => {
      emitItem(msg('r1', 1, 'assistant', 'mine'));
      emitItem(msg('r2', 1, 'assistant', 'not mine'));
    });

    expect(harness.state().items.map((item) => item.id)).toEqual(['r1-i1']);
  });

  it('de-dupes a re-delivered item by ID and keeps the transcript seq-ordered', async () => {
    const { client, emitItem } = makeClient();
    const harness = await mount(client);
    await open(harness, 'r1');

    await act(async () => {
      emitItem(msg('r1', 2, 'assistant', 'second'));
      emitItem(msg('r1', 1, 'user', 'first'));
      emitItem(msg('r1', 2, 'assistant', 'second'));
    });

    expect(harness.state().items.map((item) => item.seq)).toEqual([1, 2]);
  });

  it('settles the working state on a LIVE turn end but never on a replayed one', async () => {
    const { client, emitItem } = makeClient();
    // A working run whose transcript already holds a finished turn — the shape
    // that made a re-opened chat show Send while the daemon was still working.
    chatApi.listRunItems.mockResolvedValue([
      msg('r1', 0, 'user', 'go'),
      turnEnd('r1', 1),
      msg('r1', 2, 'user', 'again'),
    ]);
    const harness = await mount(client);
    await open(harness, 'r1');

    expect(harness.state().streaming).toBe(true);

    await act(async () => {
      emitItem(turnEnd('r1', 3));
    });

    expect(harness.state().streaming).toBe(false);
    // …and the live one mirrors its ending onto the sidebar row.
    expect(harness.state().runs.find((run) => run.id === 'r1')?.status).toBe(
      'completed',
    );
  });

  it('releases the queue on a live turn end, and never on a cancel', async () => {
    const { client, emitItem } = makeClient();
    const harness = await mount(client);
    harness.queued.add('r1');
    await open(harness, 'r1');

    await act(async () => {
      emitItem(turnEnd('r1', 1, 'turn_cancelled'));
    });
    // Stop is the user closing the door, not a cue to open a fresh turn.
    expect(harness.drain).not.toHaveBeenCalled();

    await act(async () => {
      emitItem(turnEnd('r1', 2));
    });
    expect(harness.drain).toHaveBeenCalledWith('r1');
  });

  it('releases a BACKGROUND run’s queue from the broadcast, leaving the open one to its own terminal item', async () => {
    const { client, emitRunStatus } = makeClient();
    const harness = await mount(client);
    harness.queued.add('r1');
    harness.queued.add('r2');
    await open(harness, 'r1');

    await act(async () => {
      emitRunStatus({ runId: 'r2', status: 'completed' } as RunStatusEvent);
      emitRunStatus({ runId: 'r1', status: 'completed' } as RunStatusEvent);
    });

    expect(harness.drain).toHaveBeenCalledTimes(1);
    expect(harness.drain).toHaveBeenCalledWith('r2');
  });

  it('updates a BACKGROUND thread’s preview line from the settle it never sees the items of', async () => {
    // REPORTED as "i see last chat message will not be updated (if AI wrote new
    // message) untill i will open this thread". `addItem` writes the preview
    // and returns early on any run but the open one, so r2's line stayed on
    // whatever the list was loaded with.
    const { client, emitRunStatus } = makeClient();
    const harness = await mount(client);
    await open(harness, 'r1');

    await act(async () => {
      emitRunStatus({
        runId: 'r2',
        status: 'completed',
        summary: 'main did not move — the tag points at the same commit.',
      } as RunStatusEvent);
    });

    expect(harness.state().runs.find((r) => r.id === 'r2')?.lastMessage).toBe(
      'main did not move — the tag points at the same commit.',
    );
  });

  it('keeps the preview a WORDLESS settle would otherwise blank', async () => {
    // `null` clears the notification's sentence — a turn that said nothing must
    // not re-announce the previous one's words — but the preview is the
    // thread's last MESSAGE, and a `/compact` turn did not delete it. The
    // daemon still holds the line and puts it back on the next refetch, so
    // blanking here would lose it for nothing.
    chatApi.listChats.mockResolvedValue([
      run1,
      { ...run2, lastMessage: 'the answer from before the compaction' },
    ]);
    const { client, emitRunStatus } = makeClient();
    const harness = await mount(client);
    await open(harness, 'r1');

    await act(async () => {
      emitRunStatus({
        runId: 'r2',
        status: 'completed',
        summary: null,
      } as RunStatusEvent);
    });

    expect(harness.state().runs.find((r) => r.id === 'r2')?.lastMessage).toBe(
      'the answer from before the compaction',
    );
  });

  it('releases the queue when the turn goes HELD, once per hold and not per report', async () => {
    const { client, emitRunStatus } = makeClient();
    const harness = await mount(client);
    harness.queued.add('r1');
    await open(harness, 'r1');

    await act(async () => {
      emitRunStatus({ runId: 'r1', holdingFor: 2 } as RunStatusEvent);
    });
    expect(harness.drain).toHaveBeenCalledWith('r1');

    // A hold re-announces on every unit that reports. The queue leaves one
    // message per turn, so a second drain here would fire the whole strip into
    // the same one.
    await act(async () => {
      emitRunStatus({ runId: 'r1', holdingFor: 1 } as RunStatusEvent);
    });
    expect(harness.drain).toHaveBeenCalledTimes(1);
  });

  it('releases the queue of a HELD run on opening it, with no terminal row in the transcript', async () => {
    // The daemon DEFERS the terminal row while it holds, so this transcript is
    // what a held turn's really looks like: the agent's last message, and
    // nothing after it.
    chatApi.listChats.mockResolvedValue([{ ...run1, holdingFor: 3 }, run2]);
    chatApi.listRunItems.mockResolvedValue([
      msg('r1', 1, 'user', 'go'),
      msg('r1', 2, 'assistant', 'launched two agents'),
    ]);
    const { client } = makeClient();
    const harness = await mount(client);
    harness.queued.add('r1');

    await open(harness, 'r1');

    expect(harness.drain).toHaveBeenCalledWith('r1');
  });

  it('fetches only the delta past the last rendered seq after a reconnect', async () => {
    const { client, emitItem, fireDisconnect, fireReconnect } = makeClient();
    const harness = await mount(client);
    await open(harness, 'r1');
    await act(async () => {
      emitItem(msg('r1', 7, 'assistant', 'before the drop'));
    });

    chatApi.listRunItems.mockResolvedValue([msg('r1', 8, 'user', 'missed')]);
    await act(async () => {
      fireDisconnect();
      fireReconnect();
      await Promise.resolve();
    });

    expect(chatApi.listRunItems).toHaveBeenLastCalledWith({
      runId: 'r1',
      afterSeq: 7,
    });
    expect(harness.state().items.map((item) => item.seq)).toEqual([7, 8]);
  });

  it('surfaces a failed re-join instead of fetching a delta against it', async () => {
    const { client, fireReconnect } = makeClient();
    const harness = await mount(client);
    await open(harness, 'r1');
    chatApi.listRunItems.mockClear();

    await act(async () => {
      fireReconnect(new Error('run room was left before joining'));
    });

    expect(harness.state().error).toBe('run room was left before joining');
    expect(chatApi.listRunItems).not.toHaveBeenCalled();
  });

  it('closes the open thread by leaving its room', async () => {
    const { client, leaveRun } = makeClient();
    chatApi.listRunItems.mockResolvedValue([msg('r1', 0, 'user', 'hello')]);
    const harness = await mount(client);
    await open(harness, 'r1');

    await act(async () => {
      harness.state().deactivateRun();
    });

    expect(leaveRun).toHaveBeenCalledWith('r1');
    expect(harness.state().activeRunId).toBeNull();
    expect(harness.state().items).toEqual([]);
    expect(harness.state().streaming).toBe(false);
    expect(harness.swapDraft).toHaveBeenLastCalledWith('r1', null);
  });

  it('leaves the room and drops every listener when the screen goes away', async () => {
    const { client, leaveRun, listenerCount } = makeClient();
    const harness = await mount(client);
    await open(harness, 'r1');
    expect(listenerCount()).toBe(6);

    harness.unmount();

    expect(leaveRun).toHaveBeenCalledWith('r1');
    expect(listenerCount()).toBe(0);
  });

  it('records an EXPIRED verdict for the open run, and only that', async () => {
    const { client, fireVerdictAck } = makeClient();
    const harness = await mount(client);
    await open(harness, 'r1');

    await act(async () => {
      fireVerdictAck({ runId: 'r1', requestId: 'q1', status: 'expired' });
      // Retryable, so the card must stay live.
      fireVerdictAck({ runId: 'r1', requestId: 'q2', status: 'invalid' });
      // Another thread's card is not this transcript's business.
      fireVerdictAck({ runId: 'r2', requestId: 'q3', status: 'expired' });
    });

    expect([...harness.state().deadRequestKeys]).toEqual(['r1:q1']);
  });
});
