// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, describe, expect, it } from 'vitest';

import type { ItemDto as ChatItem } from '../autogenerated';
import { ActiveWorkflowChips } from './composer-shelf';
import {
  buildWorkflowCards,
  groupTranscript,
  type ToolGroupEntry,
  workflowCardStatus,
  type WorkflowEntry,
} from './transcript-groups';
import { WorkflowCard } from './workflow-block';

let seq = 0;
function item(kind: ChatItem['kind'], payload: unknown): ChatItem {
  seq += 1;
  return {
    id: `i-${seq}`,
    runId: 'run-1',
    nodeId: null,
    seq,
    kind,
    role: null,
    payload,
    createdAt: `2026-08-30T00:00:${String(seq).padStart(2, '0')}.000Z`,
  };
}

const agent = (
  index: number,
  over: Record<string, unknown> = {},
): Record<string, unknown> => ({
  index,
  label: `probe-${index}`,
  phase: 'Probe',
  state: 'done',
  model: 'claude-haiku-4-5-20251001',
  tokens: 13779,
  toolCalls: 0,
  durationMs: 1303,
  error: null,
  ...over,
});

const info = (over: Record<string, unknown> = {}): ChatItem =>
  item('workflow_info', {
    id: 'toolu_wf',
    name: 'probe-run',
    title: 'Two trivial agents',
    activity: 'Probe: probe-2',
    tokens: 27559,
    toolUses: 0,
    durationMs: 2432,
    agents: [agent(1), agent(2)],
    ...over,
  });

const fold = (items: ChatItem[]): ReturnType<typeof buildWorkflowCards> =>
  buildWorkflowCards(groupTranscript(items), items);

const cards = (items: ChatItem[]): WorkflowEntry[] =>
  fold(items).filter(
    (entry): entry is WorkflowEntry => entry.type === 'workflow',
  );

describe('buildWorkflowCards', () => {
  it('replaces the launching tool pair with the card that describes it', () => {
    // The card already says a workflow ran, what it spawned and how it ended,
    // so leaving the pair in the group prints a poorer telling of the same
    // thing directly above it ("Used 1 tool").
    const entries = fold([
      item('tool_call', {
        id: 'toolu_wf',
        name: 'Workflow',
        input: { script: 'export const meta = {}' },
      }),
      item('tool_result', { id: 'toolu_wf', name: null, result: 'done' }),
      info(),
    ]);
    expect(entries.map((entry) => entry.type)).toEqual(['workflow']);
  });

  it('leaves the turn’s OTHER tool calls in their group', () => {
    const entries = fold([
      item('tool_call', { id: 'c1', name: 'Read', input: {} }),
      item('tool_result', { id: 'c1', name: null, result: 'ok' }),
      item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
      info(),
    ]);
    const group = entries.find(
      (entry): entry is ToolGroupEntry => entry.type === 'tools',
    );
    expect(group?.pairs).toHaveLength(1);
    // AFTER the group, so a turn that both worked and launched a workflow reads
    // in the order it happened.
    expect(entries.map((entry) => entry.type)).toEqual(['tools', 'workflow']);
  });

  it('recognises a workflow by the DAEMON’s row, never by the tool’s name', () => {
    // Which calls launched a workflow is the adapter layer's fact and it is
    // stated on the wire — so a second CLI growing an orchestrator is a daemon
    // change alone, and this fold never learns that claude spells its
    // `Workflow`.
    const entries = fold([
      item('tool_call', { id: 'toolu_wf', name: 'orchestrate', input: {} }),
      info(),
    ]);
    expect(entries.map((entry) => entry.type)).toEqual(['workflow']);
  });

  it('cards a workflow whose launching call is not in the window', () => {
    // A long thread pages its transcript, so the call can fall out from under
    // the rows describing it. The daemon's rows are the evidence it ran, and
    // dropping the card would drop the most expensive thing in the chat.
    const [card] = cards([info()]);
    expect(card?.workflow.name).toBe('probe-run');
    expect(card?.returned).toBe(false);
  });

  it('folds every announcement into ONE card', () => {
    // A workflow announces itself once per roster change — dozens of times over
    // a run — and every announcement is a fresh snapshot of the SAME work.
    expect(
      cards([
        item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
        info({ agents: null, tokens: null }),
        info({ agents: [agent(1)], tokens: 13779 }),
        info(),
      ]),
    ).toHaveLength(1);
  });

  it('keeps a workflow row from chopping the turn’s tool group in two', () => {
    // The rows land mid-turn and render nothing; treated as the node "saying
    // something" they would close the open group, turning one run of tools into
    // a column of one-call rows for rows nobody can see.
    const entries = fold([
      item('tool_call', { id: 'c1', name: 'Read', input: {} }),
      info({ id: 'other-call' }),
      item('tool_call', { id: 'c2', name: 'Read', input: {} }),
    ]);
    const groups = entries.filter((entry) => entry.type === 'tools');
    expect(groups).toHaveLength(1);
  });

  it('carries the script and the result onto the card', () => {
    const [card] = cards([
      item('tool_call', {
        id: 'toolu_wf',
        name: 'Workflow',
        input: { script: "phase('Probe')" },
      }),
      // A workflow the agent WAITED for sends its last roster before the call
      // is answered — which is exactly what makes the answer its own report.
      info(),
      item('tool_result', {
        id: 'toolu_wf',
        name: null,
        result: '{"out":["ok1"]}',
      }),
    ]);
    expect(card?.script).toBe("phase('Probe')");
    expect(card?.result).toBe('{"out":["ok1"]}');
    expect(card?.failed).toBe(false);
    // Nothing arrived after the answer, so the answer IS the workflow's report.
    expect(card?.resultIsOwn).toBe(true);
  });

  it('refuses to call a BACKGROUNDED launch receipt the workflow’s result', () => {
    // Measured on 2.1.251: a backgrounded workflow answers its call in seconds
    // with `Workflow launched in background. Task ID: … Use /workflows to watch
    // live progress` — transcript paths and a command this app does not have —
    // and then works on. Decided structurally: a roster arrived AFTER the
    // answer, so the answer was plainly not the report.
    const [card] = cards([
      item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
      item('tool_result', {
        id: 'toolu_wf',
        name: null,
        result: 'Workflow launched in background. Task ID: waflo2zl2',
      }),
      info(),
    ]);
    expect(card?.resultIsOwn).toBe(false);
  });
});

describe('workflowCardStatus', () => {
  const entry = (over: Partial<WorkflowEntry>): WorkflowEntry => ({
    type: 'workflow',
    id: 'toolu_wf',
    createdAt: '2026-08-30T00:00:00.000Z',
    seq: 1,
    nodeId: null,
    parentToolUseId: null,
    workflow: {
      id: 'toolu_wf',
      name: 'probe-run',
      title: null,
      activity: null,
      tokens: null,
      toolUses: null,
      durationMs: null,
      agents: null,
    },
    script: null,
    returned: false,
    failed: false,
    result: null,
    resultIsOwn: true,
    lastRowAt: null,
    ...over,
  });

  const roster = (state: string): Partial<WorkflowEntry> => ({
    workflow: {
      id: 'toolu_wf',
      name: 'probe-run',
      title: null,
      activity: null,
      tokens: null,
      toolUses: null,
      durationMs: null,
      agents: [
        {
          index: 1,
          label: 'probe-1',
          phase: null,
          state: state as 'running' | 'done' | 'failed',
          model: null,
          tokens: null,
          toolCalls: null,
          durationMs: null,
          error: null,
        },
      ],
    },
  });

  it('is running until the launching call answers', () => {
    expect(workflowCardStatus(entry({}))).toBe('running');
    expect(workflowCardStatus(entry({ returned: true }))).toBe('completed');
    expect(workflowCardStatus(entry({ returned: true, failed: true }))).toBe(
      'failed',
    );
  });

  it('believes the ROSTER over a call that returned while agents run on', () => {
    // A BACKGROUNDED workflow answers its call in seconds — "The workflow is
    // running in the background — I'll report when it completes" — and works
    // on. Observed live on 2.1.251 through this card, which read `completed`
    // beside its own header saying `3 agents · 1 running`.
    expect(
      workflowCardStatus(entry({ returned: true, ...roster('running') })),
    ).toBe('running');
    expect(
      workflowCardStatus(entry({ returned: true, ...roster('done') })),
    ).toBe('completed');
  });

  it('stops believing the roster once the RUN is over', () => {
    // With the CLI gone, an agent left `running` on the last roster is
    // unreported work rather than running work — and reading it as running
    // latches the spinner on for good.
    expect(workflowCardStatus(entry({ ...roster('running') }), 'unknown')).toBe(
      'stopped',
    );
  });

  it('is stopped when the run ended without the call ever answering', () => {
    expect(workflowCardStatus(entry({}), 'unknown')).toBe('stopped');
  });

  it('is still running when the workflow has spoken SINCE the run settled', () => {
    // The transcript is the evidence and the status is the claim: a run row
    // settling used to paint every unreturned card at once, including ones
    // whose rows were still landing.
    expect(workflowCardStatus(entry({ lastRowAt: 2_000 }), 1_000)).toBe(
      'running',
    );
    expect(workflowCardStatus(entry({ lastRowAt: 500 }), 1_000)).toBe(
      'stopped',
    );
  });
});

describe('WorkflowCard', () => {
  let container: HTMLElement;
  let root: Root;

  const render = (entry: WorkflowEntry): void => {
    container = document.createElement('div');
    document.body.append(container);
    root = createRoot(container);
    act(() => {
      root.render(<WorkflowCard entry={entry} />);
    });
  };

  afterEach(() => {
    act(() => root.unmount());
    container.remove();
  });

  const cardOf = (items: ChatItem[]): WorkflowEntry => {
    const [card] = cards(items);
    if (card === undefined) {
      throw new Error('no workflow card was built');
    }
    return card;
  };

  it('states the fleet and the bill with the card still SHUT', () => {
    // The whole complaint this answers: a workflow was `running Workflow ·
    // 20m 34s` and nothing else, for what is routinely the most expensive tool
    // call in a conversation.
    render(
      cardOf([
        item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
        info({
          agents: [agent(1), agent(2, { state: 'running' }), agent(3)],
        }),
      ]),
    );
    const facts = container.querySelector('[data-slot="workflow-facts"]');
    expect(facts?.textContent).toContain('3 agents · 1 running · 27.6k tokens');
    // Shut: the roster is behind the disclosure, the headline is not.
    expect(
      container.querySelectorAll('[data-slot="workflow-agent"]'),
    ).toHaveLength(0);
    expect(container.textContent).toContain('probe-run');
  });

  it('says nothing about failures when there are none', () => {
    // `1 agent · 0 failed` is the same fact plus a zero nobody asked for — and
    // a SETTLED workflow's header carries no clock either.
    render(
      cardOf([
        item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
        item('tool_result', { id: 'toolu_wf', name: null, result: 'ok' }),
        info({ agents: [agent(1)], tokens: 13779 }),
      ]),
    );
    const facts = container.querySelector('[data-slot="workflow-facts"]');
    expect(facts?.textContent).toBe('1 agent · 13.8k tokens');
  });

  it('counts real seconds while the workflow is still out', () => {
    // The CLI's own `duration_ms` rides the last roster it sent, so it freezes
    // between announcements — and the row this card replaced (`running
    // Workflow · 20m 34s`) had a clock that did not. Counted from the launching
    // call, which is why this card is built with one timed to now.
    render(
      cardOf([
        {
          ...item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
          createdAt: new Date(Date.now() - 4_000).toISOString(),
        },
        info({ agents: [agent(1)], tokens: 13779 }),
      ]),
    );
    const facts = container.querySelector('[data-slot="workflow-facts"]');
    expect(facts?.textContent).toMatch(/^1 agent · 13\.8k tokens · \ds$/);
  });

  it('opens onto the roster, in the workflow’s OWN numbering', () => {
    // The CLI merges its roster by index and re-emits it, so the array's order
    // is the order agents were first SEEN — under `parallel()` that is a race.
    render(
      cardOf([
        item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
        info({
          agents: [agent(3), agent(1), agent(2, { state: 'failed' })],
        }),
      ]),
    );
    act(() => container.querySelector('button')?.click());
    const rows = [
      ...container.querySelectorAll('[data-slot="workflow-agent"]'),
    ];
    expect(
      rows.map((row) => row.querySelector('span:nth-child(2)')?.textContent),
    ).toEqual(['probe-1', 'probe-2', 'probe-3']);
    // The state is the row's own attribute, so a reader scanning for the one
    // that failed has something to find and a test something to assert.
    expect(rows.map((row) => row.getAttribute('data-state'))).toEqual([
      'done',
      'failed',
      'done',
    ]);
  });

  it('captions the roster once per phase, not once per agent', () => {
    render(
      cardOf([
        item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
        info({
          agents: [
            agent(1, { phase: 'Find' }),
            agent(2, { phase: 'Find' }),
            agent(3, { phase: 'Verify' }),
          ],
        }),
      ]),
    );
    act(() => container.querySelector('button')?.click());
    expect(
      [...container.querySelectorAll('[data-slot="workflow-phase"]')].map(
        (row) => row.textContent,
      ),
    ).toEqual(['Find', 'Verify']);
  });

  it('shows the workflow’s own answer and hides a launch receipt', () => {
    const withReceipt = cardOf([
      item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
      item('tool_result', {
        id: 'toolu_wf',
        name: null,
        result: 'Workflow launched in background. Task ID: waflo2zl2',
      }),
      info(),
    ]);
    render(withReceipt);
    act(() => container.querySelector('button')?.click());
    expect(container.textContent).not.toContain('launched in background');
    // The same card WITH an own answer prints it, so the assertion above is
    // about the receipt and not about the panel being missing altogether.
    act(() => root.unmount());
    container.remove();
    render({ ...withReceipt, resultIsOwn: true });
    act(() => container.querySelector('button')?.click());
    expect(container.textContent).toContain('launched in background');
  });

  it('drops the live phrase once the workflow is over', () => {
    // The CLI phrases it as `Phase: label`, which after the workflow ends is
    // the last agent that happened to finish rather than any kind of summary.
    render(
      cardOf([
        item('tool_call', { id: 'toolu_wf', name: 'Workflow', input: {} }),
        item('tool_result', { id: 'toolu_wf', name: null, result: 'ok' }),
        info(),
      ]),
    );
    act(() => container.querySelector('button')?.click());
    expect(container.textContent).not.toContain('Probe: probe-2');
  });
});

describe('ActiveWorkflowChips', () => {
  let container: HTMLElement;
  let root: Root;

  const render = (workflows: WorkflowEntry[]): (() => string[]) => {
    container = document.createElement('div');
    document.body.append(container);
    root = createRoot(container);
    const revealed: string[] = [];
    act(() => {
      root.render(
        <ActiveWorkflowChips
          workflows={workflows}
          onReveal={(id) => revealed.push(id)}
        />,
      );
    });
    return () => revealed;
  };

  afterEach(() => {
    act(() => root.unmount());
    container.remove();
    localStorage.clear();
  });

  const workflow = (id: string, state: string): WorkflowEntry => {
    const [card] = cards([
      item('tool_call', { id, name: 'Workflow', input: {} }),
      item('workflow_info', {
        id,
        name: `wf-${id}`,
        title: null,
        activity: null,
        tokens: 13779,
        toolUses: 0,
        durationMs: 1000,
        agents: [agent(1, { state })],
      }),
      // A finished workflow has ANSWERED its call — a roster of settled agents
      // with the call still open is a workflow between phases, which is still
      // running and is exactly what `workflowCardStatus` says.
      ...(state === 'done'
        ? [item('tool_result', { id, name: null, result: 'ok' })]
        : []),
    ]);
    if (card === undefined) {
      throw new Error('no card');
    }
    return card;
  };

  it('names the workflow that is running and nothing else', () => {
    // A finished workflow is history with a card of its own; a running one is
    // the most expensive thing in the chat and is what the shelf is for.
    render([workflow('a', 'done')]);
    expect(container.querySelector('[data-slot="workflow-chip"]')).toBeNull();

    act(() => root.unmount());
    container.remove();
    render([workflow('a', 'done'), workflow('b', 'running')]);
    const chip = container.querySelector('[data-slot="workflow-chip"]');
    expect(chip?.getAttribute('data-workflow')).toBe('b');
    expect(chip?.textContent).toBe('wf-b1 agent · 1 running · 13.8k tokens');
  });

  it('shows ONE chip and a count, never a line of them', () => {
    // The shelf is a single line above the textarea; a row that grew with the
    // thread pushed the composer up the pane, which is the defect its
    // pull-request neighbour was rebuilt to fix.
    const revealed = render([
      workflow('a', 'running'),
      workflow('b', 'running'),
      workflow('c', 'running'),
    ]);
    expect(
      container.querySelectorAll('[data-slot="workflow-chip"]'),
    ).toHaveLength(1);
    const all = container.querySelector('button + button');
    expect(all?.textContent).toBe('All 3');
    act(() => (all as HTMLElement | null)?.click());
    // The press reaches the PANEL rather than growing the shelf.
    expect(localStorage.getItem('chats.agentsPanelCollapsed')).toBe('0');
    expect(revealed()).toEqual([]);
  });

  it('hands the chip’s press to the caller, which takes the reader to the card', () => {
    const revealed = render([workflow('b', 'running')]);
    act(() =>
      (
        container.querySelector(
          '[data-slot="workflow-chip"]',
        ) as HTMLElement | null
      )?.click(),
    );
    expect(revealed()).toEqual(['b']);
  });
});
