// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type { AgentIdentityCapability } from '../autogenerated';
import {
  NODE_DND_MIME,
  NodePalette,
  type PaletteItem,
  paletteNode,
  parsePaletteItem,
} from './node-palette';
import { NODE_CONNECTION_RULES, NODE_TYPE_SCHEMAS } from './node-schema';

(
  globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

/** The three registered CLIs, exactly as `GET /v1/capabilities` reports them. */
const AGENTS: AgentIdentityCapability[] = [
  {
    agent: 'claude',
    displayName: 'Claude',
    shortName: 'claude',
    summary: 'Anthropic Claude, driven headlessly via the claude CLI.',
    details: [
      'Runs one turn per node, headlessly through the claude CLI.',
      'Tool approvals are per-node — set the node to auto or ask.',
    ],
    icon: 'bot',
    callerEscalatesQuestions: true,
  },
  {
    agent: 'cursor-agent',
    displayName: 'Cursor',
    shortName: 'cursor',
    summary: 'cursor-agent CLI — honours per-node tool approvals.',
    details: [
      'Runs one turn per node, headlessly through the cursor-agent CLI.',
      'Signs itself in — Settings offers the sign-in; no API key to enter.',
    ],
    icon: 'terminal',
    callerEscalatesQuestions: false,
  },
  {
    agent: 'codex',
    displayName: 'Codex',
    shortName: 'codex',
    summary: 'OpenAI Codex, driven headlessly via the codex CLI.',
    details: ['Runs one turn per node, headlessly through the codex CLI.'],
    icon: 'code',
    callerEscalatesQuestions: true,
  },
];

let container: HTMLDivElement;
let root: Root;

beforeEach(() => {
  localStorage.clear(); // persisted width/fold state must not leak between tests
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
});

afterEach(() => {
  act(() => root.unmount());
  container.remove();
  vi.restoreAllMocks();
});

function render(
  agents: readonly AgentIdentityCapability[] = AGENTS,
  onAdd?: (item: PaletteItem) => void,
): void {
  act(() => {
    root.render(<NodePalette agents={agents} onAdd={onAdd} />);
  });
}

/** The draggable tiles (the fold/category buttons are not draggable). */
function tiles(): HTMLButtonElement[] {
  return Array.from(
    container.querySelectorAll<HTMLButtonElement>('button'),
  ).filter((b) => b.draggable);
}

function tileByLabel(label: string): HTMLButtonElement | undefined {
  return tiles().find((b) => b.textContent?.includes(label));
}

function byLabel(label: string): HTMLButtonElement | undefined {
  return Array.from(
    container.querySelectorAll<HTMLButtonElement>('button'),
  ).find((b) => b.getAttribute('aria-label') === label);
}

function click(el: Element | undefined): void {
  act(() => {
    el?.dispatchEvent(new MouseEvent('click', { bubbles: true }));
  });
}

function dialog(): Element | null {
  return container.querySelector('[role="dialog"]');
}

describe('NodePalette', () => {
  it('shows every node type at once — the categories do not fold', () => {
    // This REVERSES an earlier report ("by default all groups should be
    // collapsed"), and the reversal is deliberate rather than an oversight.
    // That report was about the panel being FULL: three expanded accordion
    // blocks, each a bordered box of bordered tiles, filled the column before
    // the user had asked for anything. The drawer holds one trigger, one tile
    // per registered agent, and one instruction block — five tiles today —
    // so what it costs unfolded is a handful of rows under three captions.
    //
    // The fold is gone rather than merely defaulted open, so there is no
    // `aria-expanded` left in the panel body at all.
    render();

    expect(tiles()).toHaveLength(1 + AGENTS.length + 1);
    const folds = Array.from(
      container.querySelectorAll<HTMLButtonElement>('button'),
    ).filter((b) => b.hasAttribute('aria-expanded'));
    expect(folds).toHaveLength(0);
  });

  it('renders one draggable tile per trigger, registered agent and instruction block', () => {
    render();
    expect(tiles()).toHaveLength(1 + AGENTS.length + 1); // Manual + 3 agents + Instructions
    expect(container.textContent).toContain('Triggers');
    expect(container.textContent).toContain('Agents');
    expect(container.textContent).toContain('Instructions');
    expect(container.textContent).toContain('Manual');
    expect(container.textContent).toContain('Claude');
    expect(container.textContent).toContain('Cursor');
    expect(container.textContent).toContain('Codex');
  });

  it('draws no agent tiles before capabilities have answered — never a guessed set', () => {
    // The honest rendering before `GET /v1/capabilities` lands is nothing, on
    // the same rule every other identity-driven surface in this app follows —
    // never a fallback list of CLI names invented here.
    render([]);
    expect(tiles()).toHaveLength(1 + 1); // Manual + Instructions, no agents
    expect(container.textContent).not.toContain('Claude');
    expect(container.textContent).not.toContain('Cursor');
    expect(container.textContent).not.toContain('Codex');
  });

  it('opens the info dialog on click — never adds a node', () => {
    // Clicking a tile must open its read-only details, not drop a node
    // (matches geniro: drag to add, click for info).
    render();
    click(tileByLabel('Claude'));

    expect(dialog()).not.toBeNull();
    expect(dialog()?.textContent).toContain('Claude');
    expect(dialog()?.textContent).toContain('claude'); // the CLI command
    expect(dialog()?.textContent).toContain('Drag this agent onto the canvas');
  });

  it('the info dialog offers a click/keyboard add path — "Add to canvas" fires onAdd and closes', () => {
    // Drag is not the only way in: keyboard users (and failed trackpad drags)
    // add through the dialog's button, which hands the item to the canvas's
    // position-less add (stack-to-the-right placement).
    const onAdd = vi.fn();
    render(AGENTS, onAdd);
    click(tileByLabel('Claude'));

    const add = Array.from(
      container.querySelectorAll<HTMLButtonElement>('button'),
    ).find((b) => b.textContent === 'Add to canvas');
    expect(add).toBeDefined();
    click(add);

    expect(onAdd).toHaveBeenCalledWith(
      expect.objectContaining({ kind: 'agent', agent: 'claude' }),
    );
    expect(dialog()).toBeNull();
  });

  it('without onAdd the info dialog stays drag-only (no Add button)', () => {
    render();
    click(tileByLabel('Claude'));

    expect(
      Array.from(container.querySelectorAll('button')).some(
        (b) => b.textContent === 'Add to canvas',
      ),
    ).toBe(false);
  });

  it("renders each kind's own schema in the info dialog", () => {
    render();
    const schemaKeys = (): string[] =>
      Array.from(
        container.querySelectorAll('[aria-label="Node schema"] code'),
      ).map((el) => el.textContent ?? '');

    click(tileByLabel('Claude'));
    expect(schemaKeys()).toEqual(NODE_TYPE_SCHEMAS.agent.map((f) => f.key));
    click(byLabel('Close'));

    click(tileByLabel('Manual'));
    expect(schemaKeys()).toEqual(NODE_TYPE_SCHEMAS.trigger.map((f) => f.key));
  });

  it('renders one connection-rule row per registry rule, with arity and every registered agent as a partner', () => {
    // The Connections section is driven by NODE_CONNECTION_RULES — one row
    // per input/output rule showing the accepted kind, its arity badge, and
    // the concrete node types matching the rule — the agent partners coming
    // from the SAME identity list the tiles are built from.
    render();
    click(tileByLabel('Claude'));

    const rules = container.querySelector('[aria-label="Connection rules"]');
    expect(rules).not.toBeNull();
    expect(rules?.textContent).toContain('Inputs');
    expect(rules?.textContent).toContain('Outputs');

    const rows = rules?.querySelectorAll('code') ?? [];
    const expected = [
      ...NODE_CONNECTION_RULES.agent.inputs,
      ...NODE_CONNECTION_RULES.agent.outputs,
    ];
    expect(Array.from(rows).map((el) => el.textContent)).toEqual(
      expected.map((rule) => rule.kind),
    );
    expect(rules?.textContent).toContain('multiple'); // agent→agent is multi-edge
    expect(rules?.textContent).toContain('single'); // trigger→agent is single
    // kind `agent` partners are every registered CLI, by its display name.
    expect(rules?.textContent).toContain('Claude');
    expect(rules?.textContent).toContain('Cursor');
    expect(rules?.textContent).toContain('Codex');
  });

  it("shows the trigger's empty input side as an explicit entry-point note", () => {
    render();
    click(tileByLabel('Manual'));

    const rules = container.querySelector('[aria-label="Connection rules"]');
    expect(rules?.textContent).toContain('None — nothing can feed a trigger');
    // Its one output rule starts ONE agent — the palette is where a user reads
    // that arity before they drag, so it is the surface the breaking change has
    // to reach. `multiple` here would mean the flip never got past the daemon.
    expect(rules?.textContent).toContain('single');
    expect(rules?.textContent).not.toContain('multiple');
  });

  it('closes the info dialog on ✕', () => {
    render();
    click(tiles()[0]);
    expect(dialog()).not.toBeNull();

    click(byLabel('Close'));
    expect(dialog()).toBeNull();
  });

  it('writes the palette item as JSON under the shared DND mime on drag start', () => {
    // The canvas drop handler reads NODE_DND_MIME back through
    // parsePaletteItem — pin the exact payload round-trip for both kinds.
    render();
    const setData = vi.fn();
    const drag = (tile: HTMLButtonElement | undefined): void => {
      const event = new Event('dragstart', {
        bubbles: true,
      }) as unknown as DragEvent;
      Object.defineProperty(event, 'dataTransfer', {
        value: { setData, effectAllowed: '' },
      });
      act(() => {
        tile?.dispatchEvent(event);
      });
    };

    drag(tileByLabel('Claude'));
    drag(tileByLabel('Manual'));

    const payloads = setData.mock.calls.map(([mime, payload]) => {
      expect(mime).toBe(NODE_DND_MIME);
      return parsePaletteItem(payload as string);
    });
    expect(payloads).toEqual([
      { kind: 'agent', agent: 'claude' },
      { kind: 'trigger', trigger: 'manual' },
    ]);
  });

  it('parsePaletteItem rejects garbage payloads', () => {
    expect(parsePaletteItem('')).toBeNull();
    expect(parsePaletteItem('not json')).toBeNull();
    expect(parsePaletteItem('{"kind":"agent","agent":"nope"}')).toBeNull();
    expect(parsePaletteItem('{"kind":"trigger","trigger":"cron"}')).toBeNull();
  });

  it('folds the whole panel to a rail and expands again', () => {
    render();
    expect(tiles()).toHaveLength(1 + AGENTS.length + 1);

    click(byLabel('Collapse palette'));
    expect(tiles()).toHaveLength(0); // folded — tiles gone

    click(byLabel('Expand palette'));
    expect(tiles()).toHaveLength(1 + AGENTS.length + 1);
  });

  it('starts FOLDED at phone width, where it left the canvas a sliver', () => {
    const real = window.matchMedia;
    window.matchMedia = ((query: string) => ({
      matches: query.includes('max-width'),
      media: query,
      addEventListener: () => undefined,
      removeEventListener: () => undefined,
    })) as unknown as typeof window.matchMedia;
    try {
      render();
      expect(tiles()).toHaveLength(0);
      expect(byLabel('Expand palette')).toBeDefined();
    } finally {
      window.matchMedia = real;
    }
  });

  it('keeps every category caption as a heading, not a control', () => {
    // The captions used to be the fold buttons. With the fold gone they must
    // become plain headings rather than buttons that do nothing — a dead
    // control is worse than no control, and it would still take a tab stop.
    render();

    const captions = Array.from(container.querySelectorAll('h3')).map(
      (h) => h.textContent,
    );
    expect(captions).toEqual(['Triggers', 'Agents', 'Instructions']);
    // Nothing in the panel body is pressable except the tiles and the
    // rail's own collapse control.
    const pressable = Array.from(
      container.querySelectorAll<HTMLButtonElement>('button'),
    ).filter((b) => !b.draggable);
    expect(pressable.map((b) => b.getAttribute('aria-label'))).toEqual([
      'Collapse palette',
    ]);
  });

  it('resizes on drag and persists the new width', () => {
    render();
    const width = (): number =>
      parseInt(container.querySelector('aside')!.style.width || '0', 10);
    const start = width(); // DEFAULT_WIDTH = 240
    const handle = container.querySelector('[role="separator"]')!;

    act(() => {
      handle.dispatchEvent(
        new MouseEvent('mousedown', { bubbles: true, clientX: 240 }),
      );
      window.dispatchEvent(new MouseEvent('mousemove', { clientX: 320 }));
      window.dispatchEvent(new MouseEvent('mouseup'));
    });

    expect(width()).toBe(start + 80); // 240 + (320 − 240)
    expect(localStorage.getItem('geniro.builder.paletteWidth')).toBe('320');
  });
});

describe('parsePaletteItem — instruction blocks', () => {
  // A block carries no variant: what distinguishes two of them is the text
  // somebody writes afterwards, so the payload is the kind alone and the
  // parser must accept it without looking for a second field.
  it('accepts a bare instruction payload', () => {
    expect(parsePaletteItem(JSON.stringify({ kind: 'instruction' }))).toEqual({
      kind: 'instruction',
    });
  });

  it('still refuses an unknown kind', () => {
    expect(parsePaletteItem(JSON.stringify({ kind: 'webhook' }))).toBeNull();
  });
});

describe('paletteNode', () => {
  // The EMPTY string is load-bearing: it is why the schema admits `\'\'` at all,
  // and it is what makes a freshly dropped block saveable before anyone has
  // written into it.
  it('creates an instruction block with empty text', () => {
    expect(paletteNode({ kind: 'instruction' }, 'instruction-1')).toEqual({
      id: 'instruction-1',
      kind: 'instruction',
      instructions: '',
    });
  });

  it('creates the other kinds with their palette variant', () => {
    expect(paletteNode({ kind: 'trigger', trigger: 'manual' }, 't1')).toEqual({
      id: 't1',
      kind: 'trigger',
      trigger: 'manual',
    });
    expect(paletteNode({ kind: 'agent', agent: 'claude' }, 'a1')).toEqual({
      id: 'a1',
      kind: 'agent',
      agent: 'claude',
      approval: 'auto',
    });
  });
});
