// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import type { Mock } from 'vitest';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { createPreloadStub } from '../__fixtures__/preload-stub';
import { stubResizeObserver } from '../__tests__/stub-resize-observer';
import type { CapabilitiesDto, RunAwaiting } from '../autogenerated';
import { CHAT_LIVE_KEY, type LiveState } from '../chats/live-text';
import type { DaemonApis } from '../daemon-api';
import type { DaemonClient } from '../daemon-client';
import type { WorkflowChatState } from './use-workflow-chat';
import { WorkflowChatPanel } from './workflow-chat-panel';

// The hook has its own spec; what this one is about is the panel's contract
// with the BUILDER — flush before a send, report the turn, count the settles.
const { chat } = vi.hoisted(() => ({
  chat: { current: null as WorkflowChatState | null },
}));
vi.mock('./use-workflow-chat', () => ({
  useWorkflowChat: () => chat.current,
}));

/** What the run's metrics route answers: a 40k window of 200k, and nothing else. */
const CHAT_METRICS = {
  context: {
    categories: [],
    totalTokens: 40_000,
    maxTokens: 200_000,
    model: null,
    autoCompactAtTokens: null,
    autoCompactEnabled: null,
    memoryFiles: [],
    servers: [],
  },
  breakdownReason: null,
  plan: null,
  planReason: null,
  takenAt: null,
  planTakenAt: null,
  totals: {
    turns: 0,
    costedTurns: 0,
    costUsd: null,
    inputTokens: null,
    outputTokens: null,
    cacheReadTokens: null,
    cacheCreationTokens: null,
    thinkingTokens: null,
    workedMs: null,
  },
};

const APIS = {
  chats: {
    readChatMetrics: vi.fn(async () => CHAT_METRICS),
  },
  agents: {
    listAgentModels: vi.fn(async () => []),
    listAgentEfforts: vi.fn(async () => ({
      efforts: [],
      unavailableReason: null,
    })),
    listAgentContextWindows: vi.fn(async () => ({
      windows: [],
      unavailableReason: null,
      unavailableKind: null,
    })),
    listAgentModelParameters: vi.fn(async () => ({
      parameters: [],
      unavailableReason: null,
    })),
  },
} as unknown as DaemonApis;

function chatState(overrides: Partial<WorkflowChatState>): WorkflowChatState {
  return {
    run: { id: 'run-1', status: 'pending' } as WorkflowChatState['run'],
    items: [],
    anchors: [],
    liveText: new Map(),
    loading: false,
    error: null,
    working: false,
    activity: null,
    settledTurns: 0,
    send: vi.fn(async () => true),
    post: vi.fn(async () => {}),
    patchSettings: vi.fn(async () => true),
    rememberContext: vi.fn(),
    deadRequestIds: new Set<string>(),
    respond: vi.fn(),
    cancel: vi.fn(async () => {}),
    discard: vi.fn(async () => {}),
    ...overrides,
  };
}

/** A live-plane entry with every field empty, overridden where a test needs one. */
function liveEntry(overrides: Partial<LiveState>): LiveState {
  return {
    text: '',
    thinkingTokens: null,
    thinkingText: null,
    thinkingSince: null,
    thinkingStretch: null,
    composingTool: null,
    composingBytes: null,
    contextTokens: null,
    contextWindowTokens: null,
    spentInputTokens: null,
    spentOutputTokens: null,
    spentCacheReadTokens: null,
    spentCostUsd: null,
    ...overrides,
  };
}

describe('WorkflowChatPanel', () => {
  let container: HTMLDivElement;
  let root: Root;
  let onBeforeSend: Mock<() => Promise<void>>;
  let onWorkingChange: Mock<(working: boolean) => void>;
  let onTurnSettled: Mock<() => void>;

  beforeEach(() => {
    stubResizeObserver();
    container = document.createElement('div');
    document.body.appendChild(container);
    root = createRoot(container);
    window.geniro = createPreloadStub();
    onBeforeSend = vi.fn(async (): Promise<void> => {});
    onWorkingChange = vi.fn<(working: boolean) => void>();
    onTurnSettled = vi.fn<() => void>();
    chat.current = chatState({});
  });

  afterEach(() => {
    act(() => root.unmount());
    container.remove();
    vi.restoreAllMocks();
  });

  it('preserves an onboarding draft when the empty builder conversation connects, without sending it', async () => {
    chat.current = chatState({ run: null });
    await paint(null, true, 'Build a team that plans and reviews features');
    expect(container.querySelector('textarea')?.value).toBe(
      'Build a team that plans and reviews features',
    );
    chat.current = chatState({});
    await paint(null, true, 'Build a team that plans and reviews features');
    expect(container.querySelector('textarea')?.value).toBe(
      'Build a team that plans and reviews features',
    );
    expect(chat.current.post).not.toHaveBeenCalled();
  });

  async function paint(
    capabilities: CapabilitiesDto | null = null,
    active = true,
    initialDraft?: string,
  ): Promise<void> {
    await act(async () => {
      root.render(
        <WorkflowChatPanel
          slug="dev-team"
          initialDraft={initialDraft}
          workflowName="Dev Team"
          apis={APIS}
          handle={null}
          client={null as unknown as DaemonClient}
          capabilities={capabilities}
          active={active}
          capabilitiesLoading={false}
          recentConfigDirs={{}}
          configProfiles={[]}
          onClose={vi.fn()}
          onBeforeSend={onBeforeSend}
          onWorkingChange={onWorkingChange}
          onTurnSettled={onTurnSettled}
        />,
      );
    });
  }

  const textarea = (): HTMLTextAreaElement => {
    const field = container.querySelector('textarea');
    if (field === null) {
      throw new Error('no composer field');
    }
    return field;
  };

  const sendButton = (): HTMLButtonElement => {
    // By its accessible NAME: Send and Stop share one slot in the composer, as
    // they do in the chat screen, so the control is a glyph rather than a word.
    const button = container.querySelector<HTMLButtonElement>(
      'button[aria-label="Send"]',
    );
    if (button === null) {
      throw new Error('no Send control');
    }
    return button;
  };

  async function type(text: string): Promise<void> {
    await act(async () => {
      const field = textarea();
      const setter = Object.getOwnPropertyDescriptor(
        HTMLTextAreaElement.prototype,
        'value',
      )?.set;
      setter?.call(field, text);
      field.dispatchEvent(new Event('input', { bubbles: true }));
    });
  }

  // The agent reads the FILE, so a canvas edit still sitting in the autosave
  // debounce is invisible to the turn about to start — and would then be
  // written over whatever that turn produced.
  it('writes pending canvas edits before the message reaches the daemon', async () => {
    await paint();
    await type('rename the reviewer');

    await act(async () => {
      sendButton().click();
    });

    expect(onBeforeSend).toHaveBeenCalledTimes(1);
    const send = chat.current?.post as ReturnType<typeof vi.fn>;
    expect(send).toHaveBeenCalledWith('rename the reviewer', []);
    expect(onBeforeSend.mock.invocationCallOrder[0] ?? 0).toBeLessThan(
      send.mock.invocationCallOrder[0] ?? 0,
    );
  });

  it('sends nothing at all when the box is empty', async () => {
    await paint();

    await act(async () => {
      sendButton().click();
    });

    expect(onBeforeSend).not.toHaveBeenCalled();
    expect(chat.current?.post).not.toHaveBeenCalled();
  });

  // The chat screen's own queue: a message typed while the agent works waits in
  // the strip, and goes out only once the turn has settled AND the canvas has
  // re-read what it wrote — the send flushes the canvas first.
  it('queues a message typed during a turn and sends it after the canvas reloads', async () => {
    const post = vi.fn(async () => {});
    chat.current = chatState({ working: true, post });
    await paint();
    await type('add a reviewer');

    await act(async () => {
      container
        .querySelector<HTMLButtonElement>('button[aria-label="Queue"]')
        ?.click();
    });

    expect(post).not.toHaveBeenCalled();
    expect(container.textContent).toContain('add a reviewer');

    chat.current = chatState({ working: false, settledTurns: 1, post });
    await paint();

    expect(onTurnSettled).toHaveBeenCalledTimes(1);
    expect(post).toHaveBeenCalledWith('add a reviewer', []);
    expect(onTurnSettled.mock.invocationCallOrder[0] ?? 0).toBeLessThan(
      post.mock.invocationCallOrder[0] ?? 0,
    );
  });

  it('keeps the queued message when the daemon refuses it, and says why', async () => {
    chat.current = chatState({ working: true });
    await paint();
    await type('add a reviewer');
    await act(async () => {
      container
        .querySelector<HTMLButtonElement>('button[aria-label="Queue"]')
        ?.click();
    });

    const post = vi.fn(async () => {
      throw new Error('daemon said no');
    });
    chat.current = chatState({ working: false, settledTurns: 1, post });
    await paint();

    expect(post).toHaveBeenCalledTimes(1);
    expect(container.textContent).toContain('add a reviewer');
    expect(container.textContent).toContain('daemon said no');
  });

  it('reports the turn to the builder, so autosave can stand down', async () => {
    await paint();
    expect(onWorkingChange).toHaveBeenLastCalledWith(false);

    chat.current = chatState({ working: true });
    await paint();
    expect(onWorkingChange).toHaveBeenLastCalledWith(true);

    chat.current = chatState({ working: false, settledTurns: 1 });
    await paint();
    expect(onWorkingChange).toHaveBeenLastCalledWith(false);
  });

  // Keyed on the COUNT, so a second turn reloads the canvas a second time —
  // a boolean going false cannot tell one settle from the next.
  it('asks the builder to reload once per settled turn', async () => {
    await paint();
    expect(onTurnSettled).not.toHaveBeenCalled();

    chat.current = chatState({ settledTurns: 1 });
    await paint();
    expect(onTurnSettled).toHaveBeenCalledTimes(1);

    chat.current = chatState({ settledTurns: 2 });
    await paint();
    expect(onTurnSettled).toHaveBeenCalledTimes(2);
  });

  it('does not ask for a reload on a re-render that settled nothing', async () => {
    await paint();
    chat.current = chatState({ settledTurns: 1 });
    await paint();

    chat.current = chatState({ settledTurns: 1, items: [] });
    await paint();

    expect(onTurnSettled).toHaveBeenCalledTimes(1);
  });

  it('puts Stop in the COMPOSER, in the Send slot, while a turn runs', async () => {
    // REPORTED as "кнопочка «Стоп» должна быть в текстере, то есть те же самые
    // компоненты, которые у нас есть уже". It was an icon in the panel's own
    // header, which is a second place to stop a turn and a second place for the
    // two to disagree about whether there is one; the chat screen has always
    // kept it in the composer, where the hand already is.
    const stop = (): Element | null =>
      container.querySelector('button[aria-label="Stop"]');
    const header = (): Element | null =>
      container.querySelector('header [aria-label="Stop the agent"]');
    await paint();
    expect(stop()).toBeNull();
    expect(sendButton()).not.toBeNull();

    chat.current = chatState({ working: true });
    await paint();

    const composer = container.querySelector('[data-slot="composer-card"]');
    expect(composer?.contains(stop())).toBe(true);
    expect(header()).toBeNull();
    // ONE slot: while the turn runs there is nothing to send, so Send is not
    // drawn beside it.
    expect(container.querySelector('button[aria-label="Send"]')).toBeNull();
  });

  it('surfaces the daemon sentence when the chat refuses', async () => {
    chat.current = chatState({ error: 'daemon said no' });

    await paint();

    expect(container.textContent).toContain('daemon said no');
  });
});

describe('WorkflowChatPanel — the transcript is the chat screen’s own', () => {
  let container: HTMLDivElement;
  let root: Root;

  beforeEach(() => {
    stubResizeObserver();
    container = document.createElement('div');
    document.body.appendChild(container);
    root = createRoot(container);
    window.geniro = createPreloadStub();
    chat.current = chatState({});
  });

  afterEach(() => {
    act(() => root.unmount());
    container.remove();
    vi.restoreAllMocks();
  });

  async function paint(
    capabilities: CapabilitiesDto | null = null,
    active = true,
  ): Promise<void> {
    await act(async () => {
      root.render(
        <WorkflowChatPanel
          slug="dev-team"
          workflowName="Dev Team"
          apis={APIS}
          handle={null}
          client={null as unknown as DaemonClient}
          capabilities={capabilities}
          active={active}
          capabilitiesLoading={false}
          recentConfigDirs={{}}
          configProfiles={[]}
          onClose={vi.fn()}
          onBeforeSend={vi.fn(async () => {})}
          onWorkingChange={vi.fn()}
          onTurnSettled={vi.fn()}
        />,
      );
    });
  }

  /** The menu option whose text is `text`, once a settings menu is open. */
  const optionWithText = (text: string): HTMLElement | undefined =>
    [...container.querySelectorAll<HTMLElement>('[role="option"]')].find(
      (option) =>
        option.querySelector('span')?.textContent === text ||
        option.textContent?.trim() === text,
    );

  /** A save whose answer the test gives when it chooses. */
  const deferredSave = (): {
    promise: Promise<boolean>;
    resolve: (saved: boolean) => void;
  } => {
    let resolve: (saved: boolean) => void = () => {};
    const promise = new Promise<boolean>((done) => {
      resolve = done;
    });
    return { promise, resolve };
  };

  /** Pick a config directory from the composer's Profile row. */
  const chooseConfigDir = async (): Promise<void> => {
    await act(async () => {
      container
        .querySelector<HTMLButtonElement>('[data-menu-trigger]')
        ?.click();
    });
    await act(async () => {
      optionWithText('Profile')?.click();
    });
    await act(async () => {
      optionWithText('Choose config directory…')?.click();
    });
    await act(async () => {});
  };

  /** The Profile row of the model settings menu, read and then closed again. */
  const readProfile = async (): Promise<string | undefined> => {
    await act(async () => {
      container
        .querySelector<HTMLButtonElement>('[data-menu-trigger]')
        ?.click();
    });
    const text = optionWithText('Profile')?.textContent ?? undefined;
    await act(async () => {
      container
        .querySelector<HTMLButtonElement>('[data-menu-trigger]')
        ?.click();
    });
    return text;
  };

  const ringLabel = (): string | null | undefined =>
    container
      .querySelector('[aria-label*="% full"]')
      ?.getAttribute('aria-label');

  const row = (
    id: string,
    kind: string,
    payload: Record<string, unknown>,
    role = 'assistant',
  ): WorkflowChatState['items'][number] =>
    ({
      id,
      runId: 'run-1',
      seq: Number(id.replace(/\D/g, '')) || 1,
      kind,
      role,
      nodeId: null,
      payload,
      createdAt: '2026-09-01T00:00:00.000Z',
    }) as WorkflowChatState['items'][number];

  it('FOLDS a turn’s tool calls into one group, as the chat screen does', async () => {
    // It used to map one row per item, so a turn that read three files was
    // three bare rows with nothing to collapse — the panel looked nothing like
    // the surface it is meant to BE. Reusing `groupTranscript` is also what
    // keeps the two honest: a row that looks wrong here looks wrong there.
    chat.current = chatState({
      items: [
        row('i1', 'tool_call', { id: 'c1', name: 'Read', input: { a: 1 } }),
        row('i2', 'tool_result', { id: 'c1', output: 'ok' }),
        row('i3', 'tool_call', { id: 'c2', name: 'Read', input: { a: 2 } }),
        row('i4', 'tool_result', { id: 'c2', output: 'ok' }),
      ],
    });

    await paint();

    // ONE group holding both calls, collapsed behind its own disclosure —
    // which is the whole of what the fold buys and what a row-per-item map
    // could not produce. Unfolded, the two calls would be two loose rows and
    // there would be no `tool-group` element at all.
    const groups = container.querySelectorAll('[data-role="tool-group"]');
    expect(groups).toHaveLength(1);
    expect(
      groups[0]?.querySelector('button')?.getAttribute('aria-expanded'),
    ).toBe('false');
    expect(groups[0]?.textContent).toContain('2 tools');
  });

  it('draws the WORKING row while a turn runs — the loading state it had none of', async () => {
    // REPORTED as "сейчас там нет ни иконки загрузки, ничего": a turn could run
    // for minutes with the dock showing the transcript exactly as it was.
    chat.current = chatState({ working: true });

    await paint();

    expect(container.textContent).toContain('Working…');
  });

  it('draws the agent’s words as they STREAM, before any row exists', async () => {
    // The live plane, folded in by `withLiveText` — the same channel and the
    // same reducer the chat screen reads. With `items` empty, nothing but the
    // live text can put this sentence on screen.
    chat.current = chatState({
      working: true,
      liveText: new Map([
        [CHAT_LIVE_KEY, liveEntry({ text: 'Adding the reviewer node' })],
      ]),
    });

    await paint();

    expect(container.textContent).toContain('Adding the reviewer node');
  });

  const dockRun = (
    overrides: Partial<WorkflowChatState['run'] & object> = {},
  ): WorkflowChatState['run'] =>
    ({
      id: 'run-1',
      status: 'completed',
      agentKind: 'claude',
      ...overrides,
    }) as WorkflowChatState['run'];

  it('has no agent-type label in its composer once the run exists', async () => {
    // The chat screen's open composer names no CLI, and neither does the dock's.
    chat.current = chatState({ run: dockRun() });

    await paint();

    const composer = container.querySelector('[data-slot="composer-card"]');
    expect(composer).not.toBeNull();
    const labels = Array.from(composer?.querySelectorAll('span') ?? []).filter(
      (span) => span.textContent?.trim() === 'claude',
    );
    expect(labels).toHaveLength(0);
  });

  it('draws the context ring beside the model settings, from the run’s own reading', async () => {
    chat.current = chatState({
      run: dockRun({ contextTokens: 50000, contextWindowTokens: 200000 }),
    });

    await paint();

    const composer = container.querySelector('[data-slot="composer-card"]');
    expect(
      composer?.querySelector('[data-slot="context-meter"]'),
    ).not.toBeNull();
    // 50k of 200k is a quarter: the figure the run row reports.
    expect(ringLabel()).toContain('Context 25% full');
  });

  it('names the run status in the header once the run has settled', async () => {
    chat.current = chatState({ run: dockRun({ status: 'completed' }) });

    await paint();

    expect(
      container.querySelector('[data-slot="workflow-chat-status"]')
        ?.textContent,
    ).toContain('completed');
  });

  it('draws no working row while the run waits on an answer', async () => {
    // The card is the question the turn is parked on. A working row under it
    // says the agent is busy, when it is waiting on the user.
    chat.current = chatState({
      run: dockRun({ status: 'running' }),
      working: true,
    });
    await paint();
    expect(container.textContent).toContain('Working…');

    chat.current = chatState({
      run: {
        ...dockRun({ status: 'running' }),
        awaiting: { kind: 'approval' } as unknown as RunAwaiting,
      } as WorkflowChatState['run'],
      working: true,
    });
    await paint();
    expect(container.textContent).not.toContain('Working…');
  });

  it('saves the config directory the user browses to on the run', async () => {
    // The Profile row's browse entry hands its folder to the run, as the chat
    // screen's composer does.
    const patchSettings = vi.fn(async () => true);
    window.geniro = {
      ...createPreloadStub(),
      pickProjectFolder: async () => '/p/work',
    } as typeof window.geniro;
    chat.current = chatState({ run: dockRun(), patchSettings });
    // The Profile row is offered only where the daemon says the CLI reads a
    // config directory.
    await paint({
      approvals: [],
      configDirs: [{ agent: 'claude', unavailableReason: null }],
    } as unknown as CapabilitiesDto);

    await chooseConfigDir();

    expect(patchSettings).toHaveBeenCalledWith({ configDir: '/p/work' });
  });

  it('names a run needing input when its transcript holds a request nobody has answered', async () => {
    // The run row names the wait only once its announce lands, but the request row
    // is in the window the moment the card is raised. The chat screen counts either,
    // so the header does too.
    chat.current = chatState({
      run: dockRun({ status: 'running' }),
      items: [
        row('r1', 'approval_request', {
          id: 'req-1',
          toolName: 'Bash',
          input: { command: 'ls' },
        }),
      ],
    });

    await paint();

    expect(
      container.querySelector('[data-slot="workflow-chat-status"]')
        ?.textContent,
    ).toContain('needs more info');
  });

  it('does not name a request its verdict has already answered as needing input', async () => {
    chat.current = chatState({
      run: dockRun({ status: 'running' }),
      items: [
        row('r1', 'approval_request', {
          id: 'req-1',
          toolName: 'Bash',
          input: { command: 'ls' },
        }),
        row('v1', 'approval_verdict', { id: 'req-1', allow: true }),
      ],
    });

    await paint();

    expect(
      container.querySelector('[data-slot="workflow-chat-status"]')
        ?.textContent,
    ).not.toContain('needs more info');
  });

  it('reads the context readout from the run’s metrics route, and files its figures on the run row', async () => {
    // The ring and the readout it opens are one reading. The readout asks the
    // run's own metrics route, and its run-level figures go back onto the row, so
    // the ring agrees with the panel it was opened from.
    const rememberContext = vi.fn();
    chat.current = chatState({
      run: dockRun({ contextTokens: 10_000, contextWindowTokens: 200_000 }),
      rememberContext,
    });
    await paint();

    await act(async () => {
      container
        .querySelector<HTMLButtonElement>('[aria-label*="% full"]')
        ?.click();
    });
    await act(async () => {});

    expect(APIS.chats.readChatMetrics).toHaveBeenCalledWith(
      expect.objectContaining({ runId: 'run-1' }),
    );
    expect(rememberContext).toHaveBeenCalledWith('run-1', 40_000, 200_000);
  });

  it('does not name a request whose verdict came back expired as needing input', async () => {
    // Its turn ended before an answer arrived, so nothing is waiting on the card.
    chat.current = chatState({
      run: dockRun({ status: 'completed' }),
      items: [
        row('r1', 'approval_request', {
          id: 'req-1',
          toolName: 'Bash',
          input: { command: 'ls' },
        }),
      ],
      deadRequestIds: new Set(['req-1']),
    });

    await paint();

    expect(
      container.querySelector('[data-slot="workflow-chat-status"]')
        ?.textContent,
    ).not.toContain('needs more info');
  });

  it('does not repeat the verdict of a request whose card is on screen', async () => {
    // The card that asked draws its own settled line, so the verdict row beside it
    // would only say the same thing again.
    chat.current = chatState({
      run: dockRun({ status: 'completed' }),
      items: [
        row('r1', 'approval_request', {
          id: 'req-1',
          toolName: 'Bash',
          input: { command: 'ls' },
        }),
        row('v1', 'approval_verdict', { id: 'req-1', allow: true }),
      ],
    });

    await paint();

    expect(container.textContent).toContain('Bash');
    expect(container.textContent).not.toContain('✓ tool approved');
  });

  it('shows the run’s profile until the daemon answers the save, then the one it answered with', async () => {
    // A save the daemon has not answered is not the run's profile yet, so the chip
    // waits for the row — the chat screen's chips work the same way.
    const folder = deferredSave();
    const patchSettings = vi.fn(() => folder.promise);
    window.geniro = {
      ...createPreloadStub(),
      pickProjectFolder: async () => '/p/work',
    } as typeof window.geniro;
    const capabilities = {
      approvals: [],
      configDirs: [{ agent: 'claude', unavailableReason: null }],
    } as unknown as CapabilitiesDto;
    chat.current = chatState({ run: dockRun(), patchSettings });
    await paint(capabilities);

    await chooseConfigDir();
    expect(patchSettings).toHaveBeenCalledTimes(1);
    expect(await readProfile()).not.toContain('work');

    await act(async () => {
      folder.resolve(true);
    });
    chat.current = chatState({
      run: dockRun({ configDir: '/p/work' }),
      patchSettings,
    });
    await paint(capabilities);
    expect(await readProfile()).toContain('work');
  });

  it('puts the Profile chip back when the daemon refuses the folder', async () => {
    // A save the daemon refuses leaves the run on its old profile, so the chip
    // must show that profile again rather than keep a folder never taken.
    const patchSettings = vi.fn(async () => false);
    window.geniro = {
      ...createPreloadStub(),
      pickProjectFolder: async () => '/p/work',
    } as typeof window.geniro;
    chat.current = chatState({ run: dockRun(), patchSettings });
    await paint({
      approvals: [],
      configDirs: [{ agent: 'claude', unavailableReason: null }],
    } as unknown as CapabilitiesDto);

    await chooseConfigDir();

    const profile = await readProfile();
    expect(profile).toContain('default');
    expect(profile).not.toContain('work');
  });

  it('reads the tool-step setting again when the builder comes back on screen', async () => {
    // The builder stays mounted while it is hidden, so a change made in Settings
    // reaches the dock only if the setting is read again on activation.
    const stub = createPreloadStub();
    const settings = await stub.getSettings();
    const getSettings = vi.fn(async () => settings);
    window.geniro = { ...stub, getSettings } as typeof window.geniro;
    chat.current = chatState({});

    await paint(null, false);
    expect(getSettings).not.toHaveBeenCalled();

    await paint(null, true);
    expect(getSettings).toHaveBeenCalledTimes(1);
  });

  it('closes a tool group that never returned once the run has settled', async () => {
    // A call with no result is still running while the run is. Once the run
    // settles nothing will ever return it, so its spinner has to stop.
    const calls = [
      row('i1', 'tool_call', {
        id: 'c1',
        name: 'Bash',
        input: { command: 'sleep 9' },
      }),
    ];
    chat.current = chatState({
      items: calls,
      working: true,
      run: dockRun({ status: 'running' }),
    });

    await paint();
    expect(
      container.querySelector('[data-role="tool-group"] .animate-spin'),
    ).not.toBeNull();

    chat.current = chatState({ items: calls, run: dockRun() });
    await paint();
    expect(
      container.querySelector('[data-role="tool-group"] .animate-spin'),
    ).toBeNull();
  });

  it('names the phrase the run is working on in place of a generic word', async () => {
    chat.current = chatState({
      run: dockRun({ status: 'running' }),
      working: true,
      activity: 'running Bash',
    });

    await paint();

    expect(container.textContent).toContain('running Bash');
    // The phrase stands in for the generic word, rather than sitting beside it.
    expect(container.textContent).not.toContain('Working…');
  });

  it('draws the placeholder for a geniro tool still being written, as the chat screen does', async () => {
    chat.current = chatState({
      run: dockRun({ status: 'running' }),
      working: true,
      liveText: new Map([
        [
          CHAT_LIVE_KEY,
          liveEntry({
            composingTool: 'mcp__geniro-run-1__show_artifact',
            composingBytes: 1200,
          }),
        ],
      ]),
    });

    await paint();

    expect(
      container.querySelector('[data-slot="composing-card"]'),
    ).not.toBeNull();
  });

  it('lets the model settings change the open chat’s auto-compact, as the chat screen does', async () => {
    const patchSettings = vi.fn(async () => true);
    chat.current = chatState({
      run: dockRun({ autoCompactPercent: 80 }),
      patchSettings,
    });

    await paint();
    await act(async () => {
      container
        .querySelector<HTMLButtonElement>('[data-menu-trigger]')
        ?.click();
    });
    await act(async () => {
      optionWithText('Auto-compact')?.click();
    });
    await act(async () => {
      optionWithText('at 60%')?.click();
    });

    expect(patchSettings).toHaveBeenCalledWith({ autoCompactPercent: 60 });
  });
});
