import type { Meta, StoryObj } from '@storybook/react-vite';

import type { LoginSessionDto } from '../autogenerated';
import { CliLoginProgress } from './cli-login-progress';
import { CollapsibleCard } from './collapsible-card';
import { Card } from './ui/card';

function session(overrides: Partial<LoginSessionDto>): LoginSessionDto {
  return {
    id: 'session-1',
    agent: 'claude',
    status: 'waiting',
    url: 'https://claude.ai/oauth/authorize?code=abc123',
    message: null,
    ...overrides,
  };
}

/**
 * The `band` variant's REAL host, and the padding is not decoration.
 *
 * The band is built as a full-bleed strip across the foot of a card, so its
 * `-mx-4` exists to cancel that card's own `px-4` and let the rule reach both
 * edges. Dropped into an unpadded box it hangs 16px over both sides instead —
 * the rule and the fill overshooting the rounded border, and the headline
 * wrapping because the row is laid out 32px wider than the box that shows it.
 * That is the defect the component's own docblock warns about and the one
 * `Chats.tsx` adds a `px-4` wrapper to avoid, and this story shipped with it.
 *
 * So the host mirrors `agent-config-list.tsx` exactly: `CollapsibleCard`,
 * whose body is `px-4 py-4`, with `-mb-4` pulling the band flush to the foot.
 */
function BandHost({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    <div className="w-[540px]">
      <CollapsibleCard
        open
        onToggle={() => undefined}
        header={<span className="text-sm font-medium">claude</span>}>
        <p className="m-0 text-sm text-muted-foreground">
          Signed in · /opt/homebrew/bin/claude
        </p>
        <div className="-mb-4">{children}</div>
      </CollapsibleCard>
    </div>
  );
}

/**
 * The `inline` variant's real host: a line among rows in the MCP dialog, where
 * the band's negative margin took the pasted-code field off the edge. Narrower
 * on purpose — that width is what the variant exists for.
 */
function InlineHost({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    <Card className="w-[380px] gap-2 p-3">
      <span className="text-xs font-medium tracking-wide text-muted-foreground uppercase">
        MCP servers
      </span>
      <ul className="m-0 flex list-none flex-col gap-1 p-0">
        <li className="flex items-center gap-2 px-1.5 py-1 text-xs">
          <span
            aria-hidden="true"
            className="size-1.5 shrink-0 rounded-full bg-success"
          />
          linear
        </li>
        <li className="flex items-center gap-2 px-1.5 py-1 text-xs">
          <span
            aria-hidden="true"
            className="size-1.5 shrink-0 rounded-full bg-muted-foreground"
          />
          sentry
        </li>
        <li>{children}</li>
      </ul>
    </Card>
  );
}

const meta = {
  title: 'Components/CliLoginProgress',
  component: CliLoginProgress,
  args: {
    session: session({}),
    error: null,
    onSubmitCode: () => undefined,
    onCancel: () => undefined,
    onDismiss: () => undefined,
  },
  // ONE decorator that picks the host, rather than a story-level one layered
  // over a meta-level default: Storybook COMPOSES decorators (story innermost,
  // then meta, then global) rather than letting the narrower one win, so an
  // `InlineVariant` override renders the inline host inside the band's card.
  decorators: [
    (story, context) =>
      context.args.variant === 'inline' ? (
        <InlineHost>{story()}</InlineHost>
      ) : (
        <BandHost>{story()}</BandHost>
      ),
  ],
} satisfies Meta<typeof CliLoginProgress>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};

export const NeedsCode: Story = {
  args: { session: session({ status: 'needs_code' }) },
};

export const ServerHandoff: Story = {
  args: {
    session: session({
      status: 'succeeded',
      message:
        'The connector will be available the next time you start Claude Code.',
    }),
    scope: 'server',
  },
};

export const Failed: Story = {
  args: {
    session: session({ status: 'failed', url: null }),
    error: 'The CLI exited before the sign-in finished.',
  },
};

export const InlineVariant: Story = {
  args: { session: session({ status: 'needs_code' }), variant: 'inline' },
};
