import type { Meta, StoryObj } from '@storybook/react-vite';

import type {
  AgentMcpListingDto as AgentMcpListing,
  AgentMcpServer,
} from '../autogenerated';
import { McpSection } from './mcp-section';

function server(
  overrides: Partial<AgentMcpServer> & Pick<AgentMcpServer, 'name' | 'status'>,
): AgentMcpServer {
  return {
    target: null,
    transport: 'stdio',
    detail: null,
    scope: 'workspace',
    shadowsUser: false,
    disabled: false,
    toggleUnavailableReason: null,
    signInUnavailableReason: null,
    approveUnavailableReason: null,
    ...overrides,
  };
}

const MIXED_LISTING: AgentMcpListing = {
  servers: [
    server({
      name: 'codegraph',
      status: 'connected',
      target: 'codegraph mcp start',
    }),
    server({
      name: 'linear',
      status: 'failed',
      detail: 'connect ECONNREFUSED 127.0.0.1:9821 — is the server running?',
    }),
    server({ name: 'ticktick', status: 'needs_auth' }),
    server({ name: 'sentry', status: 'pending' }),
    server({ name: 'playwright', status: 'disabled', disabled: true }),
    server({ name: 'geniro', status: 'connected', scope: 'user' }),
  ],
  unavailableReason: null,
  pending: false,
  interactiveOnlyNote:
    "Claude also loads this folder's browser tools in its own interactive session — headless turns run without them.",
};

const meta = {
  title: 'Components/McpSection',
  component: McpSection,
  args: {
    listing: MIXED_LISTING,
    loading: false,
    onSetEnabled: () => undefined,
    onSignIn: () => undefined,
    onRefresh: () => undefined,
  },
  decorators: [
    (story) => (
      <div className="w-80 rounded-lg border border-border bg-card shadow-panel-sm">
        {story()}
      </div>
    ),
  ],
} satisfies Meta<typeof McpSection>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};

export const Loading: Story = {
  args: { listing: undefined, loading: true },
};

export const Empty: Story = {
  args: {
    listing: {
      servers: [],
      unavailableReason: null,
      pending: false,
      interactiveOnlyNote: null,
    },
  },
};

export const Unavailable: Story = {
  args: {
    listing: {
      servers: [],
      unavailableReason:
        'daemon GET /v1/agents/cursor-agent/mcp?dir=%2FUsers%2Fdev%2Fwork failed (504): the CLI did not answer in time',
      pending: false,
      interactiveOnlyNote: null,
    },
  },
};

export const ReadOnly: Story = {
  args: { onSetEnabled: undefined, onSignIn: undefined, onRefresh: undefined },
};
