import type { AddMcpServerDto, AgentMcpConfigDto } from '../autogenerated';

/**
 * The pure half of the "Add MCP server" dialog: turning its two forms into
 * what the daemon takes, and saying — before the press — why a form is not
 * ready yet. The daemon re-checks every rule here (`addMcpServerSchema`,
 * `checkMcpServerDefinitions`); these exist so the Add and Save buttons can be
 * disabled with a reason instead of answering a round trip with a 400.
 */

/** One server as the Add form states it — the route's body minus its address. */
export type McpServerDraft = Omit<AddMcpServerDto, 'agent' | 'configDir'>;

/** A profile's servers by name, in the CLI's own JSON shape. */
export type McpServerDefinitions = NonNullable<AgentMcpConfigDto['servers']>;

export type McpTransport = 'stdio' | 'http';

/** The Add form's fields, as typed — lists are one entry per line. */
export interface McpServerFormValues {
  name: string;
  transport: McpTransport;
  command: string;
  /** One argument per line, each taken exactly as written. */
  args: string;
  /** `KEY=VALUE`, one per line. */
  env: string;
  url: string;
  /** `Name: value`, one per line. */
  headers: string;
}

export const EMPTY_MCP_SERVER_FORM: McpServerFormValues = {
  name: '',
  transport: 'stdio',
  command: '',
  args: '',
  env: '',
  url: '',
  headers: '',
};

/** C0 controls and DEL — the daemon refuses them in anything that reaches argv. */
// eslint-disable-next-line no-control-regex
const CONTROL = /[\u0000-\u001f\u007f]/;
const ENV_KEY = /^[A-Za-z_][A-Za-z0-9_]*$/;
const HEADER_NAME = /^[A-Za-z0-9][!#$%&'*+.^_`|~0-9A-Za-z-]*$/;
const MAX_NAME_LENGTH = 128;

export type McpFormCheck =
  { ok: true; server: McpServerDraft } | { ok: false; reason: string };

/** Non-blank lines, trimmed of their line break alone. */
function lines(text: string): string[] {
  return text
    .split('\n')
    .map((line) => line.replace(/\r$/, ''))
    .filter((line) => line.trim() !== '');
}

/** `KEY=VALUE` lines into a map, or the first line that is not one. */
function readPairs(
  text: string,
  separator: '=' | ':',
  keyRule: RegExp,
  what: string,
): { ok: true; pairs: Record<string, string> } | { ok: false; reason: string } {
  const pairs: Record<string, string> = {};
  for (const line of lines(text)) {
    const at = line.indexOf(separator);
    const key = at < 0 ? '' : line.slice(0, at).trim();
    const value = at < 0 ? '' : line.slice(at + 1).trim();
    if (at < 0 || !keyRule.test(key)) {
      return {
        ok: false,
        reason: `“${line.trim()}” is not a ${what} line (${separator === '=' ? 'KEY=value' : 'Name: value'})`,
      };
    }
    if (CONTROL.test(value)) {
      return { ok: false, reason: `${key} contains a control character` };
    }
    pairs[key] = value;
  }
  return { ok: true, pairs };
}

/**
 * The Add form as the daemon's body, or the first reason it is not ready. A
 * server NAME with a space or a leading dash is refused — it becomes the CLI's
 * `mcp add <name>` positional and later `mcp login <name>`'s.
 */
export function readMcpServerForm(values: McpServerFormValues): McpFormCheck {
  const name = values.name.trim();
  if (name === '') {
    return { ok: false, reason: 'Name the server' };
  }
  if (
    /\s/.test(name) ||
    name.startsWith('-') ||
    CONTROL.test(name) ||
    name.length > MAX_NAME_LENGTH
  ) {
    return {
      ok: false,
      reason:
        'A server name has no spaces, does not start with a dash, and is at most 128 characters',
    };
  }
  if (values.transport === 'http') {
    const url = values.url.trim();
    if (!/^https?:\/\/\S+$/i.test(url) || CONTROL.test(url)) {
      return {
        ok: false,
        reason: 'Enter the server’s http:// or https:// URL',
      };
    }
    const headers = readPairs(values.headers, ':', HEADER_NAME, 'header');
    if (!headers.ok) {
      return headers;
    }
    return {
      ok: true,
      server: { name, transport: 'http', url, headers: headers.pairs },
    };
  }
  const command = values.command.trim();
  if (command === '' || CONTROL.test(command)) {
    return { ok: false, reason: 'Enter the command that starts the server' };
  }
  const args = lines(values.args);
  if (args.some((arg) => CONTROL.test(arg))) {
    return { ok: false, reason: 'An argument contains a control character' };
  }
  const env = readPairs(values.env, '=', ENV_KEY, 'environment');
  if (!env.ok) {
    return env;
  }
  return {
    ok: true,
    server: { name, transport: 'stdio', command, args, env: env.pairs },
  };
}

export type McpJsonCheck =
  { ok: true; servers: McpServerDefinitions } | { ok: false; reason: string };

/**
 * The JSON editor's text as a server map, or why it is not one yet: valid
 * JSON, an object of objects, each launching a `command` or reaching a `url`
 * — the shape every CLI shares, which the daemon checks again.
 */
export function readMcpServersJson(text: string): McpJsonCheck {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (err: unknown) {
    return {
      ok: false,
      reason: `Not valid JSON: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return {
      ok: false,
      reason:
        'The servers must be one JSON object mapping each name to its settings',
    };
  }
  const servers: McpServerDefinitions = {};
  for (const [name, entry] of Object.entries(parsed)) {
    if (entry === null || typeof entry !== 'object' || Array.isArray(entry)) {
      return { ok: false, reason: `“${name}” must be an object of settings` };
    }
    const record = entry as Record<string, unknown>;
    const command =
      typeof record.command === 'string' ? record.command.trim() : '';
    const url = typeof record.url === 'string' ? record.url.trim() : '';
    if (command === '' && url === '') {
      return {
        ok: false,
        reason: `“${name}” needs a "command" to launch or a "url" to reach`,
      };
    }
    servers[name] = record;
  }
  return { ok: true, servers };
}

/** How the editor shows a document: two-space JSON, as the CLIs write theirs. */
export function formatMcpServersJson(servers: McpServerDefinitions): string {
  return `${JSON.stringify(servers, null, 2)}\n`;
}
