// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, describe, expect, it, vi } from 'vitest';

import type {
  AgentMcpListingDto as AgentMcpListing,
  AgentMcpServer,
} from '../autogenerated';
import { McpSection } from './mcp-section';

(
  globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

let root: Root | null = null;
let container: HTMLDivElement | null = null;

afterEach(() => {
  act(() => {
    root?.unmount();
  });
  container?.remove();
  root = null;
  container = null;
});

function listing(
  ...servers: {
    name: string;
    toggleUnavailableReason?: string | null;
    target?: string | null;
    detail?: string | null;
    status?: AgentMcpServer['status'];
    disabled?: boolean;
  }[]
): AgentMcpListing {
  return {
    servers: servers.map((s) => ({
      name: s.name,
      target: s.target === undefined ? `node ${s.name}.js` : s.target,
      transport: 'stdio',
      status: s.status ?? 'connected',
      detail: s.detail ?? null,
      scope: 'project',
      disabled: s.disabled ?? false,
      toggleUnavailableReason: s.toggleUnavailableReason ?? null,
    })),
    unavailableReason: null,
  } as unknown as AgentMcpListing;
}

function render(props: Parameters<typeof McpSection>[0]): HTMLDivElement {
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
  act(() => {
    root!.render(<McpSection {...props} />);
  });
  return container;
}

describe('McpSection', () => {
  it('offers a switch on a surface that has a write path', () => {
    const el = render({
      listing: listing({ name: 'srv' }),
      loading: false,
      onSetEnabled: vi.fn(),
    });

    expect(el.querySelector('[aria-label="Load srv"]')).not.toBeNull();
  });

  it('shows the daemon’s reason instead of a switch it could not honour', () => {
    const el = render({
      listing: listing({
        name: 'srv',
        toggleUnavailableReason: 'not a project server',
      }),
      loading: false,
      onSetEnabled: vi.fn(),
    });

    expect(el.querySelector('[aria-label="Load srv"]')).toBeNull();
    expect(
      el.querySelector('[aria-label="not a project server"]'),
    ).not.toBeNull();
  });

  it('renders NEITHER switch nor lock on a read-only surface', () => {
    // The graph inspector's arm, and the reason this component was promoted
    // out of the chat panel. Its rows come from a listing taken in a folder
    // geniro owns, so every one of them carries a folder-scoped
    // `toggleUnavailableReason` — rendering that padlock would explain why a
    // control is unavailable on a surface where no control was ever going to
    // appear, citing a folder the workflow does not yet have.
    const el = render({
      listing: listing({
        name: 'srv',
        toggleUnavailableReason: 'not a project server',
      }),
      loading: false,
    });

    expect(el.querySelector('[aria-label="Load srv"]')).toBeNull();
    expect(el.querySelector('[aria-label="not a project server"]')).toBeNull();
    // ...but the server itself is still listed.
    expect(el.textContent).toContain('srv');
  });

  it('renders the hint when one is given, and nothing when not', () => {
    const withHint = render({
      listing: listing({ name: 'srv' }),
      loading: false,
      hint: 'Global servers only.',
    });
    expect(withHint.textContent).toContain('Global servers only.');

    act(() => {
      root!.unmount();
    });
    container!.remove();
    const without = render({
      listing: listing({ name: 'srv' }),
      loading: false,
    });
    expect(without.textContent).not.toContain('Global servers only.');
  });

  it('carries NO tooltip for a server whose CLI reported neither a target nor a detail', () => {
    // cursor prints `<name>: ready` and nothing else, so both fields are null.
    // What this catches is a `?? ''` fallback, which renders an empty tooltip
    // that follows the pointer around saying nothing. It does NOT pin the
    // trailing `?? undefined` — React omits a null attribute anyway, so that
    // half exists only to satisfy `title?: string`.
    const el = render({
      listing: listing({ name: 'srv', target: null }),
      loading: false,
    });

    const row = el.querySelector('li');
    expect(row).not.toBeNull();
    expect(row?.hasAttribute('title')).toBe(false);
    // ...and the server is still listed, health badge and all.
    expect(row?.textContent).toContain('srv');
  });

  it('carries no tooltip for an EMPTY target either, not just a null one', () => {
    // Absent is not only null: claude's parser yields `target: ''` for a row
    // whose command column is blank, and `??` would let that through as
    // `title=""` — an empty tooltip that follows the pointer saying nothing.
    const el = render({
      listing: listing({ name: 'srv', target: '', detail: null }),
      loading: false,
    });

    expect(el.querySelector('li')?.hasAttribute('title')).toBe(false);
  });

  it('falls back to the target when the CLI gave a command but no detail', () => {
    // The middle rung, which nothing else asserted: rewriting the tooltip as
    // `title={server.detail ?? undefined}` silently drops claude's command
    // line and every other case here still passes.
    const el = render({
      listing: listing({ name: 'srv' }),
      loading: false,
    });

    expect(el.querySelector('li')?.getAttribute('title')).toBe('node srv.js');
  });

  it('still prefers the detail over the target when the CLI gave one', () => {
    // The precedence the null-handling must not have quietly reordered: a
    // failure reason is the actionable half and outranks the command line.
    const el = render({
      listing: listing({ name: 'srv', detail: 'HTTP 502: dial failed' }),
      loading: false,
    });

    expect(el.querySelector('li')?.getAttribute('title')).toBe(
      'HTTP 502: dial failed',
    );
  });

  it('renders a CLI-reported disabled server struck through, with its own badge', () => {
    // cursor's `mcp disable` state. It is a stated choice rather than a
    // failure, so it must not wear the destructive badge — and the row still
    // has to be visible: before this status existed the row vanished entirely.
    const el = render({
      listing: listing({ name: 'off-srv', status: 'disabled', disabled: true }),
      loading: false,
    });

    const row = el.querySelector('li');
    expect(row?.textContent).toContain('off-srv');
    expect(row?.textContent).toContain('disabled');
    expect(row?.querySelector('.line-through')).not.toBeNull();
  });

  it('shows the adapter’s own sentence rather than an empty list', () => {
    const el = render({
      listing: {
        servers: [],
        unavailableReason: 'cursor-agent cannot list MCP servers',
      } as unknown as AgentMcpListing,
      loading: false,
    });

    expect(el.textContent).toContain('cursor-agent cannot list MCP servers');
    expect(el.textContent).not.toContain('No servers');
  });
});
